stolostron/multicluster-global-hub

deploy/deploy_leaf_hub.sh

Mac's base64 does not have -w option. It has "-w 0" behaviour by default.
see https://stackoverflow.com/questions/46463027/base64-doesnt-have-w-option-in-mac

handle base64 -w 0 on Mac

---

deploy/undeploy_leaf_hub.sh

not scaling down controllers has been found to sometimes skip graceful shutdowns, causing finalizers placed by the controllers not getting removed.
- changed order of deletion: syncers before hoh-system namespace (policies are in hot-system namespace with a finalizer from leaf-hub-status-sync)
- descale syncers to 0 before deleting deployments

undeploy leaf-hub syncers before deleting ns

---

deploy/README.md
deploy/deploy_hub_of_hubs.sh
deploy/deploy_hub_of_hubs_agent.sh
deploy/deploy_hub_of_hubs_agent_sync_service.sh
deploy/deploy_hub_of_hubs_sync_service.sh
deploy/deploy_kafka.sh
deploy/undeploy_hub_of_hubs.sh
deploy/undeploy_hub_of_hubs_agent.sh

This PR is used to enable deploy `hub-cluster-controller` and `hub-of-hubs-addon-controller` into HoH cluster by using our existing deployment scripts. Also enable test with the `latest` image tag. I have published all the required images with the latest tag from `main` branch.
After deployed hoh, the agent deployment can be optional. It can be done via `hub-cluster-controller` if the leaf hub cluster is a managed cluster of HoH cluster.

Enable hub controller

---

deploy/deploy_hub_of_hubs.sh

couple of changes:
1. there is a new component `grc-policy-addon-controller` introduced for grc and remove the `grc-grcui` and `grc-grcuiapi`. so we need to fork it and add back the removed components.
2. update the `governance-policy-propagator` to align with `release-2.5`.
3. Get the `SNAPSHOT` environment to enable deploy ACM Hub with the specified snapshot.

Support ACM 2.5

---

doc/hypershift/manifests/manifestwork-config-policy-controller.yaml
doc/hypershift/manifests/manifestwork-policy-framework.yaml

add hosted cluster name to addon deploy manifests so that we can create manifestworks for different hosted cluster in hypershift management cluster namespace.

add hosted cluster name to addon deploy manifests.

---

test/setup/e2e_setup.sh

`HUB_KUBECONFIG` variable was overwritten in `leafhub_setup.sh`. so the `initPolicy` is using leaf hub kubeconfig. that is why cannot watch the local policy.
Replace with `HOH_KUBECONFIG`

fix cannot propogate local policy

---

operator/Dockerfile
operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/main.go
operator/pkg/constants/constants.go
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/controllers/leafhub/addon.go
operator/pkg/controllers/leafhub/leafhub_controller.go
operator/pkg/controllers/leafhub/manifestwork.go
operator/pkg/deployer/hoh_deployer.go

ref: https://github.com/stolostron/backlog/issues/25023
According to https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/predicate/predicate.go#L140
We should use `GenerationChangedPredicate` if we only want to trigger reconcile when spec changes. @clyang82 

add support for hub-of-hubs operator to watch owned resources

---

operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/controllers/leafhub/leafhub_controller.go
operator/pkg/controllers/leafhub/packagemanifest.go

this PR tries to fix packagemenifest access issue with controller-runtime client.
use another dynamic client to get packagemenifest instead of controller-runtime client.

create dynamic client for packagemanifest.

---

operator/README.md
operator/bundle/manifests/multicluster-globalhub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-globalhub-operator.clusterserviceversion.yaml
operator/config/samples/operator_v1alpha1_multiclusterglobalhub.yaml
operator/pkg/condition/condition.go
operator/pkg/constants/constants.go
operator/pkg/controllers/hubofhubs/manifests/console-cleanup/hoh-console-cleanup.yaml
operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-script.yaml
operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-setup.yaml
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/controllers/leafhub/addon.go
operator/pkg/controllers/leafhub/leafhub_controller.go
operator/pkg/controllers/leafhub/manifests/hypershift/hub/hosting/12-multicluster-globalhub-agent-applier.yaml
operator/pkg/renderer/hoh_renderer.go

follow up PR for https://github.com/stolostron/multicluster-globalhub/pull/131
rename hub-of-hubs to multicluster-globalhub
There are still some need to be renamed, eg.
```
hub-of-hubs.open-cluster-management.io/managed-by-hoh
```
and 
```
hub-of-hubs.open-cluster-management.io/used-by: hub-of-hubs
```
but these remaining ones need to be carefully handled, because console needs the old ones.

rename hub-of-hubs to multicluster-globalhub.

---

agent/cmd/agent/main.go
agent/pkg/controllers/clusterrole_controller.go
agent/pkg/controllers/clusterrolebinding_controller.go
agent/pkg/controllers/controllers.go
agent/pkg/controllers/controllers_integration_test.go
operator/pkg/controllers/hubofhubs/manifests/placement/placement.yaml

ref: https://github.com/stolostron/backlog/issues/25232
2 fixes:
1. filter out the `local-cluster` to be selected as a regional hub cluster
2. init `clusterrole` and `clusterrolebinding` by agent. the previous way cannot be executed. use kubeclient to create such resources.

Init resources

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/config/rbac/role.yaml
operator/config/samples/storage/deploy_postgres.sh
operator/config/samples/transport/deploy_kafka.sh
operator/pkg/condition/condition.go
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/constants/constants.go
operator/pkg/controllers/hubofhubs/manifests/console-cleanup/hoh-console-cleanup.yaml
operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-script.yaml
operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-setup.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/clusterrolebinding.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/configmap-ca-bundle.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/ingress.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/role.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/rolebinding.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/service.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/serviceaccount.yaml
operator/pkg/controllers/hubofhubs/manifests/placement/managedclustersetbinding.yaml
operator/pkg/controllers/hubofhubs/manifests/placement/placement.yaml
operator/pkg/controllers/hubofhubs/manifests/rbac/deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/rbac/networkpolicy.yaml
operator/pkg/controllers/hubofhubs/manifests/rbac/secret-opa-data.yaml
operator/pkg/controllers/hubofhubs/manifests/rbac/service.yaml
operator/pkg/controllers/hubofhubs/manifests/rbac/serviceaccount.yaml
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/controllers/leafhub/addon.go
operator/pkg/controllers/leafhub/leafhub_controller.go
operator/pkg/controllers/leafhub/manifestwork.go

ref: https://github.com/stolostron/backlog/issues/25234
Add support to install multicluster-global-hub-operator and operands in any namespace that ACM is installed within.
To create the storage secret and transport secret for customized namespace, need to expose env `export TARGET_NAMESPACE=<the operator installation namespace>` before executing https://github.com/stolostron/multicluster-global-hub/blob/main/operator/config/samples/transport/deploy_kafka.sh and https://github.com/stolostron/multicluster-global-hub/blob/main/operator/config/samples/storage/deploy_postgres.sh
To deploy operator locally, change the `namespace` in https://github.com/stolostron/multicluster-global-hub/blob/main/operator/config/default/kustomization.yaml and then execute `make deploy`
Signed-off-by: morvencao …

support installation in any namespace.

---

agent/cmd/agent/main.go

resolve: https://github.com/stolostron/backlog/issues/24752
the root cause is if there is an existing lease in your environment, it needs spend 137s to acquire lease.
if that is brand new environment, there is no such problem.
we have not decided to use OpenShift default values yet, because it impact on the high available https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#high-availability
so for our case, let me use the default value in this release.
we may expose those values in mgh CRD and pass them into each operator.
I am not sure if it impacts on this issue or not - https://github.com/stolostron/backlog/issues/23768. Let me observe it.

use the default control-runtime default values

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/pkg/controllers/leafhub/leafhub_controller.go

multicluster-global-hub-operator need this permission to add annotation to (hypershift hosted) managedcluster so that it can be a regional hub. 

add missing permission for operator.

---

operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/controllers/leafhub/leafhub_controller.go
operator/pkg/controllers/leafhub/manifestwork.go

When the manifestworks that contains resdources applied to hosting cluster is updated or deleted, it should never trigger hosting cluster reconcile, instead, it should triiger hosted cluster reconcile.

fix hosting cluster reconcile triggered by manifestwork changes.

---

operator/pkg/controllers/hubofhubs/finalizer.go

fix:
```
1.6620269077928638e+09	ERROR	Reconciler error	{"controller": "managedcluster", "controllerGroup": "cluster.open-cluster-management.io", "controllerKind": "ManagedCluster", "managedCluster": {"name":"hub1"}, "namespace": "", "name": "hub1", "reconcileID": "f23dbe90-f331-4b73-9984-e4a9aed7254e", "error": "failed to set condition(True): failed to update status condition: Operation cannot be fulfilled on multiclusterglobalhubs.operator.open-cluster-management.io \"multiclusterglobalhub\": the object has been modified; please apply your changes to the latest version and try again"}
1.6620270477579641e+09	ERROR	failed to remove namespaced resources	{"controller": "multiclusterglobalhub", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": …
```

fix conflict in configmap deletion.

---

manager/pkg/specsyncer/spec2db/controller/hoh_config_spec_sync_test.go
test/pkg/postgres/main.go
test/pkg/testpostgres/testpostgres.go

When running multiple testing embeded postgresql instances in the same host,
the data path must be different, otherwise there will be conflict.

fix data path conflict of testing embed postgres.

---

agent/Makefile
manager/Makefile
operator/Makefile

format code with same rule in the root Makefile:
https://github.com/stolostron/multicluster-global-hub/blob/ba2f9d21f7fab6259d4c22f77625176aaacdcccf/Makefile#L83-L87
to avoid unnecessary changes after build images.

format code with same rule.

---

sonar-project.properties

`.yaml` is for test purpose. we should not analysis it in code coverage.

exclude yaml file to code coverage

---

manager/pkg/webhook/admission_handler_test.go
manager/pkg/webhook/admission_suite_test.go

fix lint issues when build manager image:
```
pkg/webhook/admission_suite_test.go:41:2: `k8sClient` is unused (deadcode)
k8sClient  client.Client // You'll be using this client in your tests.
^
pkg/webhook/admission_suite_test.go:42:2: `kubeClient` is unused (deadcode)
kubeClient *kubernetes.Clientset
^
pkg/webhook/admission_handler_test.go:69:13: Error return value of `c.Create` is not checked (errcheck)
c.Create(ctx, testPlacement, &client.CreateOptions{})
^
pkg/webhook/admission_handler_test.go:71:10: Error return value of `c.Get` is not checked (errcheck)
c.Get(ctx, client.ObjectKeyFromObject(testPlacement), placement)
^
pkg/webhook/admission_handler_test.go:89:13: Error return value of `c.Create` is not checked (errcheck)
c.Create(ctx, …
```

fix webhook lint issues.

---

manager/pkg/statussyncer/transport2db/syncer/dbsyncer/dbsyncer_suite_test.go
manager/pkg/statussyncer/transport2db/syncer/dbsyncer/policies_db_syncer_test.go
manager/pkg/statussyncer/transport2db/transport/test/kafka.go
test/pkg/testkafka/transportConsumer.go

This PR focuses on the following points of the policy syncer:
- Mock the Kafka consumer client for transport to the database UT
- Verify that expired policies are deleted from the database.
- Verify the delta policy bundle is used only for policy compliance status updates.
- Test the difference of bundle in two scenarios with `aggragationLevel` being `full` and `minimal`.
Ref: https://github.com/stolostron/backlog/issues/25859, https://github.com/stolostron/backlog/issues/26233

Add transport to database unit tests for policies (UT for statussyncer)

---

manager/pkg/nonk8sapi/non_k8s_api_test.go

Error message:
```bash
$ make build-manager-image
...
golangci-lint run ./cmd/... ./pkg/...
pkg/nonk8sapi/non_k8s_api_test.go:33:32: func `(*TestResponseRecorder).closeClient` is unused (unused)
func (r *TestResponseRecorder) closeClient() {
^
pkg/nonk8sapi/non_k8s_api_test.go:863:45: S1025: the argument is already a string, there's no need to use fmt.Sprintf (gosimple)
Expect(w1.Body.String()).Should(MatchJSON(fmt.Sprintf("%s", expectedPolicyStatus1)))
```

Fixed the golangci-lint error

---

test/setup/leafhub_setup.sh

fix e2e setup log redirect errors:
```bash
./test/setup/e2e_setup.sh
[06:33:52]  ✅  KUBECONFIG=/root/workspace/multicluster-global-hub/test/setup/config/kubeconfig ...
[06:35:02]  ✅  1 Prepare top hub cluster hub-of-hubs ...
[06:36:00]  ✅    Enable OLM for microshift ...
[06:36:01]  ✅  2 Prepare leaf hub cluster hub1 ...
[06:36:02]  ✅    Leaf Hub: export KUBECONFIG=/root/workspace/multicluster-global-hub/test/setup/config/kubeconfig ...
/root/workspace/multicluster-global-hub/test/setup/leafhub_setup.sh: line 31: $LEAF_HUB_LOG: ambiguous redirect
[06:36:02]  ✅    Create KinD Cluster hub1
/root/workspace/multicluster-global-hub/test/setup/leafhub_setup.sh: line 33: $LEAF_HUB_LOG: ambiguous redirect
Makefile:69: recipe for target 'e2e-setup-start' failed
make: *** [e2e-setup-start] Error 1 …
```

fix e2e setup log redirect.

---

agent/pkg/status/controller/generic/generic_status_sync_controller.go
agent/pkg/status/controller/generic/generic_status_sync_controller_test.go

revert: https://github.com/stolostron/multicluster-global-hub/pull/172
fix: https://github.com/stolostron/backlog/issues/26311
the finalizer is useful to clean the records in the database before deleting the resources in the regional hub cluster.

Add back the finalizer for resources in agent

---

agent/pkg/status/controller/generic/generic_status_sync_controller_test.go

Error message: 
```bash
$ make uint-tests-agent
...
golangci-lint run ./cmd/... ./pkg/...
pkg/status/controller/generic/generic_status_sync_controller_test.go:34:7: SA1019: fake.NewFakeClientWithScheme is deprecated: Please use NewClientBuilder instead. (staticcheck)
c := fake.NewFakeClientWithScheme(scheme)
...
```

fixed the agent compile issue

---

operator/main.go
operator/main_test.go

Error message:
```bash
$ make unit-tests-operator
...
=== RUN   TestManager
1.6662492562370045e+09  ERROR   Failed to get API Group-Resources       {"error": "Unauthorized"}
sigs.k8s.io/controller-runtime/pkg/cluster.New
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/cluster/cluster.go:160
sigs.k8s.io/controller-runtime/pkg/manager.New
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/manager/manager.go:322
github.com/stolostron/multicluster-global-hub/operator.getManager
/root/workspace/hub-of-hubs/operator/main.go:251
github.com/stolostron/multicluster-global-hub/operator.TestManager
/root/workspace/hub-of-hubs/operator/main_test.go:117
testing.tRunner
/usr/local/go/src/testing/testing.go:1439
main_test.go:119: failed to …
```

Fixed TestManager error in operator

---

test/setup/hoh/hoh_setup.sh

We need to add multiclusterhub crd for the global hub agent. Otherwise it will occur the following error message:
```
$ oc logs -f -l name=multicluster-global-hub-agent -n open-cluster-management-agent-addon
...
{"level":"error","ts":1667288012.9255772,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"MultiClusterHub.operator.open-cluster-management.io","error":"no matches for kind \"MultiClusterHub\" in version \"operator.open-cluster-management.io/v1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:139\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\ …
```

add multiclusterhub crd for e2e test

---

operator/config/samples/storage/deploy_postgres.sh
operator/config/samples/storage/postgres-cluster/postgres-cluster.yaml
operator/config/samples/storage/postgres-operator/bases/crd/bases/postgres-operator.crunchydata.com_postgresclusters.yaml
operator/config/samples/storage/postgres-operator/bases/manager/manager.yaml

Fixed: https://issues.redhat.com/browse/ACM-1950, https://github.com/stolostron/backlog/issues/26694
Reference: 
1. https://github.com/CrunchyData/postgres-operator-examples/issues/151
2. https://github.com/CrunchyData/postgres-operator/pull/3370
ErrorMessage:
```bash
time="2022-11-01T08:07:07Z" level=error msg="if kind is a CRD, it should be installed before calling Start" error="no matches for kind \"CronJob\" in version \"batch/v1beta1\"" file="sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144" func="log.(*DelegatingLogger).Error" kind=CronJob.batch version=5.0.3-0
panic: no matches for kind "CronJob" in version "batch/v1beta1"
goroutine 1 [running]:
main.assertNoError(...)
github.com/crunchydata/postgres-operator/cmd/postgres-operator/main …
```

failed to deploy PostgreSQL with operator on OCP 4.12

---

agent/pkg/status/controller/generic/generic_status_sync_controller.go
agent/pkg/status/controller/generic/generic_status_sync_controller_test.go
pkg/constants/constants.go
pkg/jobs/prune_finalizer.go

Fixed: https://github.com/stolostron/multicluster-global-hub/issues/258, https://github.com/stolostron/backlog/issues/26691
The process is updated to:
1. The addon pre-delete job adds a removing-finalizer label(with ttl=60s) to the resource and remove the finalizer from it
2. Global hub agent detected the removing-finalizer label in the resource and stop adding the finalizer back to it.
3. Then the finalizer is removed from resources on the regional hub.

failed to remove the finalizer from resource when delete the mgh cr

---

operator/config/samples/storage/postgres-operator/bases/manager/manager.yaml
operator/config/samples/storage/postgres-operator/bases/rbac/cluster/role.yaml
operator/config/samples/storage/postgres-operator/bases/rbac/namespace/role.yaml

Fixed: https://issues.redhat.com/browse/ACM-1950, https://github.com/stolostron/backlog/issues/26694
Since the [k8s v1.25 compatible fix](https://github.com/CrunchyData/postgres-operator/pull/3370) has not been released yet, the image `quay.io/myan/postgres-operator:ubi8-k8s.1.25` is used for now.

make the postgres-operator compatible with k8s v1.25

---

agent/pkg/scheme/scheme.go
go.mod
go.sum
manager/pkg/scheme/scheme.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/managed_cluster_set_bindings_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/managed_cluster_sets_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/placements_db_to_transport_syncer.go
manager/pkg/specsyncer/spec2db/controller/managedclusterset_spec_sync.go
manager/pkg/specsyncer/spec2db/controller/managedclusterset_spec_sync_test.go
manager/pkg/specsyncer/spec2db/controller/managedclustersetbinding_spec_sync.go
manager/pkg/specsyncer/spec2db/controller/managedclustersetbinding_spec_sync_test.go
manager/pkg/statussyncer/transport2db/syncer/syncers.go
operator/main.go
operator/pkg/controllers/addon/addon_suite_test.go
operator/pkg/controllers/hubofhubs/controllers_suite_test.go
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller_test.go
pkg/jobs/jobs_suite_test.go
pkg/jobs/prune_finalizer.go
pkg/jobs/prune_finalizer_test.go
pkg/testdata/crds/0000_00_cluster.open-cluster-management.io_managedclustersetbindings.crd.yaml
pkg/testdata/crds/0000_00_cluster.open-cluster-management.io_managedclustersets.crd.yaml
test/pkg/e2e/hoh-prune_test.go

We have many warnings about managedclusterset and managedclustersetbinding api version in global hub components:
```
W0104 10:52:45.471745       1 warnings.go:70] cluster.open-cluster-management.io/v1beta1 ManagedClusterSet is deprecated; use cluster.open-cluster-management.io/v1beta2 ManagedClusterSet
W0104 10:54:16.472666       1 warnings.go:70] cluster.open-cluster-management.io/v1beta1 ManagedClusterSetBinding is deprecated; use cluster.open-cluster-management.io/v1beta2 ManagedClusterSetBinding
...
```

upgrade managedclusterset and managedclustersetbinding api version.

---

agent/cmd/agent/main_test.go
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-deployment.yaml
operator/pkg/controllers/addon/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-deployment.yaml

fix: https://github.com/stolostron/backlog/issues/27083
which is introduced in https://github.com/stolostron/multicluster-global-hub/pull/259/

fix duplicated kafka consumer ID in global hub agent.

---

operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml

See: https://github.com/openshift/oauth-proxy#limiting-access-to-users for `--openshift-sar` usage
End user or service account must have permission list in `--openshift-sar` to access backend service.
Newly created user doesn't have permission to get  or list `namespaces`:
```bash
Error from server (Forbidden): namespaces is forbidden: User "acm-user1" cannot list resource "namespaces" in API group "" at the cluster scope
```
But newly created user has permission to list `projects` in openshift, but can't see any project:
```
No resources found
```

fix oauth-proxy permission issue.

---

test/setup/e2e_dependencies.sh

followup PR for: https://github.com/stolostron/multicluster-global-hub/pull/315
return code for shell function can't be negative number.

fix docker version check.

---

README.md
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
test/setup/e2e_dependencies.sh

When the installed kubectl version is lower than v0.21, the following error may occur when installing postgres
```
error: AccumulateTarget: containers path is not of type []interface{} but map[string]interface {}
```

fixed the issue "AccumulateTarget: containers path is not of type []interface{} but map[string]interface" when installing postgres

---

operator/pkg/controllers/addon/addoninstall_controller.go

should also filter the OCP3 cluster since the addon was only support to be installed on OCP4+ cluster.

filter the ocp3

---

go.mod
go.sum
manager/cmd/manager/main_test.go
manager/pkg/statussyncer/transport2db/syncer/syncers_test.go
pkg/compressor/compressor_test.go
pkg/transport/consumer/bundle_metadata.go
pkg/transport/consumer/committer.go
pkg/transport/consumer/kafka_consumer.go
pkg/transport/consumer/kafka_message_assembler.go
pkg/transport/consumer/message_fragement.go
pkg/transport/consumer/message_fragment_collection.go
pkg/transport/helpers/helpers.go
pkg/transport/helpers/helpers_test.go
pkg/transport/producer/kafka_producer.go
pkg/transport/producer/message_builder.go
pkg/transport/transport_suite_test.go

Ref: https://github.com/confluentinc/confluent-kafka-go/releases/tag/v2.0.2, https://github.com/confluentinc/confluent-kafka-go/issues/805
CI-Ref: https://github.com/openshift/release/pull/35168, https://github.com/openshift/release/blob/3c84e31c12059a9baa4b8e4df6feea0519fdc76e/ci-operator/jobs/stolostron/multicluster-global-hub/stolostron-multicluster-global-hub-main-postsubmits.yaml#L122

upgrade confluent-kafka-go to v2.0.2 to be compatible with linux/aarch64

---

operator/bundle.Dockerfile

Risk message: Scratch images run as root by default. Make sure it is safe here.

fixed the security hotspots from the sunar postsubmit

---

test/README.md

edit image link from "doc/architecture/multicluster-global-hub-e2e-arch.png" to "../doc/architecture/multicluster-global-hub-e2e-arch.png"

fix e2e-arch img link

---

operator/config/samples/transport/kafka-cluster.yaml

Fixed: https://github.com/stolostron/multicluster-global-hub/issues/367
References:
- https://github.com/strimzi/strimzi-kafka-operator/blob/main/packaging/examples/kafka/kafka-persistent.yaml
- https://strimzi.io/blog/2018/06/11/deploying-kafka-on-kubernetes-with-local-storage-using-strimzi/
- https://b-nova.com/en/home/content/heres-how-you-can-setup-kafka-with-strimzi-on-kubernetes-in-only-five-minutes

change the kafka `storage` type from ephemeral to persistent-claim

---

manager/pkg/statussyncer/transport2db/db/postgresql/batch/base_batch_builder.go
manager/pkg/statussyncer/transport2db/db/postgresql/batch/generic_batch_builder.go
manager/pkg/statussyncer/transport2db/db/postgresql/batch/generic_local_batch_builder.go
manager/pkg/statussyncer/transport2db/db/postgresql/batch/managed_clusters_batch_builder.go
manager/pkg/statussyncer/transport2db/db/postgresql/batch/policies_batch_builder.go
operator/pkg/controllers/hubofhubs/database/3.tables.sql

ref: https://issues.redhat.com/browse/ACM-4101
Introduce `local_status.compliance_history` table to store the compliance history information. the table is not related with policy events. the table records can be generated directly based on `local_status.compliance` hourly or daily. We can have a worker in global hub manager to help on.
the table should be used for cluster / policy Compliance Overview.
Any comments? @bjoydeep @dislbenn @yanmxa

Init compliance history table

---

manager/pkg/cronjob/sheduler.go
manager/pkg/cronjob/task/compliance_history.go
manager/pkg/cronjob/task/compliance_history_test.go
operator/pkg/controllers/hubofhubs/database/3.tables.sql

Fixed: https://github.com/stolostron/multicluster-global-hub/issues/407
According to @bjoydeep 's comment to the previous PR(https://github.com/stolostron/multicluster-global-hub/pull/408), this PR is also a supplement to it.
- Use the `MATERIALIZED VIEW` instead of `VIEW` as a snapshot. which makes sure the original table updates will not reflect on the `MATERIALIZED VIEW` automatically.
- Add the `ORDER BY` when using `OFFSET` and `LIMIT` to synchronize data in batches, which ensures consistent and predictable rows for the query result. 
- Also add an index(`id`, `cluster_id`) to the `MATERIALIZED VIEW` to improve the performance of queries with an `ORDER BY` clause.
**synchronized data**:
```bash
» kubectl exec -it $(kubectl get pods -n …
```

trace the log for the cronjob operation and persist it

---

agent/Dockerfile
go.mod
operator/Dockerfile
test/setup/e2e_dependencies.sh

Refers: https://github.com/openshift/release/pull/39026

upgrade go version from go1.18 to go1.19

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/config/multiclusterglobalhub_config_test.go
operator/pkg/constants/constants.go

Refs: https://redhat-internal.slack.com/archives/C03A998ETHR/p1683824331307739?thread_ts=1683283069.326059&cid=C03A998ETHR

repalce the `OPRAND_IMAGE_` prefix with `RELATED_IMAGE_` for downstream image refs

---

manager/pkg/cronjob/task/compliance_history.go

- Fixed the error that failed to trace the cronjob log
```bash
exec failed: ERROR: null value in column "cluster_id" of relation "compliance_history" violates not-null constraint (SQLSTATE 23502)
trace compliance job failed: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)
begin failed: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)
begin failed: conn closed
...
begin failed: conn closed
{"level":"error","ts":1684195800.011777,"logger":"local-compliance-job","msg":"sync to local_status.compliance_history failed","error":"timed out waiting for the condition","stacktrace":"reflect.Value.call\n\t/usr/local/go/src/reflect/value.go:584\nreflect.Va …
```

get database conn from pool rather than a fixed conn for cronjob

---

agent/pkg/controllers/clusterclaim_controllers_test.go
agent/pkg/controllers/controllers_suite_test.go
agent/pkg/controllers/event_exporter.go
agent/pkg/controllers/event_exporter_test.go
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-event-configmap.yaml
operator/pkg/controllers/addon/manifests/templates/hostedagent/multicluster-global-hub-agent-event-configmap.yaml
pkg/testdata/event/kube-event-exporter-good-config.yaml
pkg/transport/config/confluent_config.go
pkg/transport/config/saram_config.go

There are two cases for event exporter connection:
- production environment: we need to enable the TLS.
- the /kafka-certs/client.crt and /kafka-certs/client.key file are valid.
- insecureSkipVerify is false
- e2e test environment: since the e2e pod id(hostname) can't be signed by the client ca, we need to disable the TLS.
- the /kafka-certs/client.crt and /kafka-certs/client.key files exist but are empty. Which might cause the [Kafka sinker initialize](https://github.com/resmoio/kubernetes-event-exporter/blob/f4b7ad969e5c78fd0538d5807ac3363066f8b17c/pkg/sinks/kafka.go#L156) error, and it will be fixed once this [PR](https://github.com/resmoio/kubernetes-event-exporter/pull/80) is merged.
- insecureSkipVerify is true.

update the TLS configration for event exporter

---

operator/pkg/controllers/hubofhubs/database/4.trigger.sql

there is a case that the cluster_id in status.managed_clusters table is empty before insert the data into local_status.compliance table. so create trigger before update to ensure the cluster_id is inserted.

Fix cluster_id is NULL in local_status.compliance table sometimes

---

agent/pkg/spec/controller/syncers/syncers_suite_test.go
doc/simulation/local-policies/README.md
manager/cmd/manager/main.go
manager/pkg/config/manager_config.go
manager/pkg/cronjob/scheduler_suite_test.go
manager/pkg/cronjob/scheduler_test.go
manager/pkg/cronjob/sheduler.go
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/constants/constants.go
operator/pkg/controllers/hubofhubs/globalhub_manager.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml

This PR tries to support customize scheduler interval for moving policy compliance to history, can be 'month', 'week', 'day', 'hour', 'minute' or 'second'.

customize scheduler interval.

---

agent/pkg/controllers/event_exporter.go
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-event-configmap.yaml
operator/pkg/controllers/addon/manifests/templates/hostedagent/multicluster-global-hub-agent-event-configmap.yaml

Disable the logs for event-watch by default, because it is too noisy.

Disable the logs for event by default

---

manager/cmd/manager/main.go
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml

ref: https://issues.redhat.com/browse/ACM-5619
if `SchedulerInterval` is not specified in MGH instance, then don't set `--scheduler-interval` to manager.

fix empty schedule interval.

---

agent/cmd/agent/main.go
agent/cmd/agent/main_test.go
agent/pkg/config/agent_config.go
go.mod
manager/cmd/manager/main.go
manager/cmd/manager/main_test.go
manager/pkg/eventcollector/event_collector_test.go
manager/pkg/specsyncer/spec2db/controller/controllers_suite_test.go
operator/main.go
operator/main_test.go
pkg/utils/utils.go

Before formatting
```bash
{"level":"info","ts":1684912250.9639475,"logger":"db-worker-pool","msg":"started worker","WorkerID":3}
{"level":"info","ts":1684912250.9639482,"logger":"db-worker-pool","msg":"started worker","WorkerID":8}
{"level":"info","ts":1684912250.963958,"logger":"db-worker-pool","msg":"started worker","WorkerID":9}
{"level":"info","ts":1684912250.9638596,"logger":"db-worker-pool","msg":"started worker","WorkerID":16}
{"level":"info","ts":1684912250.963951,"logger":"db-worker-pool","msg":"started worker","WorkerID":15}
```
After formatting
```bash
2023-05-24 08:35:36 UTC INFO    condition-reconciler    updating deployment status      {"name": "multicluster-global-hub-grafana", "message": "Deployment has minimum availability."}
2023-05-24 08:35:41 UTC INFO …
```

format the logger with controller runtime zap

---

operator/pkg/controllers/hubofhubs/globalhub_database.go

avoid executing all SQL statements to reconcile the database when all the tables have been initialized.

skip reconcile database when all the tables have been initialized

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-cluster-group-compliancy-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-policies.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-policy-group-compliancy-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed.yaml

https://issues.redhat.com/browse/ACM-5843
https://issues.redhat.com/browse/ACM-5771

fix policy compliancy overview and some performance issue

---

operator/apis/v1alpha3/multiclusterglobalhub_types.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/bundle/metadata/annotations.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/pkg/constants/constants.go
operator/pkg/controllers/addon/addon_manifests.go
operator/pkg/controllers/hubofhubs/globalhub_config.go
operator/pkg/controllers/hubofhubs/globalhub_manager.go
operator/pkg/controllers/hubofhubs/integration_test.go

Refers: https://issues.redhat.com/browse/ACM-5848
Remove the following fields from API:
- `AggregationLevel`: set the `AggregationLevel` value always with `full`
- `MessageCompressionType`: set the value always with `gzip`, there is an issue if cloudevents haven't used it to compress the event payload. I will enhance the use of this parameter when other things are done
- `EnableLocalPolicies`: set it with always, since this feature is necessary for this delivery.

remove unnecessary parameters from global hub api

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-policies.yaml

Updating the `Policy Status > Unknown` and `Cluster Status > Unknown` table headers to `unknown` instead of `offending`.

[ACM-5821] Updated offending clusters/policies unknown table headers

---

manager/pkg/cronjob/task/compliance_history.go
manager/pkg/cronjob/task/compliance_history_test.go

When the interval is so small that the previous job has not finished running, the next job has already started.
Then a **race condition** will arise: the previous and next jobs will use the same view, which will cause the next job to fail. To avoid this, lock the counter so only one goroutine can access the it and each goroutine will get a different simulatorCounter value.

fixed the view is not exist when simulating the local compliance

---

manager/pkg/eventcollector/processor/policy_processor.go
manager/pkg/eventcollector/processor/policy_processor_test.go
operator/pkg/controllers/hubofhubs/database/3.tables.sql
pkg/database/models/event.go

Currently, we use the unique constraint in the policy events table, like this:
```sql
CONSTRAINT local_policies_unique_constraint UNIQUE (policy_id, cluster_id, count)
```
But there is a scenario: the policy may have more than one event when the `policy_id, cluster_id, and count` are the same, just like the following logs in the global hub manager:
```shell
2023-06-17 01:21:37 UTC INFO    policy-event-processor  regional-hub    {"namespace": "local-placement", "name": "policy-limitrange.17694d9b12ef02cb", "count": "1", "offset": "12"}
2023-06-17 01:21:47 UTC INFO    policy-event-processor  regional-hub    {"namespace": "managed-cluster", "name": "local-placement.policy-limitrange.17694d981e9b98f3", "count": "1", "offset
": "13"}
2023-06-17 01:21:57 UTC INFO    policy-event-processor …
```

fixed the issue of potential policy events loss

---

agent/pkg/event/enhancers/policy_event.go
manager/pkg/statussyncer/syncers/local_spec_policies_syncer.go
manager/pkg/statussyncer/syncers/managed_clusters_syncer.go

1. When we delete the managed cluster from the database, the `deletedAt` column may not be filled if the delete obj is not a pointer.
2. When the cluster is re-imported again, the `deletedAT` should be NULL.
3. Using `Find(&obj)` to get the un-deleted records, cause `db.Table(fmt.Sprintf("%s.%s", schema, tableName))` will get all the records from database.

fixed the managed cluster deletion not work

---

README.md
doc/simulation/local-policies/create_local_policies.sql
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-cluster-group-compliancy-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-policies.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-policy-group-compliancy-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-policies.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/deployment.yaml

Jira issues:
- [ACM-6056](https://issues.redhat.com/browse/ACM-6056) - Remove the name from managedcluster label dropdown
- Removes the `name` label from the drop down list in the `Global Hub - Cluster Group Compliancy Overview` and `Global Hub - Offending Clusters` dashboard.
- [ACM-6057](https://issues.redhat.com/browse/ACM-6057) - The standard,category and control filter should pass to next view when drilling down to offending policy/clusters
- Update the data links in the `Global Hub - Cluster Group Compliancy Overview` and `Global Hub - Policy Group Compliancy Overview` dashboards to pass the `standard`, `category`, and `control` variable values in the URL.
- [ACM-6058](https://issues.redhat.com/browse/ACM-6058) - should able to filter the policy/clusters based on the regional hub …

[ACM-6056][ACM-6057][ACM-6058][ACM-6060] Remove name label from dropdown & split what's changed dashboard for policy/cluster

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-policies.yaml

1. Update the top format and add a 1:maxvalue in the top list
2. sort the event based on time and compliance status.
3. Fix https://issues.redhat.com/browse/ACM-6137
Changed the color to NonCompliant:Red, Unknown:Yellow, Compliant:Green

change top format and sort the compliance events

---

manager/pkg/statussyncer/syncers/control_info_db_syncer_test.go
manager/pkg/statussyncer/syncers/hub_cluster_info_db_syncer_test.go
manager/pkg/statussyncer/syncers/local_spec_syncers_test.go
manager/pkg/statussyncer/syncers/local_status_policies_syncer_test.go
manager/pkg/statussyncer/syncers/managed_clusters_syncer_test.go
manager/pkg/statussyncer/syncers/placement_decisions_db_syncer_test.go
manager/pkg/statussyncer/syncers/placement_rules_db_syncer_test.go
manager/pkg/statussyncer/syncers/placements_db_syncer_test.go
manager/pkg/statussyncer/syncers/policies_db_syncer_test.go
manager/pkg/statussyncer/syncers/subscription_reports_db_syncer_test.go
manager/pkg/statussyncer/syncers/subscription_status_db_syncer_test.go
manager/pkg/statussyncer/syncers/suite_test.go
test/pkg/testpostgres/testdatabase.go

add the following code before testing, and it will init a global hub database and create the tables, indexes and triggers
```golang
err = testpostgres.InitDatabase(testPostgres.URI)
Expect(err).NotTo(HaveOccurred())
```
resolved: https://github.com/stolostron/multicluster-global-hub/issues/466

init the db globally instead of creating the table manually in each test case

---

operator/main.go
operator/pkg/controllers/hubofhubs/globalhub_config.go
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/globalhub_database.go
operator/pkg/controllers/hubofhubs/globalhub_grafana.go

Refers: https://issues.redhat.com/browse/ACM-4732
Propagate the transport/storage secret to the regional hub when they are updated
Previous, the global hub only watch the secret with the [owner lablel](https://github.com/stolostron/multicluster-global-hub/blob/dd3e9127bf199c17f3e5c1311a2beaa51573bc61/operator/main.go#L79). Then it will filter the `transport/storage secret`. 
Because the cache selector of the controller runtime manager does not have an OR operation, we can cache both types of secret at the same time.
In order to avoid caching a large number of secrets, at the same time, the above two types of secrets will not be missed. A compromise is to only cache the secrets under the global hub namespace, and then use the event handler to filter the secrets that need to be reconciled.

watch the transport and storage secret 

---

pkg/database/gorm_conn.go

Ref: https://issues.redhat.com/browse/ACM-6246
When bringing your own Postgres without `rootca` cert, it will throw the following bug:
```bash
2023-07-17 05:47:24 UTC ERROR   setup   failed to initialize GORM instance      {"error": "pq: SSL is not enabled on the server"}
```

fixed the issue with BYO postgres

---

test/setup/common.sh

After the policy operator has been added the `propagator-webhook-validating-configuration` [validating webhook](https://github.com/open-cluster-management-io/governance-policy-propagator/commit/c93f938892c18f3fe84655246ee1a92a963ad62e#diff-3cbaaa330e7ffeab27fc2751c0454be7d83bb82914ea948d6d7c09f5029e0e34). The following issues arise with the `governance-policy-propagator` component setup:
```bash
Warning  FailedMount  61s (x4 over 14m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[kube-api-access-bs2rm cert]: timed out waiting for the condition
Warning  FailedMount  48s (x18 over 21m)   kubelet            MountVolume.SetUp failed for volume "cert" : secret "propagator-webhook-server-cert" not found
```

fixed version of Policy Progator Operator

---

agent/pkg/event/enhancers/policy_event.go
agent/pkg/event/enhancers/policy_event_test.go
agent/pkg/event/event_exporter.go
manager/pkg/cronjob/task/task_suite_test.go
manager/pkg/specsyncer/spec2db/controller/controllers_suite_test.go

Ref: https://issues.redhat.com/browse/ACM-6593
The following cluster policy events will reported after I create an informed policy and then enforce it:
However, we can find that the red boxes in the figure are not helpful for analyzing the reasons for the policy state, so it is recommended to remove them.

forbidd the cluster policy events from managed hub

---

manager/pkg/cronjob/task/data_partition.go
manager/pkg/cronjob/task/local_compliance_history.go
manager/pkg/statussyncer/syncers/compliance_handler_test.go
pkg/database/models/history.go

Ref: https://issues.redhat.com/browse/ACM-7029
- Replace `sql` logging with ORM
- Fixed the log issue that the `end_at` of the retention job isn't set.

Consolidate cronjobs logging

---

operator/config/samples/storage/postgres-cluster.yaml
test/setup/hoh/postgres/postgres-cluster/postgres-cluster.yaml
test/setup/hoh/postgres/postgres-operator/bases/manager/manager.yaml
test/setup/hoh/postgres/postgres_setup.sh

[pgBouncer](https://www.pgbouncer.org/) is a lightweight connection poooler and state manager that provides an efficient gateway to metering connections to PostgreSQL. We connect to postgres via `hoh-primary` service. We do not use hoh-primary so far.

Remove pgBouncer

---

operator/apis/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml

ref: https://issues.redhat.com/browse/ACM-6780
support the cases:
```bash
cat <<EOF | oc apply -f -
apiVersion: operator.open-cluster-management.io/v1alpha4
kind: MulticlusterGlobalHub
metadata:
annotations:
mgh-image-repository: quay.io/stolostron
name: multiclusterglobalhub
namespace: open-cluster-management
EOF
cat <<EOF | oc apply -f -
apiVersion: operator.open-cluster-management.io/v1alpha4
kind: MulticlusterGlobalHub
metadata:
annotations:
mgh-image-repository: quay.io/stolostron
name: multiclusterglobalhub
namespace: open-cluster-management
spec:
dataLayer:
postgres: 
retention: 18m
EOF
cat <<EOF | oc apply -f -
apiVersion: operator.open-cluster-management.io/v1alpha4
kind: MulticlusterGlobalHub
metadata:
annotations:
mgh-image-repository: quay.io/stolostron
name: …
```

generate the default value/struct for the global hub operand

---

operator/pkg/controllers/hubofhubs/globalhub_controller.go

There are no kafka and postgres apis are available at the beginning. Need to find another way to handle the deletion case.
anyway, disable them temporarily to let operator go forward.

Disable watching kafka and postgres temporarily

---

manager/pkg/statussyncer/syncers/local_spec_policies_syncer.go
manager/pkg/statussyncer/syncers/managed_clusters_syncer.go

Manager Log:
```bash
2023/09/08 08:17:37 /workspace/manager/pkg/statussyncer/syncers/local_spec_policies_syncer.go:110 pq: duplicate key value violates unique constraint "policies_pkey"
[2.836ms] [rows:0] INSERT INTO "local_spec"."policies" ("leaf_hub_name","payload") VALUES ('regional-28','{"kind":"Policy","apiVersion":"policy.open-cluster-management.io/v1","metadata":{"name":"backup-restore-enabled","namespace":"open-cluster-management-backup","uid":"6f3be17e-6882-4989-8dc2-c7b7889925dc","resourceVersion":"261875","creationTimestamp":"2023-09-05T07:08:37Z","labels":{"app":"cluster-backup-chart","app.kubernetes.io/instance":"cluster-backup-chart","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"cluster-backup-chart","chart":"cluster-bac …
```

Fixed the policy bug when managed hub rejoin with a different name

---

operator/config/samples/storage/postgres-cluster.yaml
operator/pkg/postgres/postgres.go
test/setup/hoh/postgres/postgres-cluster/postgres-cluster.yaml

If there is some issue happening with the transaction. The logs in this file will continue to accumulate until all disk space is consumed. Like:
```
sh-4.4$ pwd
/pgdata
sh-4.4$ du -sh ./*
16K	./lost+found
7.1G	./pg14
30G	./pg14_wal
8.0K	./pgbackrest
```
ref: https://github.com/CrunchyData/postgres-operator/issues/2115, https://github.com/CrunchyData/postgres-operator/issues/2813,  https://thebuild.com/blog/2023/03/23/the-importance-of-max_wal_size/

Limit uncontrolled growth of the postgre `pg_wal` dir

---

manager/cmd/manager/main_test.go
manager/pkg/statussyncer/syncers_test.go
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/integration_test.go

ref: https://issues.redhat.com/browse/ACM-7570
`r.MiddlewareConfig.KafkaConnection` can be set to `nil` in the global hub operator reconciler, while the addon installer reconciler is using this value. so the nil pointer error occurs sometimes.

fix nil pointer error

---

agent/pkg/status/bundle/hubcluster/hub_cluster_bundle.go
agent/pkg/status/controller/controller_integration_test.go
agent/pkg/status/controller/hubcluster/clusters_status_sync.go
operator/pkg/controllers/hubofhubs/database/2.tables.sql
pkg/bundle/status/hub_cluster_info_bundle.go
pkg/constants/constants.go
pkg/database/models/status.go

```
select * from status.leaf_hubs;
leaf_hub_name |                                                                                                                                        payload                                                                                                                                        |                                             console_url                                             |                                                       grafana_url                                                       |         created_at         |         updated_at         | deleted_at
---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

Add observability Grafana url into status.leaf_hubs

---

operator/pkg/postgres/postgres.go

There is insufficient storage(`20 GB`) for `5` hubs each with `300` managed clusters and `50` root policies. When rotating the policies' status, The storage was up to about `22 GB` and stabilized at around `20 GB` after several minutes. 
Based on the policies events might be remained for a long time(let's say 18 months). I recommend set it up to `25 GB`.

Extend the postgres disk for the high scale global hub

---

manager/pkg/cronjob/scheduler.go
manager/pkg/cronjob/scheduler_test.go
manager/pkg/cronjob/task/local_compliance_history.go

This PR aims to fix the bug: It won't trigger the cronjob even though added the its annotation to the global hub operand.

Wait until the scheduler is initialized before starting the cronjob

---

operator/config/manager/manager.yaml
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml

Ref: https://issues.redhat.com/browse/ACM-6381
Note: https://home.robusta.dev/blog/stop-using-cpu-limits

Set the resources cpu and memory for global hub components

---

operator/pkg/controllers/hubofhubs/database/5.privileges.sql
operator/pkg/controllers/hubofhubs/globalhub_database.go
operator/pkg/controllers/hubofhubs/manifests/postgres/init-configmap.yaml

move the create role and alter role into postgres start script to be executed when postgres pod starts. in the past, it needed the admin user have create role permission which may not be required.

Update global-hub-user password

---

operator/pkg/constants/constants.go
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/globalhub_database.go
operator/pkg/controllers/hubofhubs/globalhub_kafka.go
operator/pkg/controllers/hubofhubs/globalhub_manager.go
operator/pkg/controllers/hubofhubs/globalhub_postgres.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/postgres-credential-secret.yaml
operator/pkg/controllers/hubofhubs/manifests/postgres/secret.yaml

Resolved: https://github.com/stolostron/multicluster-global-hub/issues/687
Ref: https://issues.redhat.com/browse/ACM-8230
https://github.com/stolostron/multicluster-global-hub/issues/691: If we want to dynamically load the values of the Postgres credential into the pod, we need a separate controller to load and update the connection of the database, the same as Kafka.

Implicitly pass the postgres url to manager

---

operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/globalhub_postgres.go

ref: https://issues.redhat.com/browse/ACM-7917
We need to initilize the config (set images / imagepullsecret / etc) before the real reconcilers start

Move reconciling config to top

---

operator/main_test.go
operator/pkg/condition/condition.go
operator/pkg/controllers/addon/addon_controller.go
operator/pkg/controllers/addon/addon_suite_test.go
operator/pkg/controllers/addon/addoninstall_reconciler.go
operator/pkg/controllers/addon/addoninstall_reconciler_test.go
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/controllers/hubofhubs/suite_test.go
operator/pkg/utils/utils.go
operator/pkg/utils/utils_test.go

https://issues.redhat.com/browse/ACM-7913
1. When Kafka or Postgre is starting, we should not return errors in reconcile. We just need to wait it started
2. We should not return `mgh is not exist` errors before `mgh` is created. just need to wait it created.

fix reconcile too long and some error in log

---

cicd-scripts/run-prow-e2e-test.sh
operator/main.go
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/controllers/addon/addon_installer.go
operator/pkg/controllers/addon/addon_installer_test.go
operator/pkg/controllers/addon/addon_integration_test.go
operator/pkg/controllers/addon/addon_manifests.go
operator/pkg/controllers/addon/addon_suite_test.go
operator/pkg/controllers/hubofhubs/globalhub_config.go
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/globalhub_kafka.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/kafka/kafka.go
operator/pkg/utils/utils.go
pkg/constants/constants.go
test/setup/common.sh
test/setup/e2e_setup.sh
test/setup/hoh/kafka/kafka-cluster/kafka-cluster.yaml
test/setup/hoh/kafka/kafka-cluster/kafka-topics.yaml
test/setup/hoh/kafka/kafka-cluster/kafka-user.yaml
test/setup/hoh/kafka/kafka-operator/kustomization.yaml
test/setup/hoh/kafka/kafka-operator/rbac/020-RoleBinding-strimzi-cluster-operator.yaml
test/setup/hoh/kafka/kafka-operator/rbac/022-RoleBinding-strimzi-cluster-operator.yaml
test/setup/hoh/kafka/kafka-operator/rbac/023-RoleBinding-strimzi-cluster-operator.yaml
test/setup/hoh/kafka/kafka-operator/rbac/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml
test/setup/hoh/kafka/kafka_setup.sh

Resolved: https://issues.redhat.com/browse/ACM-6179
Reference: https://github.com/strimzi/strimzi-kafka-operator/tree/main/documentation/modules/security
We will disable this feature for the BYO case.  Since we don't know which kind of Kafka cluster the user provisioned, whether cloud we create the connection credential by the `KafkaUser` API under the global hub namespace.
So If the customer provides the transport secret. We will use that as the only source of truth for connecting Kafka, whether from a global hub cluster or managed hub clusters.
Also, we aren't considering renewing the certificates for now.

Create Kafka certs for each managed hub

---

pkg/transport/consumer/generic_consumer.go

Signed-off-by: myan <myan@redhat.com> 
To make events more efficient, the cloudevents use the multi-goroutine to fetch the messages. That will break the order of the messages on the partition.
Since Kafka already natively utilizes consumer groups to enhance consumption efficiency, there is no need to use multiple goroutines to boost consumption speed.

keep the order of the events on the partitions

---

agent/cmd/agent/main.go
agent/pkg/controllers/crd_controller.go
agent/pkg/event/event_exporter.go
go.mod
go.sum
manager/pkg/webhook/admission_suite_test.go
operator/pkg/controllers/hubofhubs/globalhub_manager.go
operator/pkg/controllers/hubofhubs/globalhub_middleware.go
operator/pkg/transporter/byo_transporter.go
operator/pkg/transporter/strimzi_transporter.go
operator/pkg/transporter/strimzi_transporter_test.go
pkg/database/gorm_conn.go
pkg/transport/config/confluent_config.go
pkg/transport/config/saram_config.go
pkg/transport/consumer/generic_consumer.go
pkg/transport/kafka_confluent/message.go
pkg/transport/kafka_confluent/option.go
pkg/transport/kafka_confluent/protocol.go
pkg/transport/kafka_confluent/write_producer_message.go
pkg/transport/producer/generic_producer.go
pkg/utils/utils.go
samples/cloudevent/confluent-receiver/main.go
samples/cloudevent/confluent-sender/main.go
samples/config/confluent_config.go
samples/kafka/confluent_consumer/main.go

Ref: https://issues.redhat.com/browse/ACM-8793
If we split the spec, then the manager must get which cluster it needs to send the message. That means it has to hold the cluster information
Note:
- e2e certificate error reference: https://github.com/confluentinc/librdkafka/issues/4349
- resolved by setting: "ssl.endpoint.identification.algorithm": "none",
```bash
%3|1703161332.046|FAIL|multicluster-global-hub-manager#consumer-2| [thrd:ssl://172.20.0.2:30095/bootstrap]: ssl://172.20.0.2:30095/bootstrap: SSL handshake failed: error:0A000086:SSL routines::certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (install ca-certificates package) (after 7ms …
```

Split topics for each regional hub

---

operator/pkg/transporter/strimzi_transporter.go
test/pkg/e2e/suite_test.go
test/setup/hoh/kafka/kafka-cluster/kafka-cluster.yaml
test/setup/hoh/kafka/kafka_setup.sh

Add the `nodeport` IP to the broker/server certificate SAN
ref: https://strimzi.io/blog/2019/04/23/accessing-kafka-part-2/

Enable TLS for e2e

---

agent/pkg/spec/controller/syncers/managed_cluster_label_syncer.go
operator/main.go
operator/pkg/controllers/addon/addon_installer.go
operator/pkg/controllers/backup/backup.go
operator/pkg/controllers/backup/backup_reconcile.go
operator/pkg/controllers/backup/backup_start.go
operator/pkg/controllers/backup/integration_test.go
operator/pkg/controllers/backup/kafka.go
operator/pkg/controllers/backup/kafkatopic.go
operator/pkg/controllers/backup/kafkauser.go
operator/pkg/controllers/hubofhubs/globalhub_middleware.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/transporter/byo_transporter.go
operator/pkg/transporter/strimzi_transporter.go
operator/pkg/transporter/strimzi_transporter_test.go
operator/pkg/utils/utils.go
operator/pkg/utils/utils_test.go
pkg/transport/consumer/sarama_consumer.go
pkg/transport/transport.go
samples/config/confluent_config.go
test/setup/hoh/kafka/kafka-cluster/kafka-cluster.yaml

Ref: https://issues.redhat.com/browse/ACM-8508
- Global Hub Manager Authorization
```yaml
authorization:
acls:
- host: '*'
operations:
- Describe
- Read
resource:
name: event
patternType: literal
type: topic
- host: '*'
operations:
- Read
resource:
name: '*'
patternType: literal
type: group
- host: '*'
operations:
- Describe
- Read
resource:
name: status
patternType: prefix
type: topic
- host: '*'
operations:
- Write
resource:
name: spec
patternType: literal
type: topic
type: simple
```
- Global Hub Agent Authorization for Each Managed Hub
```yaml
authorization:
acls:
- host: '*'
operations:
- Describe
- Read
resource:
name: spec
patternType: literal
type: topic
- host: '*'
operations:
- Read
resource:
name: '*'
patternType: literal
type: group
- …
```

Add authorization for managed hub topics

---

agent/pkg/controllers/crd_controller.go
agent/pkg/spec/controller/controller.go
agent/pkg/spec/controller/syncers/resend_syncer.go
agent/pkg/spec/controller/syncers/resend_syncer_test.go
agent/pkg/spec/controller/syncers/syncers_suite_test.go
agent/pkg/status/controller/cache/cache.go
agent/pkg/status/controller/hubcluster/clusters_status_syncer.go
manager/cmd/manager/main.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/syncers_intergration_test.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/syncres_suite_test.go
manager/pkg/specsyncer/db2transport/syncer/syncers.go
manager/pkg/specsyncer/syncers.go
operator/pkg/controllers/hubofhubs/integration_test.go
pkg/bundle/cluster/hub_cluster_info_bundle.go
pkg/constants/constants.go

https://issues.redhat.com/browse/ACM-9179
In upgrade case, there is a middle status that agent upgrade to new version, but manager do not. 
When agent start, agent will send the managed hubinfo(we add clusterid in this release) to manager, but manager can not handle it now and will discard it. 
After manager upgrade to new version, agent will not send the hubinfo any more, so the hubinfo in database could not be updated. So we need to ask agent to resend hubinfo after manager started.

resend hub info bundle when manager start

---

operator/pkg/controllers/addon/addon_installer.go
operator/pkg/controllers/hubofhubs/globalhub_controller.go

The generation field is always 0 for no spec resources.
So we should update the watch logic for these kind of resources.

fix watch no spec resources

---

test/setup/e2e_setup.sh

For the e2e test case, If we don't create the `clusterclaim` instance on the managed hub, then the `hubClusterClaimController` will never be triggered.
The `hub.open-cluster-management.io` claim will be absent from the managed hub cluster 
Resolved: https://github.com/stolostron/multicluster-global-hub/issues/765

Add cluster claim for E2E test

---

operator/config/default/kustomization.yaml
test/setup/hoh/postgres/postgres-operator/bases/kustomization.yaml
test/setup/hoh/postgres/postgres-operator/kustomization.yaml

When deploying the operator with `make deploy-operator`, It may echo the following warning message:
```bash
.../operator/bin/kustomize build config/default | kubectl apply -f -
namespace/multicluster-global-hub unchanged
```

Remove the deprecated bases for kustomize

---

operator/pkg/controllers/backup/backup_start.go
operator/pkg/controllers/backup/integration_test.go
operator/pkg/controllers/backup/kafka.go
operator/pkg/controllers/backup/kafka_test.go
operator/pkg/controllers/backup/suite_test.go

https://issues.redhat.com/browse/ACM-9293
The kafka always sync the pvc label based on kafka cr pvc template, so we also need to update the template in kafka cr.

fix backup log always show

---

agent/cmd/agent/main.go
agent/pkg/controllers/cert_controller.go
agent/pkg/controllers/cert_controller_test.go
agent/pkg/controllers/controllers_suite_test.go
agent/pkg/controllers/crd_controller.go
agent/pkg/controllers/hub_clusterclaim_controller.go
agent/pkg/controllers/version_clusterclaim_controller.go
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
operator/pkg/controllers/addon/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-role.yaml
operator/pkg/controllers/backup/suite_test.go
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/globalhub_grafana.go
operator/pkg/controllers/hubofhubs/globalhub_grafana_test.go
operator/pkg/controllers/hubofhubs/globalhub_manager.go
operator/pkg/controllers/hubofhubs/globalhub_middleware.go
operator/pkg/controllers/hubofhubs/globalhub_postgres.go
pkg/constants/constants.go
pkg/utils/utils.go

https://issues.redhat.com/browse/ACM-7489
We need to rebuild the database and transport connection if transport/database connection info changed.
1. The the database/transport secret changed(url/ca/cert...)
2. The database/transport ca is expired.
And for kafka, it's difficult to rebuild the consumer connection when CA changed. I tried openshift/kafka, they all restart the related pods when rotate the CA, So I also restart the manager/agent pod when CA changed.

handle ca updated

---

manager/pkg/statussyncer/hubmanagement/hub_management.go
manager/pkg/statussyncer/hubmanagement/hub_management_test.go
pkg/bundle/grc/compliance_bundle.go

When the managed hub status switches to inactive:
- soft delete the managed cluster(`status.managed_clusters`)
- soft delete the spec policy(`local_spec.polcies`)
- soft delete the hub info(`status.leaf_hubs`)
- delete the compliance(`local_status.compliance`)
- mark the status of the hub as inactive(`status.leaf_hub_heartbeats`)
Otherwise, when the status switches to active:
- resync the managed cluster
- resync the spec policy
- resync the hub info
- resync the compliance
- mark the hub status as active

Trigger `cleanup/resync` when status is updated

---

manager/cmd/manager/main.go
manager/pkg/statussyncer/hubmanagement/hub_management.go
manager/pkg/statussyncer/syncers.go
manager/pkg/statussyncer/syncers/suite_test.go

The manager will throw a nil pointer error of the transport producer when it is not set in the resync function.

Fixed the producer is not set for hub management

---

agent/pkg/status/controller/event/local_replicated_policy_emitter.go
agent/pkg/status/controller/event/local_root_policy_emitter.go
manager/pkg/statussyncer/handler/local_policies/root_policy_event_handler.go

Reference: https://issues.redhat.com/browse/ACM-10145
Error message:
```bash
2024/02/26 04:07:35 /remote-source/multicluster-global-hub/app/manager/pkg/statussyncer/handler/local_policies/root_policy_event_handler.go:84 pq: invalid input syntax for type uuid: ""
[7.320ms] [rows:0] INSERT INTO "event"."local_root_policies" ("event_name","policy_id","message","leaf_hub_name","reason","count","source","compliance","created_at") VALUES ('acmqe-policy-38732.17b74d718fde269b','aed9bbb1-f47a-4a1b-ba78-62d3db3ccb93','Policy acmqe-policy-38732/acmqe-policy-38732 was propagated to cluster clc-iks-609-9bxmp-iks','acmqe-hoh-auto-hskp4x','PolicyPropagation',1,NULL,'non_compliant','2024-02-26 03:55:33'),('acmqe-policy-43020.17b74de84e9ad09c','b8e3a1ca-79f8-47f6-89f8 …
```

Fixed the event persist error

---

manager/cmd/manager/main.go
operator/pkg/controllers/hubofhubs/globalhub_manager.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
operator/pkg/transporter/byo_transporter.go
operator/pkg/transporter/strimzi_transporter.go
pkg/bundle/metadata/bundle_status.go
pkg/bundle/metadata/status/threshold_bundle_status.go
pkg/conflator/conflation_committer.go
pkg/transport/consumer/generic_consumer.go
pkg/transport/consumer/generic_consumer_test.go
pkg/transport/type.go
test/pkg/kafka/strimzi_kafka.go

This PR is derived from the Kafka backup solution. https://issues.redhat.com/browse/ACM-9703
With the offset cached in the database, we can make sure the unprocessed message won't be lost even if the manager crashes.
But if the original transport is deleted and a new Kafka cluster is created. Then we should also deprecate the cached offset. and the consumer should start receiving messages from the start of the transport.

Consume message from the start when the transport(kafkacluster) is changed

---

agent/Dockerfile
go.mod
go.sum
manager/Dockerfile
operator/Dockerfile
test/setup/e2e_dependencies.sh

Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including critical security problems, in supported releases as needed by issuing minor revisions.
1.22 was just released on 2/6/24, so 1.20 is already end-of-life

Update to use golang 1.21

---

manager/pkg/cronjob/task/local_compliance_history.go
operator/pkg/controllers/hubofhubs/database/2.tables.sql
operator/pkg/controllers/hubofhubs/database/3.functions.sql
operator/pkg/controllers/hubofhubs/globalhub_database.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/controllers/hubofhubs/upgrade/1.upgrade.sql

Error message:
```bash
2024/03/05 00:29:55 /remote-source/multicluster-global-hub/app/manager/pkg/cronjob/task/local_compliance_history.go:282 pq: ON CONFLICT DO UPDATE command cannot affect row a second time
[3.439ms] [rows:0]
INSERT INTO history.local_compliance (policy_id, cluster_id, leaf_hub_name, compliance_date, compliance,
compliance_changed_frequency)
WITH compliance_aggregate AS (
SELECT cluster_id, policy_id, leaf_hub_name,
CASE
WHEN bool_or(compliance = 'non_compliant') THEN 'non_compliant'
WHEN bool_or(compliance = 'unknown') THEN 'unknown'
ELSE 'compliant'
END::local_status.compliance_type AS aggregated_compliance
FROM event.local_policies
WHERE created_at BETWEEN CURRENT_DATE - INTERVAL '1 days' AND CURRENT_DATE - INTERVAL '0 day'
GROUP …
```

Fix the bug that local compliance history data conflicts

---

agent/pkg/status/controller/placement/placement_rule_syncer.go

Reference: https://issues.redhat.com/browse/ACM-10755
We will enable the local `placementrule` unitl it's necessary

Disable the local placement rule

---

pkg/transport/config/confluent_config.go
pkg/transport/consumer/generic_consumer.go
pkg/transport/kafka_confluent/option.go
pkg/transport/kafka_confluent/protocol.go

After a few days with 5 hubs, the manager's memory consumption from 80 MB to 180 MB. So there must be a memory leak issue in the current code.
Fixes https://github.com/stolostron/multicluster-global-hub/issues/848, https://issues.redhat.com/browse/ACM-10813
This bug also exists in Global Hub 1.1.0: https://issues.redhat.com/browse/ACM-10814
Reference: https://github.com/confluentinc/confluent-kafka-go/issues/1043, https://github.com/confluentinc/confluent-kafka-go/issues/578

:bug: Fix the bug that the memory leak of the producer

---

agent/pkg/status/controller/apps/subscription_report_sync.go
agent/pkg/status/controller/apps/subscription_status_sync.go
agent/pkg/status/controller/generic/generic_object_emitter.go
agent/pkg/status/controller/generic/generic_object_handler.go
agent/pkg/status/controller/managedclusters/managed_cluster_syncer.go
agent/pkg/status/controller/placement/placement_decision_syncer.go
agent/pkg/status/controller/placement/placement_rule_syncer.go
agent/pkg/status/controller/placement/placement_syncer.go
agent/pkg/status/controller/policies/policy_syncer.go

Reference: https://issues.redhat.com/browse/ACM-10797
For the policy spec event, we only need to report the object when the generation(spec) is changed. And ignore the status updates.

Sync policy object only policy spec is changed

---

operator/main.go

The operator start with the error:
```bash
2024-04-02T02:27:40.868Z	ERROR	setup	unable to start manager	{"error": "failed to determine if *v1beta2.Kafka is namespaced: failed to get restmapping: no matches for kind \"Kafka\" in group \"kafka.strimzi.io\""}
main.doMain
/workspace/operator/main.go:163
main.main
/workspace/operator/main.go:132
runtime.main
/usr/local/go/src/runtime/proc.go:267
```
Reference: https://github.com/kubernetes-sigs/controller-runtime/issues/2456, from here: https://github.com/kubernetes-sigs/controller-runtime/commit/3e35cab1ea29145d8699259b079633a2b8cfc116
Fixes #

:bug: The operator failed to start without kafka resources

---

agent/pkg/status/controller/policies/complete_compliance_emitter.go
agent/pkg/status/controller/policies/compliance_emitter.go
doc/simulation/local-policies/create_local_policies.sql
manager/pkg/cronjob/task/local_compliance_history.go
manager/pkg/statussyncer/syncers/local_policy_complete_handler.go
manager/pkg/statussyncer/syncers/local_policy_compliance_handler.go
manager/pkg/statussyncer/syncers/local_policy_compliance_handler_test.go
manager/pkg/statussyncer/syncers/policy_complete_handler.go
manager/pkg/statussyncer/syncers/policy_compliance_handler.go
manager/pkg/statussyncer/syncers/policy_compliance_handler_test.go
manager/pkg/statussyncer/syncers/policy_delta_compliance_handler.go
operator/pkg/controllers/hubofhubs/database/1.schemas.sql
operator/pkg/controllers/hubofhubs/database/3.functions.sql
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-adhoc-investigation.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-cluster-group-compliancy-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-policies.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-policy-group-compliancy-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-policies.yaml
operator/pkg/controllers/hubofhubs/upgrade/1.upgrade.sql
pkg/bundle/grc/complete_compliance_bundle.go
pkg/bundle/grc/compliance_bundle.go
pkg/database/common/util.go
pkg/database/constants.go

This pr handle pending policies in back-end and dashboards
https://issues.redhat.com/browse/ACM-10818
https://issues.redhat.com/browse/ACM-10817

:sparkles: handle pending policies

---

operator/pkg/controllers/hubofhubs/globalhub_kafka_controller.go
operator/pkg/controllers/hubofhubs/globalhub_middleware.go
operator/pkg/controllers/hubofhubs/integration_test.go

Globalhub can not install successfully when enable metric in mgh.
Fixes #
When enable metric in mgh, kafka cluster depend on a kafka-metric configmap, but it's created after kafka operator and it depend on kafka cluster ready in current code logic, so we should create the configmap first.

:bug: fix kafka cluster error when enable metric by default

---

agent/pkg/status/controller/generic/generic_event_controller.go
agent/pkg/status/controller/policies/local_policies_test.go

Fix the bug that the policy payload isn't synced to database when update its spec
Fixes # https://issues.redhat.com/browse/ACM-10943

:bug: Enable spec syncer for agent

---

operator/pkg/constants/constants.go

Avoid the pods being evicted by the resource limitation. 
Reference: [Scenario 3](https://github.com/stolostron/multicluster-global-hub/blob/main/doc/simulation/scenario/Scenario3%3A%203000_clusters_500_policies.md)

:seedling:Extend the manager/agent memory limitation

---

operator/pkg/controllers/hubofhubs/globalhub_middleware.go
operator/pkg/controllers/hubofhubs/globalhub_upgrade_test.go
operator/pkg/controllers/hubofhubs/integration_test.go

Most likely the unit test reports the following error:
```
2024-04-03T09:49:58Z    INFO    strimzi-transporter kafka cluster is ready2024-04-03T09:49:59Z    INFO    strimzi-transporter reconcile global hub kafka transport...2024-04-03T09:49:59Z    INFO    strimzi-transporter waiting the kafka cluster instance to be ready...2024-04-03T09:49:59Z    INFO    strimzi-transporter kafka cluster is ready[FAILED] in [It] - /go/src/github.com/stolostron/multicluster-global-hub/operator/pkg/controllers/hubofhubs/integration_test.go:958 @ 04/03/24 09:49:59.274
<< Timeline
[FAILED] Timed out after 30.001s.
Unexpected error:    <*errors.errorString | 0xc003033900>:     mghReconciler.TransportConn.PgConnection should not be nil    
{        
s: "mghReconciler.TransportConn.PgConnection should not be …
```

reset KafkaInit as false

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/pkg/controllers/hubofhubs/globalhub_controller.go

The clusterrole cluster-monitoring-view add some rules for ocp 4.15, we need to add it in globalhub controller.
apiGroups:
- monitoring.coreos.com
resourceNames:
- k8s
resources:
- prometheuses/api
verbs:
- get
- create
- update
https://issues.redhat.com/browse/ACM-11266
Fixes #

:bug: add monitor permissions in globalhub

---

operator/pkg/transporter/strimzi_transporter.go

When detaching a managed hub cluster or disable the agent, should delete the shared topic like `event` or `spec`.
Fixes # https://issues.redhat.com/browse/ACM-11284

:bug: Fix the topic isn't ready for the detach case

---

operator/pkg/controllers/hubofhubs/manifests/kafka/podmonitor.yaml

The kafkauser and kafkatopic metric collected in entyty-operator, and we do not monitor it previously.

:bug: add entity-operator monitor

---

agent/pkg/spec/controller/syncers/dispatcher.go

Upgrade from `release-2.10` to `release-2.11`
Error message
```bash
nil syncer or evt       {"syncer": null, "event": "Context Attributes,\n  specversion: 1.0\n  type: SpecBundle\n  source: broadcast\n  id: Resync\n  time: 2024-05-06T08:34:03.018187888Z\n  datacontenttype: application/json\nExtensions,\n  extoffset: 0\n  extsize: 18\n  kafkamessagekey: Resync\n  kafkaoffset: 1\n  kafkapartition: 0\n  kafkatopic: spec\nData (binary),\n  [\n    \"HubClusterInfo\"\n  ]\n"}
```
Fixes # https://issues.redhat.com/browse/ACM-11490

:bug: Fix the event format incompatible when upgrading

---

agent/pkg/status/controller/controller.go
agent/pkg/status/controller/event/event_integration_test.go
agent/pkg/status/controller/event/event_suite_test.go
agent/pkg/status/controller/event/local_replicated_policy_emitter.go
agent/pkg/status/controller/event/local_replicated_policy_emitter_test.go
agent/pkg/status/controller/event/local_root_policy_emitter.go
agent/pkg/status/controller/event/local_root_policy_emitter_test.go
agent/pkg/status/controller/filter/time_filter.go
agent/pkg/status/controller/filter/time_filter_test.go
agent/pkg/status/controller/generic/generic_event_syncer.go
agent/pkg/status/controller/generic/generic_object_syncer.go
agent/pkg/status/controller/policies/status_event_emitter.go

Add the configMap to save the agent event state, so as to deduplicate the event in the message queue(event topics)
Fixes #https://issues.redhat.com/browse/ACM-11243

:seedling: Persistent the agent event state to the configmap

---

operator/pkg/config/cache_config.go

The postgres pvc do not have owner ref label, so we need to use namespace to wath it.
Fixes #

:bug: fix-backup

---

operator/pkg/controllers/hubofhubs/manifests/postgres/secret.yaml

postgres pod can not start in upgrade case:
```
Normal   Started         <invalid>                      kubelet            Started container multicluster-global-hub-postgres
Normal   Pulled          <invalid> (x8 over <invalid>)  kubelet            Container image "quay.io/prometheuscommunity/postgres-exporter:v0.15.0" already present on machine
Warning  Failed          <invalid> (x8 over <invalid>)  kubelet            Error: couldn't find key database-uri in Secret multicluster-global-hub/multicluster-global-hub-postgres
```
https://issues.redhat.com/browse/ACM-11537
Fixes #

:bug: fix postgres pod can not start in upgrade case

---

pkg/transport/producer/generic_producer.go

After this https://github.com/cloudevents/sdk-go/pull/1031 patch to the sdk, we must add the producer event handler, otherwise, it may cause a memory leak for the event channel.
Fixes #

Add default producer event handler for kafka protocol

---

agent/pkg/status/controller/event/managedcluster_emitter.go
agent/pkg/status/controller/event/managedcluster_emitter_test.go
manager/pkg/statussyncer/syncers/managedcluster_event_handler_test.go
operator/pkg/controllers/hubofhubs/database/2.tables.sql
operator/pkg/controllers/hubofhubs/database/3.functions.sql
operator/pkg/controllers/hubofhubs/database/4.trigger.sql
pkg/database/models/event.go
pkg/utils/object.go

Note:
1. add cluster_name in the cluster event table
2. patch the cluster_id in the event table when managed_clusters is created/updated
Fixes #

:seedling: Add `cluster_name` and `cluster_id` for the managed cluster events

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-managedclusters.yaml

@hchenxa give feedback. Sometimes the openshiftversion label is null. we should hanlde it.
Fixes #

:bug: fix cluster dashboard when there is no openshiftversion

---

test/script/util.sh

In e2e, if the kind cluster create error, clusteradm command will always waiting , and no timeout. we should set timeout to that.
Fixes #

set timeout for clusteradmin

---

agent/pkg/status/controller/event/event_syncer.go
test/integration/agent/status/localpolicy_event_test.go

The replicated policy events are duplicated and do not consist of the ACM dashboard.
Fixes #

disable the replicated policy event

---

agent/pkg/status/controller/controller.go
agent/pkg/status/controller/filter/time_filter.go
agent/pkg/status/controller/filter/time_filter_test.go
test/Makefile
test/script/e2e_prow.sh

The previous cache key is based on the `eventType`. But if we support renaming the topic, we need the agent to send the event to the new topic again after the topic is changed. Otherwise, it might lose data when renaming the topics
Reference: https://github.com/stolostron/multicluster-global-hub/pull/1032

:sparkles: Add the cache filter with topic prefix

---

operator/pkg/controllers/addon/addon_installer.go
operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go

1. Consumer Impact: The consumer typically detects the deletion during its polling process. The default polling interval (max.poll.interval.ms) is 5 minutes, meaning the consumer may not notice the deletion until the next poll.
2. Metadata Refresh: Kafka clients periodically refresh their metadata, which includes topic information. The frequency of this refresh (`metadata.max.age.ms`) can also affect how quickly the consumer becomes aware of the topic deletion. The default value is 5 minutes.
3. Rebalancing Trigger: When the Kafka consumer attempts to fetch data from a deleted topic, it will encounter an error like UnknownTopicOrPartitionException. This error can trigger a rebalance in the consumer group. The rebalance process redistributes the available partitions among the remaining …

:bug: Disable the the topic deletion when removing the global hub agent

---

operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go

```yaml
- apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
creationTimestamp: "2024-08-26T01:54:44Z"
finalizers:
- strimzi.io/topic-operator
generation: 2
labels:
global-hub.open-cluster-management.io/managed-by: global-hub-operator
strimzi.io/cluster: kafka
name: gh-event.global-hub
namespace: multicluster-global-hub
ownerReferences:
- apiVersion: operator.open-cluster-management.io/v1alpha4
blockOwnerDeletion: true
controller: true
kind: MulticlusterGlobalHub
name: multiclusterglobalhub
uid: b5aa1fdc-8699-4078-8f5b-6f104f67db0c
resourceVersion: "6156"
uid: 6ab99671-3af5-485f-a091-9d30038e0788
spec:
config:
cleanup.policy: compact
partitions: 1
replicas: 3
status:
conditions:
- lastTransitionTime: "2024-08-26T02:15:04.974685907Z"
message: Replication factor change not …
```

:bug:  kafka replicas topic

---

agent/pkg/controllers/crd_controller.go

Currently the agent has controller that watches custom resource definitions and acts when a new one is created. This controller doesn't really need to retrieve the details of those custom resource definitions: it only needs to detect when they are present. But the cache used for that will contain the complete definition anyhow. This patch changes that controller to use the `builder.OnlyMetadata` option, so that the cache will only hold the metadata of the CRDs, which consumes less space. In an OpenShift cluster with ACM installed, for example, the complete set of CRDs consumes approx 7 MiB, while the metadata consumes only 100 KiB.
Related: https://github.com/kubernetes-sigs/controller-runtime/blob/b901db121e1f53c47ec9f9683fad90a546688c3e/pkg/builder/options.go#L103-L133

Only watch metadata of CRDs in agent

---

test/integration/operator/hubofhubs/storage_test.go

The integration test failed frequently. I found the main reason is the mgh condition failed to update. We can remove it from here. And cover this session in the [re-think the status of global hub operand](https://issues.redhat.com/browse/ACM-13680)
Fixes #

:bug: Remove the database condition test from integration

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/controllers/addons/addons_controller.go
operator/pkg/controllers/addons/addons_controller_test.go
operator/pkg/controllers/hubofhubs/controller.go
operator/pkg/controllers/hubofhubs/prune/prune_reconciler.go
operator/pkg/controllers/hubofhubs/prune/prune_reconciler_test.go
operator/pkg/controllers/hubofhubs/webhook/manifests/addondeploymentconfig.yaml
operator/pkg/controllers/hubofhubs/webhook/manifests/managedclustersetbinding.yaml
operator/pkg/controllers/hubofhubs/webhook/manifests/placement.yaml
test/integration/operator/addons/addons_hosted_test.go
test/integration/operator/addons/suite_test.go

This pr revert the cma when uninstall globalhub
We also redefine the placement and addondeploymentconfig to disable the sync managedhubcluster label to clusterclaim 
Fixes #
https://issues.redhat.com/browse/ACM-14313
-   Manually tested the whole flow about importing hosted cluster and uninstall mgh

revert cma when uninstall globalhub

---

operator/pkg/controllers/hubofhubs/storage/manifests.sts/init-configmap.yaml

Currently, only create `inventory` dbname when the CR has `with-inventory` annotation. the db won't be created if add `with-inventory` annotation latter because the postgres sts is already running, the init configmap won't be executed.
for the longer term, we will enable inventory by default. So, just create it regardless of whether we have this annotation or not.
Fixes #
Tested in local environment

:bug: Create inventory always

---

operator/api/migration/v1alpha1/managedclustermigration_types.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

Owned CRDs should have resources specified
Fixes #
```
"status": {
"results": [
{
"name": "olm-crds-have-resources",
"log": "Loaded ClusterServiceVersion: multicluster-global-hub-operator-rh.v1.3.0\n",
"state": "fail",
"errors": [
"Owned CRDs do not have resources specified"
],
"creationTimestamp": null
}
]
}
```
ref: http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/multicluster-globalhub-operator-bundle-container-v1.3.0-31/b854a993-d8f2-4b8e-9e82-b3804a40e233/operator-custom-scorecard-tests-bundle-image-output.txt

:bug: Owned CRDs should have resources specified

---

operator/pkg/controllers/hubofhubs/transporter/protocol/byo_transporter.go
operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
operator/pkg/controllers/hubofhubs/transporter/transport_reconciler.go

When install the mgh, the operator will always waiting for the Kafka resource
```
oc logs -f -l name=multicluster-global-hub-operator -n multicluster-global-hub
I0923 04:33:59.194138       1 strimzi_transporter.go:580] Wait kafka cluster ready
I0923 04:33:59.497324       1 strimzi_transporter.go:580] Wait kafka cluster ready
...
```
The reason is the Kafka resource cannot ready 
```bash
❯ oc get kafka kafka -oyaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
creationTimestamp: "2024-09-23T03:50:21Z"
generation: 1
labels:
global-hub.open-cluster-management.io/managed-by: global-hub
name: kafka
namespace: multicluster-global-hub
port: 9093
tls: true
type: route
metricsConfig:
type: jmxPrometheusExporter
valueFrom:
configMapKeyRef:
key: kafka-metrics-config.yml
name: …
```

:sparkles: Kafka resource reconcile deadlock

---

operator/pkg/controllers/crd/crd_controller.go
operator/pkg/utils/utils.go
operator/pkg/utils/utils_test.go
test/e2e/cluster_test.go

follow up https://github.com/stolostron/multicluster-global-hub/pull/1128
if the managed clusters do not have global hub addon enabled, then do not add the annotations
Fixes #

:bug: Add annotations to the managedcluster if the global hub addon is there

---

agent/pkg/status/controller/generic/generic_event_syncer.go

In code logic, if the policy and hub info in synced to db, but do not synced heart beat. then we detached the hub cluster. The related policy and hubinfo will not be removed forever. So in this pr, we send the event immediately instead of waiting interval.
Will enhance this in future: https://issues.redhat.com/browse/ACM-14560
https://issues.redhat.com/browse/ACM-14401
Fixes #

fix policy number is not right

---

agent/pkg/config/agent_config.go
agent/pkg/controllers/hub_clusterclaim_controller.go
agent/pkg/controllers/version_clusterclaim_controller.go
agent/pkg/status/controller/controller.go
agent/pkg/status/controller/managedclusters/managed_cluster_info_syncer.go
agent/pkg/status/controller/managedclusters/managed_cluster_info_syncer_test.go
agent/pkg/status/controller/policies/policy_controller.go
agent/pkg/status/controller/policies/policy_controller_test.go
go.mod
operator/pkg/controllers/hubofhubs/inventory/manifests/secret.yaml

1. support k8s-policy
2. update to remove the creationtimestamp. see https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md#q-how-do-i-have-different-logic-in-my-reconciler-for-different-types-of-events-eg-create-update-delete
Fixes #

:sparkles: Inventory policy

---

manager/cmd/manager/main.go
operator/cmd/main.go

Fixes # https://issues.redhat.com/browse/ACM-14621
References: https://github.com/kubernetes-sigs/controller-runtime/pull/1548, https://github.com/kubernetes-sigs/controller-runtime/issues/1431, https://github.com/kubernetes-sigs/controller-runtime/issues/1754

:bug: Switch the minimum TLS version of webhook from 1.2 to 1.3

---

agent/pkg/spec/controller/syncers/migration_from_syncer.go
agent/pkg/status/controller/managedclusters/managed_cluster_syncer.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
operator/pkg/controllers/hubofhubs/controller.go
pkg/constants/constants.go

1. cannot detach the managedcluster due to no permission
2. the hub cluster name is not correct for the migrated managed cluster in the DB.
Fixes #https://issues.redhat.com/browse/ACM-14794
- Test the migration feature. the above 2 issues have disappeared.

:bug: fix migration issues

---

operator/pkg/controllers/hubofhubs/prune/prune_reconciler.go
operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go

the manager is waiting for the transport connection. in the first time, the transport connection is empty. once the kafka is ready, the transport connection will be set as correct value. when reinstall, the transport connection keeps the previous value so that the manager and grafana will be deploy at the beginning.
Fixes # https://issues.redhat.com/browse/ACM-14761
- tested in local environment for the re-installation

:bug: Clean the transport connection

---

operator/pkg/controllers/hubofhubs/storage/manifests.sts/conf-configmap.yaml

Fix the warning "vulnerable cipher usage in service/multicluster-global-hub-postgres"
Fixes # https://issues.redhat.com/browse/ACM-14622
```
$ oc port-forward service/multicluster-global-hub-postgres 8123:5432
...
$ nmap -Pn -sV --script ssl-enum-ciphers -p 8123 localhost
Starting Nmap 7.95 ( https://nmap.org ) at 2024-10-11 11:29 CST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00033s latency).
Other addresses for localhost (not scanned): ::1
PORT     STATE SERVICE    VERSION
8123/tcp open  postgresql PostgreSQL DB 9.6.0 or later
| ssl-enum-ciphers:
|   TLSv1.3:
|     ciphers:
|       TLS_AKE_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_AKE_WITH_CHACHA20_POLY1305_SHA256 (secp256r1) - A
|       TLS_AKE_WITH_AES_128_GCM_SHA256 (secp256r1) - A
| …
```

:bug: Bump the postgres SSL min protocol version from 1.2 to 1.3

---

agent/pkg/status/controller/managedclusters/managed_cluster_info_syncer.go
agent/pkg/status/controller/managedclusters/managed_cluster_info_syncer_test.go
agent/pkg/status/controller/policies/policy_controller.go
agent/pkg/status/controller/policies/policy_controller_test.go
go.mod
go.sum
operator/config/samples/global_hub_v1alpha1_managedclustermigration.yaml
pkg/constants/constants.go

1. distinguish create and update inspired from https://github.com/stolostron/multicluster-global-hub/pull/1154 Thanks @yanmxa 
2. Correct the usage for update and delete
3. Add labels to the request metadata
4. Add relationship for the policy to show the status 
Fixes #https://issues.redhat.com/browse/ACM-14812
- tested in local environment and have a demo for it.

:sparkles: :bug: Add Relationship and correct the update operations

---

doc/dev-preview.md

This patch fixes a typo in the instructions to enable the integration with _Red Hat Advanced Cluster Security_: the name of the namespace should be `rhacs-operator`.
None.
Tested the instructions manually.

🐛 Fix typo in RHACS integration instructions

---

agent/pkg/controllers/inventory/managedclusterinfo/managed_cluster_info_controller.go
agent/pkg/controllers/inventory/policy/policy_controller.go

Duplicated create message can be received by kafka. the current logic is sending the create request and then update the resource to add a new finalizer. the temporary annotation is updated to real resource. the fix is to return after creation.
Fixes # 
- verified in local environment

Fix multiple creation events

---

operator/pkg/controllers/crd/crd_controller.go

The case only occurs when the mgh CR is deleting and the global hub operator is restarted in the same time. so the SetKafkaResourceReady is not called.
Fixes # https://issues.redhat.com/browse/ACM-15011

:bug: Adjust the order

---

manager/pkg/spec/controllers/generic.go
operator/pkg/controllers/meta.go
operator/pkg/controllers/multiclusterhub/acm.go
operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
operator/pkg/controllers/transporter/transport_reconciler.go
test/integration/operator/controllers/grafana_test.go
test/integration/operator/controllers/inventory_test.go
test/integration/operator/controllers/manager_test.go
test/integration/operator/controllers/meta_controller_test.go
test/integration/operator/controllers/multiclusterhub_test.go
test/integration/operator/controllers/storage_test.go
test/integration/operator/controllers/transporter_test.go
test/integration/operator/meta_controller_test.go
test/integration/operator/suite_test.go
test/integration/utils/utils.go

encounter the error like
```bash
2024-11-05T07:07:20.920Z	ERROR	controller/controller.go:316	Reconciler error	{"controller": "transport", "controllerGroup": "operator.open-cluster-management.io", "controllerKind": "MulticlusterGlobalHub", "MulticlusterGlobalHub": {"name":"multicluster-global-hub-transport","namespace":"namespace-7g4m7k"}, "namespace": "namespace-7g4m7k", "name": "multicluster-global-hub-transport", "reconcileID": "2c3cbf7e-93dc-48aa-89b3-39789feb9e49", "error": "controller with name strimzi_controller already exists. Controller names must be unique to avoid multiple controllers reporting to the same metric"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/c …
```

:sparkles: Split the multiclusterhub controller from global hub

---

operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go

We should not have any wait logic in reconciler. so remove the kafakconnection wait login
https://issues.redhat.com/browse/ACM-15413
Fixes #

:sparkles: remove wait login in kafka controller

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/pkg/controllers/grafana/grafana_reconciler.go
operator/pkg/controllers/meta.go
operator/pkg/controllers/storage/storage_reconciler.go
operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
operator/pkg/controllers/transporter/transport_reconciler.go
test/integration/operator/controllers/multiclusterhub_test.go
test/integration/operator/controllers/transporter_test.go
test/integration/utils/utils.go
test/manifest/crd/operators.coreos.com_clusterserviceversions.yaml

Previously, we use kafka crd to check if kafaka ready, but it's better to use csv status to check if we should create kafka related cr.
https://issues.redhat.com/browse/ACM-15413
Fixes #

:sparkles: check kafka using csv

---

operator/pkg/controllers/hubofhubs/prune/prune_reconciler.go

Delete all kafkausers and kafkatopics in the global hub namespace instead of just managed by global hub. that is because we do not provide support for other purpose.
Fixes #
https://issues.redhat.com/browse/ACM-15062
- verified in the upgrade environment

:bug: Delete all kafkausers and kafkatopics in global hub namespace

---

operator/pkg/controllers/transporter/protocol/manifests/global-hub-kafka.yaml
operator/pkg/controllers/transporter/protocol/strimzi_transporter.go

The Kafka cluster enabled the KRaft should not validate the zookeeper. Reference: https://github.com/orgs/strimzi/discussions/10836
Fixes #

:bug: The Kafka cluster enabled the KRaft should not validate the zookeeper 

---

operator/cmd/main.go
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/config/status.go
operator/pkg/config/transport_config.go
operator/pkg/controllers/agent/addon_agent_manifest_acm.go
operator/pkg/controllers/agent/addon_manager.go
operator/pkg/controllers/agent/certificates/approver.go
operator/pkg/controllers/agent/certificates/csr.go
operator/pkg/controllers/agent/certificates/signer.go
operator/pkg/controllers/agent/hosted_agent_controller.go
operator/pkg/controllers/backup/backup_reconcile.go
operator/pkg/controllers/grafana/grafana_reconciler.go
operator/pkg/controllers/hubofhubs/prune/prune_reconciler.go
operator/pkg/controllers/inventory/inventory_reconciler.go
operator/pkg/controllers/managedhub/managedhub_controller.go
operator/pkg/controllers/manager/manager_reconciler.go
operator/pkg/controllers/meta.go
operator/pkg/controllers/storage/postgres_crunchy.go
operator/pkg/controllers/storage/postgres_statefulset.go
operator/pkg/controllers/storage/storage_reconciler.go
operator/pkg/controllers/transporter/protocol/byo_transporter.go
operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
operator/pkg/controllers/transporter/transport_reconciler.go
operator/pkg/utils/utils.go
operator/pkg/webhook/admission_handler.go
pkg/transport/config/confluent_config.go
pkg/utils/meta.go
pkg/utils/utils.go

The log data
```bash
2024-11-21T01:08:46.276Z        INFO    utils/utils.go:26       Go OS/Arch: linux/amd64
2024-11-21T01:08:46.276Z        INFO    utils/utils.go:27       Go Version: go1.22.5
2024-11-21T01:08:46.276Z        INFO    utils/utils.go:28       Git Commit: 944c4e82
2024-11-21T01:08:46.297Z        INFO    cmd/main.go:110 registering webhooks to the webhook server
2024-11-21T01:08:46.297Z        INFO    controller-runtime.webhook      webhook/server.go:183   Registering webhook     {"path": "/mutating"}
2024-11-21T01:08:46.297Z        INFO    cmd/main.go:115 starting manager
2024-11-21T01:08:46.297Z        INFO    controller-runtime.metrics      server/server.go:208    Starting metrics server
2024-11-21T01:08:46.297Z        INFO    manager/server.go:83    starting server …
```

:sparkles:  Switch zap log for global hub operator

---

agent/pkg/spec/dispatcher.go
agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_from_syncer_test.go
agent/pkg/spec/syncers/migration_to_syncer.go
pkg/transport/controller/controller_test.go

1. remove the backup secret since the `-current-hub` bookstrap secret can be added by default
2. retry for conflict error
3. wait for 10 seconds to ensure klusterletconfig is applied and then update `hubAcceptClient` to false to trigger the migration (TODO: there is condition indicates the klusterletconfig is applied)
4. remove the managed cluster when the cluster hubAcceptClient is false
Fixes # https://issues.redhat.com/browse/ACM-15220
- verified in local environment

:sparkles: Migration enhancement

---

operator/pkg/controllers/acm/resources.go

```
conditions:
- lastTransitionTime: "2024-11-28T03:53:35Z"
message: controller with name acm-controller already exists. Controller names
must be unique to avoid multiple controllers reporting to the same metric
reason: MulticlusterGlobalHubNotReady
status: "False"
type: Ready
- lastTransitionTime: "2024-11-28T03:50:40Z"
```
Fixes #

:bug: Fix the acm controller be added multiple times

---

operator/pkg/config/status.go
operator/pkg/config/storage_config.go
operator/pkg/config/transport_config.go
operator/pkg/controllers/acm/resources.go
operator/pkg/controllers/agent/addon_manager.go
operator/pkg/controllers/agent/default_agent_controller.go
operator/pkg/controllers/agent/hosted_agent_controller.go
operator/pkg/controllers/backup/backup_reconcile.go
operator/pkg/controllers/backup/backup_start.go
operator/pkg/controllers/grafana/grafana_reconciler.go
operator/pkg/controllers/inventory/inventory_reconciler.go
operator/pkg/controllers/managedhub/managedhub_controller.go
operator/pkg/controllers/manager/manager_reconciler.go
operator/pkg/controllers/storage/storage_reconciler.go
operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
operator/pkg/controllers/transporter/transport_reconciler.go
operator/pkg/controllers/webhook/webhook_controller.go

When operator restart, the transport connection is null, so the controllers(manager) which depend on the transport connection will not be start. But when transport connection is set, the kafka component status in mgh is not updated, so controller-runtime will not trigger reconcile to start manager controller. 
In this pr, we update the kafka component status in mgh when transport connection set.
The storage connection has the same problem, so we do it as the same way.
Fixes #

fix manager do not recreted after delete manager deploy

---

manager/pkg/processes/hubmanagement/hub_addon_controller.go
manager/pkg/processes/hubmanagement/hub_addon_controller_test.go

Fixes # https://issues.redhat.com/browse/ACM-16060

 :seedling:  Clean the resource when the addon is not found

---

pkg/transport/producer/generic_producer.go

```
2024-12-04T03:04:11.091Z        WARN    kafka-producer  producer/generic_producer.go:215        transport producer client error, ignore it for most cases       {"error": "4/4 brokers are down"}
github.com/stolostron/multicluster-global-hub/pkg/transport/producer.handleProducerEvents.func1
/workspace/pkg/transport/producer/generic_producer.go:215
```
https://github.com/confluentinc/librdkafka/issues/1072#issuecomment-281997806
Fixes #

:seedling: Lower the log level for the producer error "brokers are down"

---

agent/pkg/spec/dispatcher.go
manager/pkg/processes/hubmanagement/hub_management.go
test/integration/manager/spec/db2transport_test.go
test/integration/manager/spec/suite_test.go

The agent produces the following log during the manager startup
```
2024-12-02T02:45:52.142Z        INFO    spec/dispatcher.go:70   event dropped due to cluster name retrieval error       {"error": "\"clustername\" not found"}
```
Related PR: https://github.com/stolostron/multicluster-global-hub/pull/1111/files#diff-7ac9c176d89d2e8f14840bfdd791862ab1781cb144a00553d02f296d3f194b34
The expected outcome is to resynchronize the resource from the agent. However, it appears that the resync signal is being blocked on the agent side!
Fixes #
```bash
2024-12-02T03:22:24.037Z        INFO    controllers/clusterclaim_version_controller.go:31       NamespacedName: open-cluster-management/multiclusterhub
2024-12-02T03:23:58.026Z        INFO    status-resyncer syncers/resync_syncer.go:39     resync …
```

:bug: Resync the managed hub resources upon manager startup

---

operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/controllers/acm/resources.go
operator/pkg/controllers/agent/addon_manager.go
operator/pkg/controllers/agent/default_agent_controller.go
operator/pkg/controllers/agent/hosted_agent_controller.go
operator/pkg/controllers/backup/backup_start.go
operator/pkg/controllers/grafana/grafana_reconciler.go
operator/pkg/controllers/inventory/inventory_reconciler.go
operator/pkg/controllers/managedhub/managedhub_controller.go
operator/pkg/controllers/manager/manager_reconciler.go
operator/pkg/controllers/storage/storage_reconciler.go
operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
operator/pkg/controllers/transporter/transport_reconciler.go
operator/pkg/controllers/webhook/webhook_controller.go
test/integration/operator/controllers/grafana_test.go
test/integration/operator/controllers/inventory_test.go
test/integration/operator/controllers/storage_test.go
test/script/util.sh

We did not watch globalhub applied resources previously,  if user changed these resources, we should rollback them.
Fixes #
- manually removed the manager role/rolebinding, they will be recreated.

fix watch resources in each controller

---

operator/pkg/controllers/storage/manifests.sts/grafana-service-monitor.yaml
operator/pkg/controllers/storage/postgres_statefulset.go

The postgres url is not right and sshmode should be disable
https://issues.redhat.com/browse/ACM-16333
Fixes #

fix dashboard - postgres database has no data

---

test/integration/agent/status/localpolicy_event_test.go

Fix the race condition when he integration test might failed sometimes. Should set a proper filter time ensure the older events are filtered and the newer events shouldn't be filtered.
Fixes #
References: https://github.com/stolostron/multicluster-global-hub/pull/1279

:bug: integration test error for localpolicy event filter

---

operator/pkg/controllers/grafana/manifests/acm-global-strimzi-kafka.yaml

remove duplicate pannel in kafkadashboard

---

agent/pkg/controllers/inventory/managedclusterinfo/managed_cluster_info_controller.go
agent/pkg/controllers/inventory/managedclusterinfo/managed_cluster_info_controller_test.go
operator/pkg/controllers/agent/addon_manager.go
samples/inventory/requester/global_hub.go
samples/inventory/requester/managed_hub.go
test/e2e/kessel/cluster_test.go

Get ClusterId from managedcluster, because there is no clusterId in managedclusterinfo object for non-OpenShift Cluster.
Fixes # https://issues.redhat.com/browse/ACM-15814

:bug: Get clusterId from managedcluster

---

doc/reserved_names/README.md
operator/pkg/controllers/inventory/inventory_reconciler.go
operator/pkg/controllers/transporter/protocol/manifests/global-hub-kafka-node-pool.yaml
operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
pkg/constants/constants.go
pkg/transport/controller/controller.go
pkg/transport/controller/controller_test.go
pkg/transport/kafka_config.go

Fixes #
https://issues.redhat.com/browse/ACM-16108

handle upgrade kafka from zookeeper to kraft

---

operator/pkg/config/condition_test.go
operator/pkg/controllers/backup/suite_test.go
operator/pkg/deployer/hoh_deployer_suite_test.go
pkg/jobs/jobs_suite_test.go
test/integration/agent/controller/suite_test.go
test/integration/agent/spec/suite_test.go
test/integration/agent/status/suite_test.go
test/integration/manager/controller/suite_test.go
test/integration/manager/spec/suite_test.go
test/integration/manager/status/suite_test.go
test/integration/manager/webhook/admission_suite_test.go
test/integration/operator/controllers/agent/hosted_managedhub/suite_test.go
test/integration/operator/controllers/agent/suite_test.go
test/integration/operator/controllers/suite_test.go
test/integration/operator/suite_test.go
test/integration/operator/webhook/admission_suite_test.go

the default timeout is 10s which is not enough for the envtest environment sometimes. set it as 1 minute
Fixes #
```
unable to install CRDs onto control plane: unable to create CRD instances: unable to create CRD "managedserviceaccounts.authentication.open-cluster-management.io": etcdserver: request timed out
{
msg: "unable to install CRDs onto control plane: unable to create CRD instances: unable to create CRD \"managedserviceaccounts.authentication.open-cluster-management.io\": etcdserver: request timed out", 
```

:bug: Fix the failure of integration test

---

operator/pkg/config/condition_test.go
operator/pkg/controllers/backup/suite_test.go
operator/pkg/controllers/crd/crd_controller_test.go
operator/pkg/controllers/hubofhubs/controller_test.go
operator/pkg/deployer/hoh_deployer_suite_test.go
pkg/jobs/jobs_suite_test.go
test/integration/agent/controller/suite_test.go
test/integration/agent/spec/suite_test.go
test/integration/agent/status/suite_test.go
test/integration/manager/controller/suite_test.go
test/integration/manager/spec/suite_test.go
test/integration/manager/status/suite_test.go
test/integration/manager/webhook/admission_suite_test.go
test/integration/operator/addons/suite_test.go
test/integration/operator/agent/suite_test.go
test/integration/operator/hubofhubs/suite_test.go
test/integration/operator/webhook/admission_suite_test.go
test/manifest/kafka/kafka-cluster/kafka-cluster.yaml

the default timeout is 10s which is not enough for the envtest environment sometimes. set it as 1 minute
Fixes #
```
unable to install CRDs onto control plane: unable to create CRD instances: unable to create CRD "managedserviceaccounts.authentication.open-cluster-management.io": etcdserver: request timed out
{
msg: "unable to install CRDs onto control plane: unable to create CRD instances: unable to create CRD \"managedserviceaccounts.authentication.open-cluster-management.io\": etcdserver: request timed out", 
```

:bug: Fix integration

---

operator/pkg/config/storage_config.go
operator/pkg/config/transport_config.go
operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go

we should delete kafka pvc when delete mgh, if not, when we recreate mgh, the kafka pod can not start 
```
[root@ip-172-31-15-97 multicluster-global-hub]# oc get po
NAME                                                READY   STATUS             RESTARTS      AGE
kafka-kafka-0                                       0/1     CrashLoopBackOff   2 (9s ago)    41s
kafka-kafka-1                                       0/1     CrashLoopBackOff   2 (11s ago)   41s
kafka-kafka-2                                       0/1     CrashLoopBackOff   2 (9s ago)    40s
multicluster-global-hub-grafana-cc8b57d74-v6fh2     2/2     Running            0             89s
multicluster-global-hub-grafana-cc8b57d74-vvc9c     2/2     Running            0             89s
multicluster-global-hub-manager-698594c9-6tpcp …
```

fix error when delete mgh then recreate it

---

doc/troubleshooting.md
doc/upgrade/cleanup_legacy_postgres.sh
doc/upgrade/restore_event_tables.sh
doc/upgrade/restore_history_tables.sh
doc/upgrade/upgrade_to_globalhub_1.4.0.md

Fixes # https://issues.redhat.com/browse/ACM-16157
```bash
❯ ./doc/upgrade/restore_history_tables.sh
Using namespace: multicluster-global-hub
>> Backing up history tables from multicluster-global-hub-postgres-0 (multicluster-global-hub-postgres)...
>> Backup completed.
>> Restoring history tables to multicluster-global-hub-postgresql-0 (multicluster-global-hub-postgresql)...
SET
SET
SET
SET
SET
set_config
------------
(1 row)
SET
SET
SET
SET
COPY 0
COPY 1
COPY 0
>> Restore completed.
>> Cleaning up temporary files...
>> Local and remote backup files removed. Done!
```
```bash
❯ kubectl exec -it multicluster-global-hub-postgres-0 -n multicluster-global-hub -- psql -U postgres -d hoh
Defaulted container "multicluster-global-hub-postgres" out of: multicluster-global-hub-postgres, …
```

:seedling:  Restore the history and event tables after upgrading GH to 1.4.0

---

operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-deployment.yaml
operator/pkg/controllers/agent/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-deployment.yaml
operator/pkg/controllers/agent/manifests/templates/hubcluster/hubcluster-mch.yaml
operator/pkg/controllers/grafana/manifests/deployment.yaml
operator/pkg/controllers/inventory/manifests/deployment.yaml
operator/pkg/controllers/manager/manifests/deployment.yaml
operator/pkg/controllers/storage/manifests.sts/postgres-statefulset.yaml
operator/pkg/renderer/testdata/app/nginx-deployment.yaml
operator/pkg/renderer/testdata/output/all-nginx.golden.yaml
operator/pkg/renderer/testdata/output/all.golden.yaml
operator/pkg/renderer/testdata/output/default.golden.yaml
operator/pkg/renderer/testdata/output/external.golden.yaml
operator/pkg/renderer/testdata/output/ha.golden.yaml

When set tolerations in mgh like the following, manager and grafana deploy will always update quickly.
tolerations:
- effect: NoExecute
key: node.kubernetes.io/not-ready
operator: Exists
Fixes #

fix deployment always update

---

operator/pkg/controllers/agent/addon_manager.go
operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
pkg/constants/constants.go
test/integration/operator/controllers/agent/suite_test.go

1. Agent should start after transport ready
2. Add an annotation in kafka cr in upgrade case. then identify the `isNewKafkaCluster` based on this annotation. With this, operator restart will not impact this field.
Fixes #
https://issues.redhat.com/browse/ACM-16797

fix some issue about upgrade

---

doc/upgrade/restore_event_tables.sh
doc/upgrade/restore_history_tables.sh

Fixes # https://issues.redhat.com/browse/ACM-16799
```bash
❯ ./doc/upgrade/restore_history_tables.sh mgh
Using namespace: mgh
>> Backing up history tables from multicluster-global-hub-postgres-0 (multicluster-global-hub-postgres)...
>> Backup completed.
>> Removing duplicated history records from the target tables
> Processing table: history.local_compliance
Deleting records from history.local_compliance with compliance_date <= 2025-01-02
DELETE 4
>> Completed removing duplicated history records.
>> Restoring history tables to multicluster-global-hub-postgresql-0 (multicluster-global-hub-postgresql)...
SET
SET
SET
SET
SET
set_config 
------------
(1 row)
SET
SET
SET
SET
COPY 0
COPY 4
COPY 0
>> Restore completed.
>> Cleaning up temporary files...
>> Local and remote backup files removed. …
```

:bug: Fix the duplicate key value violates unique constraint of history table restore

---

operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/pkg/controllers/agent/default_agent_controller.go
test/integration/operator/controllers/agent/cluster_default_addon_test.go
test/integration/operator/controllers/agent/cluster_hosted_addon_test.go
test/integration/operator/controllers/agent/cluster_none_addon_test.go
test/integration/operator/controllers/agent/hosted_managedhub/mgh_hosted_test.go

InstallAgentOnHub determines whether deploy the Global Hub Agent on hub cluster.
If set to true, the Global Hub Agent will be installed on the hub cluster only.
If set to false, the Global Hub Agent will not be installed on the hub cluster.
Currently, switching the value of this field is not supported after the Global Hub is installed.
Fixes # https://issues.redhat.com/browse/ACM-15099
- tested deploy the agent into local-cluster
- tested deploy the agent into hub cluster which has local-cluster="true" label

:sparkles: Install GH into a brownfield

---

operator/pkg/config/storage_config.go
operator/pkg/constants/constants.go
operator/pkg/controllers/storage/storage_reconciler.go
test/integration/operator/controllers/storage_test.go

Fixes # https://issues.redhat.com/browse/ACM-16818
1. create
```bash
❯ oc get secret postgresql-user-testuser
Error from server (NotFound): secrets "postgresql-user-testuser" not found
❯ kubectl patch mgh multiclusterglobalhub -n multicluster-global-hub --type='merge' \
-p '{"metadata": {"annotations": {"global-hub.open-cluster-management.io/postgres-users": "[{\"name\": \"testuser\", \"databases\": [\"test1\"]}]"}}}'
multiclusterglobalhub.operator.open-cluster-management.io/multiclusterglobalhub patched
❯ kubectl exec -it multicluster-global-hub-postgresql-0 -n multicluster-global-hub -- psql -U postgres -d hoh;
Defaulted container "multicluster-global-hub-postgresql" out of: multicluster-global-hub-postgresql, prometheus-postgres-exporter
psql (16.4)
Type "help" for help.
hoh=# \l
List …
```

:sparkles: Init postgres user and database from annotation

---

operator/pkg/controllers/storage/manifests.sts/postgres-config-configmap.yaml
operator/pkg/controllers/storage/postgres_statefulset.go
operator/pkg/controllers/storage/storage_reconciler.go
pkg/constants/constants.go
test/integration/operator/controllers/storage_test.go

You need to restart the Postgres instance for the configuration to take effect!
Fixed: https://issues.redhat.com/browse/ACM-16887
Resolved: https://github.com/stolostron/multicluster-global-hub/issues/1320, which provides the details for addressing the aforementioned Jira issue.
- Check the configuration before 
```bash
❯ kubectl exec -it multicluster-global-hub-postgresql-0 -n multicluster-global-hub -- psql -U postgres -d hoh;
Defaulted container "multicluster-global-hub-postgresql" out of: multicluster-global-hub-postgresql, prometheus-postgres-exporter
psql (16.4)
Type "help" for help.
hoh=# SHOW wal_level;
wal_level
-----------
replica
(1 row)
hoh=# SHOW max_wal_size;
max_wal_size
--------------
1GB
(1 row)
hoh=# exit
```
- Change the configuration
```bash
❯ oc get cm …
```

:sparkles: Enable the builtin postgres configuration

---

agent/pkg/controllers/clusterclaim_hub_controller.go
agent/pkg/controllers/inventory/managedclusterinfo/managed_cluster_info_controller.go
agent/pkg/controllers/inventory/managedclusterinfo/managed_cluster_info_controller_test.go
agent/pkg/controllers/inventory/policy/policy_controller.go
operator/pkg/config/transport_config.go
pkg/transport/requester/inventory_client.go
pkg/utils/utils.go
samples/inventory/requester/global_hub.go
samples/inventory/requester/main.go
samples/inventory/requester/managed_hub.go
test/e2e/kessel/inventory_test.go

1. Replace the k8sCluster.ReporterData.ApiHref to managedhub apiHref
2. Replace the k8sCluster.ReporterData.ConsoleHref to managedhub consoleHref
3. Add policy annotation to K8SPolicy.labels
4. Add clusterstatus OFFLINE.
5. Change the reporterid to `managedhub name` instead of `managedhub name -client`
Fixes #

fix some inventory issues

---

doc/global_hub_builtin_postgresql.md
operator/pkg/controllers/storage/postgres_statefulset.go
operator/pkg/controllers/storage/storage_reconciler.go

As @hchenxa pointed out, the secret cannot contain the `_` character. it will replace `_` with `-`  when generating the secret. That means both `test_user`  and `test-user` will share the same postures secret `postgresql-user-test-user`
Fixes # https://issues.redhat.com/browse/ACM-17609
- configmap data: `chrome_service_user: '["chrome_service_db"]'`
```bash
2025-02-05T07:37:21.511Z        INFO    storage/storage_reconciler.go:471       postgres user already exist: chrome_service_user
2025-02-05T07:37:21.512Z        INFO    storage/storage_reconciler.go:448       database chrome_service_db already exists.
2025-02-05T07:37:21.513Z        INFO    storage/storage_reconciler.go:554       granted all privileges to user chrome_service_user on database chrome_service_db.
2025-02-05T07:37:21.513Z …
```

:bug: Provide the valid secret name for postgres user

---

operator/pkg/controllers/meta.go
test/Makefile

:seedling: Change the status into `progressing` if the upgraded pg instance is not ready

---

manager/cmd/main.go
operator/pkg/config/multiclusterglobalhub_config.go
test/script/kessel_e2e_setup.sh
test/script/util.sh

1. in kessel inventory, we should not install ACM related CRDs
2. for manager, we should not watch any ACM resource initially.
Fixes # https://issues.redhat.com/browse/ACM-17820

:bug: Fix cannot start manager

---

agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_to_syncer.go
agent/pkg/spec/syncers/migration_to_syncer_test.go
manager/pkg/controllers/migration_controller.go
pkg/constants/constants.go
test/integration/manager/controller/migration_test.go

1. the clusterrole name is changed from `system:open-cluster-management:managedcluster:bootstrap:agent-registration` to `open-cluster-management:managedcluster:bootstrap:agent-registration` in foundation so we need to update accordingly.
2. instead of watching the changes for managedserviceaccount, watch secret should be a better solution. if the secret gets update, we can capture it and update the bootstrap kubeconfig.
Fixes # https://issues.redhat.com/browse/ACM-17904

:bug: Watch secret

---

doc/simulation/backup_restore/backupenv.sh
doc/simulation/backup_restore/restoreenv.sh

QE need to run backup script in jenkins, so we should use https to clone code.
Fixes #

update backup script to use https to clone repo

---

agent/pkg/status/syncers/events/event_syncer.go
agent/pkg/status/syncers/events/handlers/clustergroupupgrade_handler.go
pkg/bundle/event/clustergroupupgrades_event_bundle.go
pkg/constants/constants.go
pkg/database/models/event.go
pkg/enum/event_type.go
test/integration/agent/status/clustergroupupgrade_event_test.go

Implements a simple cloud events emitter from TALM k8s' ones, which may have some extra (structured) information encoded in the event's annotations.
https://issues.redhat.com/browse/ACM-12511

Cloud Events emitter from cluster-group-upgrades-operator events

---

pkg/enum/event_type.go

Using the existing prefix const should avoid the need for `//nolint: go:s103` comments on existing and new event types.

Avoid nolint for line length checks in event types

---

operator/pkg/controllers/webhook/webhook_controller.go

```
2025-04-02T06:08:26.196Z	DEBUG	agent/default_agent_controller.go:180	reconcile default agent controller: multicluster-global-hub/multiclusterglobalhub
2025-04-02T06:08:26.196Z	DEBUG	config/multiclusterglobalhub_config.go:424	mgha may have 1 instance, but got 0
2025-04-02T06:08:26.196Z	DEBUG	transporter/transport_reconciler.go:120	reconcile transport controller
2025-04-02T06:08:26.196Z	DEBUG	managedhub/managedhub_controller.go:78	reconcile managedhub controller
2025-04-02T06:08:26.196Z	DEBUG	storage/storage_reconciler.go:184	reconcile storage controller
2025-04-02T06:08:26.196Z	DEBUG	webhook/webhook_controller.go:83	reconcile webhook controller
2025-04-02T06:08:26.196Z	DEBUG	backup/backup_reconcile.go:56	reconcile backup
2025-04-02T06:08:26.196Z	DEBUG	manager/manager_reconciler.go:179 …
```

:bug: set importClusterInHosted from mgh annotation

---

agent/pkg/spec/dispatcher.go
test/e2e/localpolicy_test.go
test/script/e2e_prow.sh
test/script/e2e_run.sh
test/script/e2e_setup.sh
test/script/util.sh

e2e is not stable in main branch is mainly due to the memory is not sufficient to support enable/disable agent. use `m5ad.2xlarge` instead - https://github.com/openshift/release/pull/63567
some minor fixes:
1.  do not enable service ca before enable olm to fix this error:
```
CSV "packageserver" failed to reach phase succeeded
customresourcedefinition.apiextensions.k8s.io/multiclusterhubs.operator.open-cluster-management.io created
multiclusterhub.operator.open-cluster-management.io/multiclusterhub created
multiclusterhub.operator.open-cluster-management.io/multiclusterhub patched
initializing hubs: 331 seconds
```
2. update KinD version to 0.19.0 to support kubernetes 1.27 so that it can be used by https://github.com/stolostron/multicluster-global-hub/pull/1499
3. remove double quote to …

:bug: Enhance e2e

---

agent/pkg/status/syncers/configmap/config_controller.go
operator/pkg/controllers/agent/local_agent_controller.go
operator/pkg/controllers/agent/manifests/configmap.yaml
operator/pkg/controllers/agent/standalone_agent_controller.go
operator/pkg/controllers/agent/standalone_agent_controller_test.go

Root cause: 
In operator part, we do not set the log level to agent configmap `multicluster-global-hub-agent-config`
In agent part, we do not watch the globalhub namespace to change log level.
Fixes #
https://issues.redhat.com/browse/ACM-19942

fix agent log level

---

manager/pkg/migration/migration_cleaning.go
manager/pkg/migration/migration_controller.go
manager/pkg/migration/migration_deploying.go
manager/pkg/migration/migration_initializing.go
manager/pkg/migration/migration_registering.go
manager/pkg/migration/migration_validating.go
test/integration/manager/migration/migration_test.go

Fixes # https://issues.redhat.com/browse/ACM-19782

:sparkles: Add cluster validation before starting migration process

---

operator/pkg/controllers/agent/local_agent_controller.go
operator/pkg/controllers/agent/local_agent_controller_test.go
operator/pkg/controllers/transporter/protocol/strimzi_transporter.go

When detaching the cluster or disabling the local agent:
The topic shouldn't be deleted. If you have to delete the topic, its offset should also be removed from the database. Otherwise, old offsets may block message consumption if the topic is recreated.
Fixes # https://issues.redhat.com/browse/ACM-20179

:bug: Use transporter to cleanup the kafka resources when disable local agent

---

operator/pkg/controllers/agent/standalone_agent_controller.go
test/integration/operator/controllers/agent/standalone_agent/suite_test.go

fix this issue
```
2025-04-22T14:05:03.482Z	ERROR	agent/standalone_agent_controller.go:110	the cache is not started, can not read objects
github.com/stolostron/multicluster-global-hub/operator/pkg/controllers/agent.StartStandaloneAgentController
/go/src/github.com/stolostron/multicluster-global-hub/operator/pkg/controllers/agent/standalone_agent_controller.go:110
github.com/stolostron/multicluster-global-hub/test/integration/operator/controllers/agent/standalone_agent.init.func2
/go/src/github.com/stolostron/multicluster-global-hub/test/integration/operator/controllers/agent/standalone_agent/suite_test.go:95
github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3
/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.22.2/internal/node.go:475 …
```

:bug:  Fix integration issue

---

pkg/transport/controller/controller_test.go
test/integration/agent/status/managedcluster_event_test.go

Fixes #
```
2025-04-27T14:16:19.958Z	ERROR	handlers/managedcluster_handler.go:97	failed to get cluster: cluster2, event: cluster2/cluster2.event.17cd34e8c8b27fdd, error: ManagedCluster.cluster.open-cluster-management.io "cluster2" not found
github.com/stolostron/multicluster-global-hub/agent/pkg/status/syncers/events/handlers.(*managedClusterEventHandler).Update
/go/src/github.com/stolostron/multicluster-global-hub/agent/pkg/status/syncers/events/handlers/managedcluster_handler.go:97
github.com/stolostron/multicluster-global-hub/agent/pkg/status/generic.(*multiEventSyncer).updateObject
/go/src/github.com/stolostron/multicluster-global-hub/agent/pkg/status/generic/multi_event_syncer.go:115
github.com/stolostron/multicluster-global-hub/agent/pkg/status/generic.(*multiEventSyncer).Reconcile …
```

:bug:  Fix UT and integration test

---

manager/pkg/migration/migration_controller.go
manager/pkg/migration/migration_eventstatus.go
manager/pkg/migration/migration_eventstatus_test.go
manager/pkg/migration/migration_validating.go
operator/api/migration/v1alpha1/managedclustermigration_types.go
operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml

Define the event status struct to be used by migration in different stages.
Fixes #

:sparkles: Event status

---

agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_from_syncer_test.go
agent/pkg/spec/syncers/migration_to_syncer.go
agent/pkg/spec/syncers/migration_to_syncer_test.go
manager/pkg/migration/migration_cleaning.go
manager/pkg/migration/migration_controller.go
manager/pkg/migration/migration_deploying.go
manager/pkg/migration/migration_initializing.go
manager/pkg/migration/migration_registering.go
manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
operator/api/migration/v1alpha1/managedclustermigration_types.go
operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml
pkg/bundle/migration/managedcluster_migration.go
test/integration/manager/migration/migration_test.go

https://issues.redhat.com/browse/ACM-20319
Fixes #
- run e2e tests
```
conditions:
- lastTransitionTime: "2025-04-29T06:46:09Z"
message: Migration resources have been validated
reason: ResourceValidated
status: "True"
type: ResourceValidated
- lastTransitionTime: "2025-04-29T06:46:14Z"
message: All source and target hubs have been successfully initialized
reason: ResourceInitialized
status: "True"
type: ResourceInitialized
- lastTransitionTime: "2025-04-29T06:46:19Z"
message: Resources have been deployed to the target hub cluster
reason: ResourcesDeployed
status: "True"
type: ResourceDeployed
- lastTransitionTime: "2025-04-29T06:50:00Z"
message: All migrated clusters are registered
reason: ClusterRegistered
status: "True"
type: ClusterRegistered
- lastTransitionTime: …
```

:sparkles:  Wait for managed clusters are available

---

agent/pkg/spec/syncers/migration_from_syncer.go

This is a temporary solution to wait for 5 seconds to ensure the topic is authorized. this is an experienced value.
We will enhance it by using `gh-spec` and give the write permission to all the managed hub cluster at the beginning.
why do we need to enhance it?
that is because `KafkaProducer().Produce(event, nil)` is an asynchronous call, we cannot capture the error to retry.
here is one case I observed
```
2025-04-30T12:07:21.217Z	INFO	syncers/migration_from_syncer.go:398	send the migration resources to the migration topic from the source cluster
2025-04-30T12:07:21.242Z	DEBUG	syncers/migration_from_syncer.go:332	resend the migration resources due to topicPartition error
2025-04-30T12:07:26.243Z	WARN	kafka-producer	producer/generic_producer.go:202	delivery failed	{"error": "Broker: …
```

Wait for 5 seconds to ensure topic is authorized

---

agent/pkg/spec/spec.go
agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_from_syncer_test.go
agent/pkg/spec/syncers/migration_to_syncer.go
agent/pkg/spec/syncers/migration_to_syncer_test.go
manager/pkg/migration/migration_cleaning.go
manager/pkg/migration/migration_eventstatus.go
manager/pkg/migration/migration_eventstatus_test.go
manager/pkg/migration/migration_initializing.go
manager/pkg/migration/migration_registering.go
manager/pkg/migration/migration_validating.go
manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go

After migration, the cluster is managed by the target hub. To detach it from the source hub upon successful migration, we need to cache its original location under the source hub.
Fixes # https://issues.redhat.com/browse/ACM-20710

:bug: Detach the migrated clusters from source hub

---

.gitmodules
.tekton/multicluster-global-hub-agent-globalhub-1-5-pull-request.yaml
.tekton/multicluster-global-hub-agent-globalhub-1-5-push.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-5-pull-request.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-5-push.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-5-pull-request.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-5-push.yaml
agent/Containerfile.agent
manager/Containerfile.manager
rpms.in.yaml
rpms.lock.yaml

Refer to https://konflux-ci.dev/docs/building/prefetching-dependencies/#enabling-prefetch-builds-for-rpm to pre-fetch the rpm packages
- follow [rpm-lockfile-prototype](https://github.com/konflux-ci/rpm-lockfile-prototype?tab=readme-ov-file#installation) to install rpm-lockfile-prototype
- run `rpm-lockfile-prototype rpms.in.yaml --bare`
Fixes #

:sparkles: Support multi-arch

---

test/script/ocm.sh
test/script/util.sh

sometimes, we found that the cluster is not ready due to `no CSR to approve for cluster hub2` in e2e. that is because the join command is not executed successfully. we already have the logic to retry, but the `clusteradm accept` wait too long time (5m) so that the kafka and postgres can be ready and the test starts to run.
Fixes #

:bug:  Fix no CSR to approve for cluster issue

---

agent/pkg/spec/syncers/migration_from_syncer.go
operator/pkg/controllers/agent/addon/default_agent_controller.go
test/e2e/local_agent_test.go
test/integration/operator/controllers/agent/managedclusteraddon_test.go

https://github.com/open-cluster-management-io/ocm/issues/1017
Fixes # https://issues.redhat.com/browse/ACM-21092

:bug: Don't install the global hub agent in brownfield mode

---

manager/pkg/migration/migration_cleaning.go

https://issues.redhat.com/browse/ACM-21114
Fixes #

:bug: skip cleanup when the migration is not initialized

---

agent/pkg/spec/syncers/migration_to_syncer.go
agent/pkg/spec/syncers/migration_to_syncer_test.go

This pr fix the error message in registering condition like
```yaml
- lastTransitionTime: "2025-06-03T09:38:48Z"
message: 'register to hub local-cluster with error: failed to register these clusters
[]: works aren''t applied: [clc-iks-969-qnprf-iks]'
reason: Timeout
status: "False"
type: ClusterRegistered
```
the correct registering error message:
```yaml
- lastTransitionTime: "2025-06-03T09:38:48Z"
message: 'register to hub local-cluster with error: registering "timeout" - manifestwork(*-klusterlet) are not applied in these clusters: [clc-iks-969-qnprf-iks]'
reason: Timeout
status: "False"
type: ClusterRegistered
```
But the root reason for the error is the manifestwork not ready after 10 minutes, the agent log from the target hub
```bash
2025-06-03T09:38:48.426Z	INFO …
```

:seedling: Correct the registering error message

---

manager/pkg/migration/migration_controller.go
manager/pkg/migration/migration_controller_test.go
manager/pkg/migration/migration_eventstatus.go
test/script/kessel_e2e_setup.sh
test/script/util.sh

the root cause is the message is dropped. refer to this info `conflator/conflation_unit.go:68 the conflationElement predication is false      {"event": "Context Attributes,\n  specversion: 1.0\n  type: io.open-cluster-management.operator.multiclusterglobalhubs.managedclustermigration\n  source: local-cluster\n  id: 2f090ebd-29a1-42f8-bff3-9fc00db9ec6a\n  time: 2025-06-10T06:33:36.025868688Z\n  datacontenttype: application/json\nExtensions,\n  clustername: global-hub\n  extversion: 1.2\n  kafkamessagekey: io.open-cluster-management.operator.multiclusterglobalhubs.managedclustermigration\n  kafkaoffset: 2008\n  kafkapartition: 0\n  kafkatopic: gh-status.local-cluster\nData,\n  {\n    \"migrationId\": \"e49d44d5-4ae3-458f-b84e-74cb38bb8cab\",\n    \"stage\": \"ResourceDeployed\"\n  }\n"}` …

:bug: Need to wait until the cleanup is done

---

operator/pkg/controllers/agent/addon/hosted_agent_controller.go

this case is add `deploy-mode` label to local-cluster so that the namespace is updated.
https://issues.redhat.com/browse/ACM-21516
Fixes #

do not change local-cluster addon ns in hosted mode

---

manager/pkg/migration/migration_cleaning.go
manager/pkg/migration/migration_controller.go
manager/pkg/migration/migration_controller_test.go

1. trigger cleanup process if previous stage failed with timeout 
2. fix the issue that migration cr always pending even if the cleaning stage don't start(validating error)
Fixes # https://issues.redhat.com/browse/ACM-21572

:bug: trigger cleaning up process if previous stage failed with timeout

---

operator/pkg/webhook/admission_handler.go
operator/pkg/webhook/admission_handler_test.go
test/integration/operator/webhook/admission_handler_test.go

when MCE enable local-cluster, the klusterletaddonconfig created before the managedcluster cr created, so we should allow the request if the managedcluster is not found.
https://issues.redhat.com/browse/ACM-21723
Fixes #

fix issue: can not enable local-cluster when globalhub installed

---

agent/pkg/configs/resync_config.go
agent/pkg/configs/resync_config_test.go
agent/pkg/spec/syncers/resync_syncer.go
pkg/enum/event_type.go

Previously, the agent held the entire bundle in memory and triggered resyncs by updating the bundle version.
With the streaming-based approach, resyncing involves listing resources, converting them into bundles, and sending them. A `ResyncQueue` object tracks resync progress, and a periodic syncer uses the resync queue to drive both sync and resync operations.
Fixes #

:sparkles: Add the resync queue for the streaming-based bundle 

---

agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_from_syncer_test.go
agent/pkg/spec/syncers/migration_to_syncer.go
manager/pkg/migration/migration_validating_test.go
manager/pkg/status/conflator/element_delta.go
samples/cloudevent/migration/agent/main.go
test/integration/agent/migration/migration_from_syncer_test.go

Fixes # https://issues.redhat.com/browse/ACM-19540
1. create a migration resources
```yaml
apiVersion: global-hub.open-cluster-management.io/v1alpha1
kind: ManagedClusterMigration
metadata:
...
finalizers:
- global-hub.open-cluster-management.io/migration-cleanup
generation: 1
name: migration-sample
namespace: multicluster-global-hub
spec:
from: local-cluster
includedManagedClusters:
- cluster1
to: hub1
```
2. mock sending a registring error message to the global hub manager
```bash
apiVersion: global-hub.open-cluster-management.io/v1alpha1
kind: ManagedClusterMigration
metadata:
...
uid: 86d3a764-f736-441f-8910-33a3ac765b44
spec:
from: local-cluster
includedManagedClusters:
- cluster1
to: hub1
status:
conditions:
- lastTransitionTime: "2025-08-11T13:21:13Z"
message: Migration instance is …
```

:sparkles: Ensure the managed cluster is available when registering failed

---

manager/pkg/migration/migration_cleaning.go
manager/pkg/migration/migration_rollbacking.go
manager/pkg/migration/migration_validating.go

https://issues.redhat.com/browse/ACM-22600
- Added event recording for migration failures, errors, and timeouts across all migration stages
- Events are recorded during validation, rollbacking, and cleaning phases when errors occur
- Provides better observability for operators monitoring migration processes
- **migration_validating.go**: Added event recording for validation failures
- **migration_rollbacking.go**: Added event recording for rollback errors and timeouts  
- **migration_cleaning.go**: Added event recording for cleanup errors
- Uses `EventRecorder.Eventf` with appropriate event types (Warning) and reasons
- **Better observability**: Operators can monitor migration issues via `kubectl get events`
- **Consistent event format**: All stages use standardized event recording
- …

add event recording for migration failures/errors/timeouts

---

manager/pkg/migration/migration_controller.go
manager/pkg/migration/migration_controller_test.go

The config set in migration cr, so it should only take effect for this migraiton, instead of all migraiton
Fixes #

set timeout for each migration cr

---

.github/workflows/auto_code_review.yml

github.event.pull_request.author_association does not look at your custom roles or groups in GitHub. It only reflects GitHub’s built-in relationship model between the PR author and the repository. So I have add `yanmxa` `ldliu` `clyang82` as explicitly. it is working now.
Fixes #

Remove debug info

---

agent/pkg/spec/migration/migration_to_syncer.go
agent/pkg/spec/migration/migration_to_syncer_test.go
manager/pkg/migration/migration_eventstatus.go
manager/pkg/migration/migration_rollbacking.go
manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
pkg/bundle/migration/managedcluster_migration.go

Improved migration workflow with better error reporting and cluster management:
- Added cluster-specific error mapping in migration syncer for detailed error reporting
- Enhanced migration status bundle to include cluster-level error information
- Improved registering stage timeout handling with per-cluster error tracking
- Updated rollback logic to handle only failed clusters during registering phase
- Added cluster error state management in migration event status handling
- Enhanced migration status reporting with granular cluster error details
[ACM-22959](https://issues.redhat.com/browse/ACM-22959)
Fixes #

refactor: enhance migration error handling and cluster status tracking

---

manager/Containerfile.manager

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini

chore(KONFLUX-6210): fix and set name and cpe label for multicluster-global-hub-manager-globalhub-1-4

---

agent/Containerfile.agent

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini

chore(KONFLUX-6210): fix and set name and cpe label for multicluster-global-hub-agent-globalhub-1-4
