stolostron/multicluster-global-hub

deploy/README.md
deploy/deploy_hub_of_hubs.sh
deploy/deploy_leaf_hub_sync_service.sh

Signed-off-by: Ian Zhang <izhang@redhat.com>

make the css port configurable via ENV CSS_SYNC_SERVICE_PORT

---

deploy/deploy_hub_of_hubs.sh
deploy/deploy_leaf_hub.sh
deploy/deploy_leaf_hub_sync_service.sh
deploy/undeploy_hub_of_hubs.sh

addressing https://github.com/open-cluster-management/backlog/issues/17558
Signed-off-by: Ian Zhang <izhang@redhat.com>

use db as operator in hoh cluster

---

deploy/README.md
deploy/deploy_leaf_hub.sh

unable to do it automatically, since after single kubectl apply it gets
last-applied-annotation too long

perform manual editing of ClusterServiceVersion

---

deploy/undeploy_leaf_hub.sh

after further investigation, the purpose for the re-ordering is void.
deletion order was fine. new order is bad.

undo last commit

---

deploy/deploy_kafka.sh

followup PR for https://github.com/stolostron/hub-of-hubs-kafka-transport/pull/4

update amq-streams operator version to 1.8.4

---

deploy/deploy_hub_of_hubs.sh

fix namespace for hub cluster and hoh addon.

---

deploy/deploy_hub_of_hubs.sh
deploy/undeploy_hub_of_hubs.sh

deploy observability for hoh.

---

.gitignore
demos/setup/README.md
demos/setup/ocm_clean.sh
demos/setup/ocm_setup.sh

Signed-off-by: myan <yanmxa@163.com>

Bootstrap local leaf hub clusters with KinD

---

demos/setup/ocm_setup.sh

Install config-policy-controller to make sure policies can be enforced in KinD clusters.

fix policy enforce in KinD env.

---

README.md
deploy/deploy_hub_of_hubs.sh
deploy/undeploy_hub_of_hubs.sh

deplopy and undeploy the hub-of-hubs-manager.

---

deploy/deploy_hub_of_hubs.sh

fix application image patch command, otherwise, we will see the following error:

fix application image patch command.

---

demos/setup/ocm_setup.sh

Enable the application.app.k8s.io and route.openshift.io for kind cluster

---

release-notes/v0.4.0.md

Update release notes

---

deploy/deploy_hub_of_hubs.sh

fixed: https://github.com/stolostron/hub-of-hubs-manager/issues/24

replace placement image

---

demos/setup/ocm_clean.sh
demos/setup/ocm_setup.sh

Support external KUBECONFIG for ocm setup

---

test/setup/kafka/kafka-cluster.yaml
test/setup/kafka/kafka-operator.yaml
test/setup/kafka/kafka_setup.sh

Signed-off-by: Meng <yanmxa@163.com>

Enable kafka cluster for installing hub-of-hubs

---

agent/Dockerfile
agent/cmd/agent/main.go

Fix agent cannot start

---

agent/pkg/transport/producer/syncservice.go

fix: https://github.com/stolostron/backlog/issues/23783

fix null pointer exception for sync-service producer.

---

agent/cmd/agent/main.go

try to fix: https://github.com/stolostron/backlog/issues/23768

update leader election settings for hoh agent.

---

doc/hypershift/hypershift-install.md
doc/hypershift/hypershift.md
doc/hypershift/import-cluster-to-hypershift-leafhub.md
doc/hypershift/manifests/managedclusteraddon-application.yaml
doc/hypershift/manifests/manifestwork-application-manager.yaml
doc/hypershift/manifests/manifestwork-config-policy-controller.yaml
doc/hypershift/manifests/manifestwork-policy-framework.yaml

ref: https://github.com/stolostron/backlog/issues/23489

add hub-of-hubs with hypershift guide

---

test/setup/common.sh

e2e supports microshift cluster.

---

test/setup/common.sh
test/setup/leafhub_setup.sh
test/setup/microshift/microshift_setup.sh

fixes: https://github.com/stolostron/backlog/issues/23991

Fixed the connection issue between KinD and Microshift

---

test/setup/e2e_clean.sh
test/setup/e2e_setup.sh
test/setup/hoh/hub-of-hubs-rbac/secret/data.json

fixes: https://github.com/stolostron/backlog/issues/23992

Setup HoH locally with  Microshfit

---

Makefile
sonar-project.properties

Fix prow errors

---

test/pkg/test/hoh-cluster_test.go

Fixed: https://github.com/stolostron/backlog/issues/23918

List all the managedcluster with nonk8s api

---

cicd-scripts/run-local-e2e-test.sh
test/pkg/test/hoh-client_test.go
test/pkg/test/hoh-e2e-test_suite_test.go
test/pkg/utils/client.go
test/pkg/utils/options.go
test/pkg/utils/rbac.go
test/pkg/utils/shemas.go
test/resources/.gitignore
test/setup/e2e_clean.sh
test/setup/hoh/hub-of-hubs-rbac/secret/role_bindings.yaml
test/setup/microshift/microshift_setup.sh

Fixed: https://github.com/stolostron/backlog/issues/24008

Test connection and rbac for HoH scenario cases

---

test/pkg/test/hoh-label_test.go

Fixed:  https://github.com/stolostron/backlog/issues/23920

Modify the labels of the managed clusters with nonk8s api

---

cicd-scripts/run-local-e2e-test.sh
test/pkg/test/hoh-application_test.go

Fixed: https://github.com/stolostron/backlog/issues/23919

Verify the application local test

---

manager/pkg/nonk8sapi/authentication/authentication.go
manager/pkg/nonk8sapi/managedclusters/authorization.go
manager/pkg/nonk8sapi/non_k8s_api.go

fix 3 Vulnerabilities reported by sonarcloud

---

OWNERS

update owners to add longlong and meng

---

manager/pkg/nonk8sapi/authentication/authentication.go
manager/pkg/nonk8sapi/managedclusters/authorization.go

Fix sonarcloud problem

---

test/pkg/e2e/hoh-local-policy_test.go
test/setup/e2e_setup.sh
test/setup/leafhub_setup.sh

Fixed the kubeconfig issue and split the test spec for local policy 

---

test/resources/app/app-pacman-appsub.yaml
test/setup/common.sh
test/setup/hoh_setup.sh
test/setup/kafka/kafka-cluster.yaml

1. remove finalizer. it can be added automatically
2. set `klusterlet` operator replicas to 1
3. set `zookeeper` replicas to 1
4. only install route CRD for pacman application
5. set `hub-of-hubs-rbac` replicas to 1

Reduce the resources usage

---

doc/hypershift/hypershift-aws.md
doc/hypershift/hypershift-bm.md

workaround for acm hub CRDs apply.

---

cicd-scripts/run-prow-e2e-test.sh
test/pkg/e2e/hoh-application_test.go
test/resources/env.sh
test/setup/common.sh
test/setup/e2e_dependencies.sh
test/setup/e2e_setup.sh
test/setup/hoh/hub-of-hubs-manager.yaml
test/setup/hoh_setup.sh

Fixed: https://github.com/stolostron/backlog/issues/24259

Pass the new built images for e2e tests

---

cicd-scripts/run-prow-e2e-test.sh
test/setup/common.sh
test/setup/e2e_clean.sh
test/setup/leafhub_setup.sh

Fixed: https://github.com/stolostron/backlog/issues/24260

report the prow erros in artifact dir

---

test/pkg/e2e/hoh-application_test.go
test/pkg/e2e/hoh-cluster_test.go

Reference: https://github.com/stolostron/backlog/issues/24506

Fixed the E2E application test

---

go.mod
go.sum
operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/config/rbac/role.yaml
operator/main.go
operator/pkg/constants/constants.go
operator/pkg/controllers/leafhub/addon.go
operator/pkg/controllers/leafhub/leafhub_controller.go

operator manages addon resources.

---

operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/hub-of-hubs-agent-namespace.yaml
operator/pkg/controllers/leafhub/manifests/hypershift/hub/hosting/04-policy-addon-controller.yaml
operator/pkg/controllers/leafhub/manifests/hypershift/hub/hosting/05-policy-propagator.yaml
operator/pkg/controllers/leafhub/manifests/hypershift/hub/hosting/12-hub-of-hubs-agent-applier.yaml
operator/pkg/controllers/leafhub/manifestwork.go

fix manifestwork apply failure.

---

operator/pkg/controllers/leafhub/leafhub_controller.go

handle hohconfig update and recreate.

---

operator/config/samples/hubofhubs_v1alpha1_config.yaml
operator/pkg/config/hoh_config.go
operator/pkg/constants/constants.go
operator/pkg/controllers/hubofhubs/config_controller.go
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/rbac/deployment.yaml
operator/pkg/controllers/leafhub/leafhub_controller.go
operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/hub-of-hubs-agent-clusterrole.yaml
operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/hub-of-hubs-agent-deployment.yaml
operator/pkg/controllers/leafhub/manifests/hypershift/hub/hosting/12-hub-of-hubs-agent-applier.yaml
operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/hub-of-hubs-agent-clusterrole.yaml
operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/hub-of-hubs-agent-deployment.yaml
operator/pkg/controllers/leafhub/manifestwork.go
operator/pkg/controllers/leafhub/template.go

support override operands images with annotation.

---

manager/Dockerfile
manager/cmd/manager/main.go
manager/deploy/operator.yaml.template
manager/pkg/specsyncer/db2transport/transport/kafka/producer.go
manager/pkg/specsyncer/spec2db/controller/hoh_config_spec_sync.go
manager/pkg/statussyncer/transport2db/db/postgresql/batch/policies_batch_builder.go
manager/pkg/statussyncer/transport2db/transport/kafka/consumer.go
operator/pkg/controllers/hubofhubs/config_controller.go
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml

tune db and transport.

---

agent/deploy/hub-of-hubs-rbac.yaml
manager/deploy/operator.yaml.template
operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
operator/config/rbac/aggregated_role.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/clusterrole.yaml
operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/hub-of-hubs-agent-clusterrole.yaml
operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/hub-of-hubs-agent-clusterrole.yaml
test/setup/hoh/hub-of-hubs-manager.yaml

clean up hub-of-hubs config.

---

Makefile
agent/cmd/agent/main.go
agent/pkg/controllers/clusterrole_controller.go
agent/pkg/controllers/clusterrolebinding_controller.go
agent/pkg/controllers/controllers.go
agent/pkg/controllers/controllers_integration_test.go
agent/pkg/controllers/controllers_suite_test.go
operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/hub-of-hubs-agent-clusterrole.yaml
operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/hub-of-hubs-agent-clusterrole.yaml

fixed: https://github.com/stolostron/backlog/issues/24616

Create a new controller to apply the clusterrole and clusterrolebinding by hub-of-hubs-agent

---

operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
operator/config/rbac/aggregated_role.yaml
operator/config/rbac/aggregated_role_binding.yaml

fix operator aggregated role.

---

agent/cmd/agent/main.go
agent/deploy/hub-of-hubs-rbac.yaml
agent/pkg/lease/lease.go
operator/pkg/controllers/leafhub/addon.go
operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/hub-of-hubs-agent-clusterrole.yaml
operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/hub-of-hubs-agent-deployment.yaml
operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/hub-of-hubs-agent-role.yaml
operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/hub-of-hubs-agent-rolebinding.yaml
operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/hub-of-hubs-agent-serviceaccount.yaml
operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/hub-of-hubs-agent-clusterrole.yaml

update hoh lease with hoh agent.

---

Makefile
operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/pkg/controllers/hubofhubs/config_controller.go
operator/pkg/controllers/hubofhubs/manifests/placement/managedclustersetbinding.yaml
operator/pkg/controllers/hubofhubs/manifests/placement/placement.yaml

fixed: https://github.com/stolostron/backlog/issues/24615

Add default placement

---

operator/Dockerfile
operator/bundle/manifests/hub-of-hubs-operator.clusterserviceversion.yaml
operator/config/rbac/console_setup_role.yaml
operator/config/rbac/console_setup_rolebinding.yaml
operator/config/rbac/kustomization.yaml
operator/config/rbac/role.yaml
operator/operator.Dockerfile
operator/pkg/condition/condition.go
operator/pkg/controllers/hubofhubs/manifests/console-cleanup/hoh-console-cleanup.yaml
operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-script.yaml
operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-setup.yaml
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/deployer/hoh_deployer.go

ref: https://github.com/stolostron/backlog/issues/24612

handle console setup and clean.

---

operator/pkg/constants/constants.go
operator/pkg/controllers/leafhub/addon.go
operator/pkg/controllers/leafhub/leafhub_controller.go

fix condition set error in mgh delete case.

---

operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/controllers/hubofhubs/manifests/console-cleanup/hoh-console-cleanup.yaml
operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-setup.yaml
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go

support console job image customization.

---

operator/config/manager/kustomization.yaml
operator/config/samples/kafka/deploy_kafka.sh
operator/config/samples/kafka/kafka-operator.yaml
operator/config/samples/postgres/deploy_postgres.sh

Fixed the samples kafka and postgre issues

---

operator/pkg/controllers/hubofhubs/manifests/rbac/secret-opa-data.yaml

Ref: https://github.com/stolostron/backlog/issues/24610

add nonk8s authorization for e2e test user

---

cicd-scripts/run-prow-e2e-test.sh

fix the e2e issue due to the name change in prow - https://github.com/openshift/release/pull/31255

Fix e2e tests

---

operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/controllers/leafhub/leafhub_controller.go

followup PR for https://github.com/stolostron/multicluster-globalhub/pull/120
also need to handle console cleanup case 

fix console cleanup condition.

---

Makefile
test/setup/hoh/components/manager-service-local.yaml
test/setup/hoh/components/mgh-v1alpha1-cr.yaml
test/setup/hoh/hoh_setup.sh

Reference: https://github.com/stolostron/backlog/issues/24610

Setup local HoH with operator

---

test/pkg/e2e/hoh-application_test.go
test/pkg/e2e/hoh-policy_test.go

add retry for managedcluster retrieval in e2e.

---

Makefile
operator/config/samples/storage/postgres-cluster/postgres-cluster.yaml
operator/config/samples/transport/deploy_kafka.sh

clear sample pg users and kafka ca file

---

README.md

resolve: https://github.com/stolostron/backlog/issues/25026

add contributing section

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/config/samples/operator_v1alpha1_multiclusterglobalhub.yaml
operator/main.go
operator/pkg/config/hypershift_config.go
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/config/multiclusterglobalhub_config_test.go
operator/pkg/constants/constants.go
operator/pkg/controllers/hubofhubs/database.go
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/controllers/leafhub/leafhub_controller.go
operator/pkg/controllers/leafhub/manifestwork.go
test/setup/hoh/components/mgh-images-config.yaml
test/setup/hoh/components/mgh-v1alpha1-cr.yaml
test/setup/hoh/hoh_setup.sh

support image overrides.

---

test/setup/common.sh
test/setup/e2e_dependencies.sh

Signed-off-by: Meng Yan <myan@redhat.com>

Reduce the e2e OLM installation time

---

test/setup/e2e_setup.sh

overwrite the e2e leafhub label for mgh operator

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

ref: https://github.com/stolostron/backlog/issues/24608

update operator install mode.

---

operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-script.yaml

update to use 0.5.0 instead of latest tag

---

test/pkg/e2e/hoh-client_test.go
test/pkg/e2e/hoh-cluster_test.go
test/pkg/e2e/hoh-e2e-test_suite_test.go
test/pkg/e2e/hoh-label_test.go
test/pkg/e2e/hoh-policy_test.go

References: https://github.com/golang/go/issues/42026, https://github.com/golang/go/issues/40025

replace deprecated package ioutil with io and os

---

operator/pkg/controllers/hubofhubs/manifests/console-setup/hoh-console-script.yaml

Correct the configmap name

---

agent/cmd/agent/main.go
agent/pkg/spec/controller/syncers/managed_cluster_label_bundle.go
operator/pkg/constants/constants.go
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/multicluster-global-hub-agent-configmap.yaml
operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosted/multicluster-global-hub-agent-namespace.yaml
operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/multicluster-global-hub-agent-configmap.yaml
operator/pkg/controllers/leafhub/manifests/nonhypershift/agent/multicluster-global-hub-agent-namespace.yaml
pkg/constants/constants.go
test/pkg/e2e/hoh-client_test.go

ref: https://github.com/stolostron/backlog/issues/25025

Rename hoh to mgh for some resources

---

operator/Dockerfile

add check sum for operator image.

---

operator/pkg/controllers/hubofhubs/manifests/placement/managedclustersetbinding.yaml
operator/pkg/controllers/hubofhubs/manifests/placement/placement.yaml

Fixed: https://github.com/stolostron/backlog/issues/25172

delete mgh CR resource from agent

---

manager/pkg/specsyncer/spec2db/controller/managedclusterset_spec_sync.go
manager/pkg/specsyncer/spec2db/controller/managedclustersetbinding_spec_sync.go
manager/pkg/specsyncer/spec2db/controller/placement_spec_sync.go

Prevent local resources from being propagated to regional cluster

---

operator/bundle.Dockerfile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/metadata/annotations.yaml
operator/config/rbac/role.yaml
operator/main.go
operator/pkg/controllers/hubofhubs/finalizer.go
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
test/setup/hoh/hoh_setup.sh

Fixed: https://github.com/stolostron/backlog/issues/25315

prune application finalizer from global cluster

---

operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go

fix: https://bugzilla.redhat.com/show_bug.cgi?id=2122558

add missing watch for resources created but not owned by operator

---

operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go

fix: https://bugzilla.redhat.com/show_bug.cgi?id=2122862

allow customization for opa-data secret.

---

agent/cmd/applier/main.go
agent/pkg/status/controller/generic/generic_status_sync_controller.go

it is unnecessary to add finalizer to the resources in the regional hub cluster.

Remove finalizer in agent

---

test/pkg/e2e/hoh-application_test.go

ref: https://github.com/open-cluster-management-io/multicloud-operators-subscription/issues/247
Will revert this change once this issue is fixed in application side.

Skip application tests temporarily

---

agent/pkg/lease/lease.go
operator/pkg/constants/constants.go
operator/pkg/controllers/leafhub/addon.go
operator/pkg/controllers/leafhub/leafhub_controller.go
operator/pkg/controllers/leafhub/manifests/hypershift/agent/hosting/multicluster-global-hub-agent-role.yaml

support hosted mode for multicluster-global-hub addon.

---

Makefile
go.mod
go.sum
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/main.go
operator/pkg/controllers/hubofhubs/finalizer.go
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go

Fixed: https://github.com/stolostron/backlog/issues/25316

prune policy finalizer from global cluster

---

operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller_test.go
operator/pkg/controllers/leafhub/controllers_suite_test.go
operator/pkg/controllers/leafhub/leafhub_controller_test.go
operator/pkg/controllers/leafhub/packagemanifest.go
operator/pkg/controllers/leafhub/testdata/crd/0000_00_addon.open-cluster-management.io_clustermanagementaddons.crd.yaml
operator/pkg/controllers/leafhub/testdata/crd/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml
operator/pkg/controllers/leafhub/testdata/crd/0000_00_work.open-cluster-management.io_manifestworks.crd.yaml
operator/pkg/controllers/leafhub/testdata/crd/0000_01_addon.open-cluster-management.io_managedclusteraddons.crd.yaml

add envtest for leaf hub controller.

---

operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller_test.go

add more cases to mgh controller testing.

---

operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/controllers/leafhub/controllers_suite_test.go
operator/pkg/controllers/leafhub/leafhub_controller_test.go
operator/pkg/controllers/testdata/crd/cluster.open-cluster-management.io_hypershiftdeployments.yaml

add hypershift cases for leafhub controller testings.

---

README.md

Display code coverage

---

operator/pkg/controllers/hubofhubs/controllers_suite_test.go
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller_test.go
operator/pkg/controllers/leafhub/controllers_suite_test.go
operator/pkg/controllers/leafhub/leafhub_controller.go
operator/pkg/controllers/leafhub/leafhub_controller_test.go
operator/pkg/controllers/leafhub/packagemanifest.go

update package name for operator env test files.

---

operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go

cherrypick https://github.com/stolostron/multicluster-global-hub/pull/184 to release-2.6

cherrypick 184 to release-2.6

---

operator/pkg/controllers/hubofhubs/controllers_suite_test.go

Fixed multicluster-global-hub controller unit test issue

---

operator/PROJECT
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

missing part of https://github.com/stolostron/multicluster-global-hub/pull/193

update mgh api version.

---

Makefile
cicd-scripts/run-local-e2e-test.sh
cicd-scripts/run-prow-e2e-test.sh
test/pkg/e2e/hoh-cleanup_test.go
test/pkg/e2e/hoh-policy_test.go
test/pkg/e2e/hoh-prune_test.go

Fixed: https://github.com/stolostron/backlog/issues/25741

Add e2e tests for pruning resources

---

go.mod
go.sum

ref: https://github.com/stolostron/backlog/issues/25044

fix kubevirt dependency.

---

test/setup/common.sh
test/setup/e2e_setup.sh

[ Enhance ] wait kafka and postgres secrets to be ready in e2e test

---

operator/pkg/controllers/hubofhubs/database/3.tables.sql

resolve: https://github.com/stolostron/backlog/issues/25809

Correct the DB schema

---

agent/pkg/controllers/controllers_integration_test.go
manager/pkg/specsyncer/spec2db/controller/hoh_config_spec_sync_test.go
operator/pkg/controllers/hubofhubs/controllers_suite_test.go
operator/pkg/controllers/leafhub/controllers_suite_test.go

fix sonarcloud UT failure in post submit testings.

fix metrics port conflict in testings.

---

README.md
operator/Makefile
operator/README.md
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

fix: https://github.com/stolostron/backlog/issues/25948
fix: https://github.com/stolostron/backlog/issues/25947

allow override installation namespace for mgh operator.

---

operator/pkg/controllers/hubofhubs/database/3.tables.sql

Ref: https://github.com/stolostron/backlog/issues/25809

Replace the unique constraint of name with id for postgres status tables

---

manager/pkg/statussyncer/status/controller/placementbinding_controller.go

Reference: https://github.com/stolostron/backlog/issues/25859

Fixed palcementbinding is not found error when deleting the resources from global hub

---

test/pkg/e2e/hoh-application_test.go
test/pkg/e2e/hoh-policy_test.go
test/pkg/e2e/hoh-prune_test.go
test/pkg/utils/client.go
test/setup/common.sh

Ref: https://github.com/stolostron/backlog/issues/25859

Prune policy from regional hub when deleting policy from global hub

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml

remove operator image

---

pkg/compressor/compressor_test.go

Ref: https://github.com/stolostron/backlog/issues/26233

Add UT for transport compressor

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

ref: https://github.com/stolostron/backlog/issues/24608#issuecomment-1276869501

address comments from ID for operator bundle.

---

manager/pkg/nonk8sapi/non_k8s_api_test.go
manager/pkg/nonk8sapi/policies/constants.go
manager/pkg/nonk8sapi/policies/list.go
manager/pkg/specsyncer/db2transport/db/postgresql/postgresql.go
manager/pkg/specsyncer/spec2db/controller/generic_spec_to_db_reconciler.go

fix: https://github.com/stolostron/backlog/issues/26309
fix: https://github.com/stolostron/backlog/issues/26310

fix global hub issues.

---

manager/pkg/nonk8sapi/managedclusters/list.go
manager/pkg/nonk8sapi/non_k8s_api_test.go
manager/pkg/nonk8sapi/policies/list.go

ref: https://github.com/stolostron/backlog/issues/26230

only set continue token if it has remaining items.

---

manager/pkg/nonk8sapi/managedclusters/list.go
manager/pkg/nonk8sapi/non_k8s_api.go
manager/pkg/nonk8sapi/non_k8s_api_test.go
manager/pkg/nonk8sapi/policies/list.go
manager/pkg/nonk8sapi/subscriptions/get.go
manager/pkg/nonk8sapi/subscriptions/list.go
test/pkg/e2e/hoh-label_test.go
test/pkg/e2e/hoh-policy_test.go

ref: https://github.com/stolostron/backlog/issues/26230

add subscription api.

---

cicd-scripts/run-local-e2e-test.sh
manager/cmd/manager/main.go
manager/pkg/nonk8sapi/authentication/authentication.go
manager/pkg/nonk8sapi/non_k8s_api.go
manager/pkg/nonk8sapi/non_k8s_api_suite_test.go
manager/pkg/nonk8sapi/non_k8s_api_test.go
manager/pkg/nonk8sapi/subscriptions/list.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/config/rbac/aggregated_role.yaml
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/config/multiclusterglobalhub_config_test.go
operator/pkg/controllers/hubofhubs/manifests/manager/clusterrole.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/role.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/secret.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/service.yaml
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller_test.go
test/setup/hoh/components/manager-service-local.yaml

ref: https://github.com/stolostron/backlog/issues/26230

add oauth-proxy to nonk8s apiserver.

---

cicd-scripts/run-local-e2e-test.sh
manager/pkg/nonk8sapi/authentication/authentication.go
test/setup/hoh/components/manager-service-local.yaml

ref: https://github.com/stolostron/backlog/issues/26230

fix forward access token to upstream api server.

---

test/setup/common.sh
test/setup/e2e_setup.sh
test/setup/leafhub_setup.sh

check managed clusters available for e2e tests

---

manager/pkg/nonk8sapi/policies/list.go
manager/pkg/nonk8sapi/subscriptions/list.go

ref: https://github.com/stolostron/backlog/issues/26455

fix query last item for list api when there are deleted resources.

---

operator/main.go
operator/pkg/controllers/addon/addon.go
operator/pkg/controllers/addon/addon_controller.go
operator/pkg/controllers/addon/addon_suite_test.go
operator/pkg/controllers/addon/addon_test.go
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-deployment.yaml
operator/pkg/controllers/addon/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-deployment.yaml

Reference: https://github.com/stolostron/backlog/issues/26331

add leader election config for agent addon

---

manager/pkg/nonk8sapi/README.md
manager/pkg/nonk8sapi/non_k8s_api.go
manager/pkg/nonk8sapi/non_k8s_api_test.go
manager/pkg/nonk8sapi/subscriptions/get.go
manager/pkg/nonk8sapi/swagger.md
manager/pkg/nonk8sapi/swagger.yaml

remove subscription status api.

---

agent/cmd/agent/main.go

fix leaderelection in hosted mode

---

agent/pkg/controllers/clusterclaim_controller.go
agent/pkg/controllers/controllers.go
agent/pkg/controllers/hubclusterclaim_controller.go
agent/pkg/controllers/utils.go

fix hub clusterClaim is not created at the beginning

---

manager/cmd/manager/main.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/applications_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/channels_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/helpers.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/hoh_config_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/managed_cluster_labels_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/managed_cluster_set_bindings_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/managed_cluster_sets_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/placementbindings_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/placementrules_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/placementrules_db_to_transport_syncer_test.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/placements_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/policies_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/subscriptions_db_to_transport_syncer.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/syncers_suite_test.go
manager/pkg/specsyncer/db2transport/syncer/syncers.go
manager/pkg/statussyncer/transport2db/syncer/dbsyncer/control_info_db_syncer.go
manager/pkg/statussyncer/transport2db/syncer/dbsyncer/db_syncer.go
manager/pkg/statussyncer/transport2db/syncer/dbsyncer/generic_db_syncer.go
manager/pkg/statussyncer/transport2db/syncer/dbsyncer/local_spec_db_syncer.go
manager/pkg/statussyncer/transport2db/syncer/dbsyncer/managed_clusters_db_syncer.go
manager/pkg/statussyncer/transport2db/syncer/dbsyncer/policies_db_syncer.go
manager/pkg/statussyncer/transport2db/syncer/syncers.go
pkg/transport/consumer/kafka_consumer.go
pkg/transport/producer/kafka_producer.go
pkg/transport/transport.go

ref: https://github.com/stolostron/backlog/issues/26483

update the transport interface

---

agent/cmd/agent/main.go
agent/cmd/agent/main_test.go
manager/cmd/manager/main.go
manager/cmd/manager/main_test.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/syncers_suite_test.go
manager/pkg/statussyncer/transport2db/db/workerpool/db_worker.go
manager/pkg/statussyncer/transport2db/db/workerpool/db_worker_pool.go
manager/pkg/statussyncer/transport2db/syncer/dbsyncer/dbsyncer_suite_test.go
pkg/transport/consumer/consumer.go
pkg/transport/consumer/kafka_consumer.go
pkg/transport/kafka_test.go
pkg/transport/producer/kafka_producer.go
pkg/transport/producer/producer.go
pkg/transport/transport.go
pkg/transport/transport_suite_test.go

ref: https://github.com/stolostron/multicluster-global-hub/pull/267

make producer and consumer managed by controller-runtime manager.

---

agent/cmd/agent/main.go
agent/pkg/controllers/clusterclaim_controller.go
agent/pkg/controllers/controllers_integration_test.go
agent/pkg/controllers/controllers_suite_test.go
agent/pkg/controllers/hubclusterclaim_controller.go
agent/pkg/controllers/utils.go
doc/reserved_names/README.md
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
pkg/constants/constants.go
pkg/testdata/crds/0000_01_operator.open-cluster-management.io_clustermanagers.crd.yaml
test/setup/e2e_setup.sh

remove deprecated label and add check clustermanager

---

agent/cmd/agent/main.go
agent/cmd/agent/main_test.go
agent/pkg/incarnation/incarnation.go
agent/pkg/incarnation/incarnation_test.go
agent/pkg/lease/lease.go
agent/pkg/scheme/scheme.go
agent/pkg/status/controller/controller_suite_test.go
agent/pkg/status/controller/status_syncer_objects_test.go
agent/pkg/status/controller/status_syncer_test.go
manager/cmd/manager/main_test.go
pkg/testdata/crds/0000_00_apps.open-cluster-management.io_subscriptionreports_crd_v1alpha1.yaml
pkg/testdata/crds/0000_00_apps.open-cluster-management.io_subscriptionstatuses_crd_v1alpha1.yaml
pkg/testdata/crds/0000_03_clusters.open-cluster-management.io_placementdecisions.crd.yaml

ref: https://github.com/stolostron/backlog/issues/26232

add testing for agent status syncers.

---

agent/Dockerfile
agent/cmd/agent/main.go
agent/pkg/helper/config.go
manager/Dockerfile
manager/cmd/manager/main.go
operator/config/samples/transport/deploy_kafka.sh
operator/pkg/controllers/addon/addon.go
operator/pkg/controllers/addon/addon_integration_test.go
operator/pkg/controllers/addon/addon_test.go
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-deployment.yaml
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-secret.yaml
operator/pkg/controllers/addon/manifests/templates/hostedagent/multicluster-global-hub-agent-secret.yaml
operator/pkg/controllers/addon/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/kafka-ca.yaml
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller_test.go
operator/pkg/utils/utils.go
pkg/transport/consumer/kafka_consumer.go
pkg/transport/helpers/helpers.go
pkg/transport/helpers/helpers_test.go
pkg/transport/producer/kafka_producer.go
test/setup/hoh/kafka_setup.sh

ref: https://github.com/stolostron/backlog/issues/26300

replace inline kafka ca.

---

operator/config/samples/transport/deploy_kafka.sh
operator/config/samples/transport/kafka-cluster.yaml
operator/config/samples/transport/kafka-operator.yaml
test/setup/hoh/components/kafka-community-cluster.yaml
test/setup/hoh/components/kafka-community-operator.yaml
test/setup/hoh/kafka_setup.sh

Reference: https://github.com/stolostron/backlog/issues/26674

upgrade sample of kafka operator to 0.31.x

---

operator/pkg/controllers/addon/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-pre-delete-job.yaml

add annotation for pre-delete job in hosted mode

---

agent/cmd/agent/main.go
agent/pkg/incarnation/incarnation.go
agent/pkg/incarnation/incarnation_test.go
agent/pkg/status/controller/controller_suite_test.go
operator/pkg/controllers/addon/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-role.yaml
pkg/constants/constants.go

- put incarnation in agent namespace
- add role for agent to create/update incarnation configmap in hosted mode

put incarnation in agent namespace.

---

go.mod
go.sum
manager/cmd/manager/main.go

ref: https://github.com/stolostron/backlog/issues/26421

upgrade tls to 1.2 for webhook.

---

operator/config/samples/storage/deploy_postgres.sh
operator/config/samples/storage/undeploy_postgres.sh
operator/config/samples/transport/deploy_kafka.sh
operator/config/samples/transport/undeploy_kafka.sh
test/setup/common.sh
test/setup/hoh/kafka_setup.sh
test/setup/hoh/postgres_setup.sh

Reference: https://github.com/stolostron/backlog/issues/26694, https://github.com/stolostron/backlog/issues/26674

consolidate postgres and kafka scripts

---

agent/pkg/controllers/controllers_integration_test.go
agent/pkg/controllers/utils.go
operator/pkg/controllers/addon/addon.go
operator/pkg/controllers/addon/addoninstall_controller.go
operator/pkg/controllers/addon/addoninstall_controller_test.go
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-namespace.yaml
pkg/constants/constants.go

install the agent in the global-hub-system ns

---

agent/cmd/agent/main.go
agent/cmd/agent/main_test.go
agent/pkg/incarnation/incarnation.go
agent/pkg/incarnation/incarnation_test.go
agent/pkg/status/controller/controller_suite_test.go
operator/pkg/controllers/addon/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-role.yaml

ref: https://issues.redhat.com/browse/ACM-2023

fix incarnation in hosted mode.

---

manager/pkg/statussyncer/transport2db/syncer/dbsyncer/local_spec_db_syncer_test.go
manager/pkg/statussyncer/transport2db/syncer/dbsyncer/policies_db_syncer_test.go

Reference: https://github.com/stolostron/backlog/issues/26233

add UT for transport to db

---

operator/pkg/controllers/addon/addoninstall_controller.go
operator/pkg/controllers/addon/addoninstall_controller_test.go
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go

issue: https://issues.redhat.com/browse/ACM-2095

fix the addon deletion when mgh is deleted

---

operator/pkg/controllers/addon/addon.go
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller_test.go

double check message compression type.

---

test/setup/common.sh
test/setup/e2e_dependencies.sh

use latest clusteradm in e2e test setup.

---

doc/README.md
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

Update to 2.7 as required version for global hub

---

README.md
operator/README.md

ref: https://issues.redhat.com/browse/ACM-2194

fix operator uninstall doc.

---

manager/pkg/statussyncer/transport2db/syncer/dbsyncer/policies_db_syncer_test.go

add delta bundle comment in the UT test

---

manager/pkg/statussyncer/transport2db/db/workerpool/db_worker_pool.go
manager/pkg/statussyncer/transport2db/syncer/dispatcher/dispatcher.go

throw error when cann't get the database worker

---

test/setup/e2e_dependencies.sh

Fix e2e testing failures caused by docker version check error.

enhance docker version check.

---

Makefile
operator/config/samples/transport/undeploy_kafka.sh

fixed scripts for uninstalling kafka issues

---

operator/pkg/controllers/addon/addoninstall_controller.go

blocking the addon installation when MGH CR has the pause annotation

---

operator/apis/v1alpha2/multiclusterglobalhub_types.go
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml

Reference: https://github.com/stolostron/multicluster-global-hub/pull/319

modify the description for the transportFormat of API

---

operator/apis/v1alpha2/multiclusterglobalhub_types.go
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml

Resolve: https://github.com/stolostron/multicluster-global-hub/issues/323

abbreviation supports both mgh and mcgh

---

manager/pkg/specsyncer/db2transport/syncer/dbsyncer/syncers_test.go

check postgres connection before ut

---

manager/pkg/nonk8sapi/authentication/authentication.go

Error message: `Deferring unsafe method "Close" on type "io.ReadCloser"`

fixed the security issue of the sonar 'defer'

---

test/setup/hoh/postgres_setup.sh

refs: https://github.com/stolostron/multicluster-global-hub/pull/334

expose the test postgres database with nodeport

---

cicd-scripts/run-local-e2e-test.sh
operator/config/samples/storage/deploy_postgres.sh
test/pkg/e2e/hoh-application_test.go
test/pkg/e2e/hoh-client_test.go
test/pkg/e2e/hoh-e2e-test_suite_test.go
test/pkg/e2e/hoh-label_test.go
test/pkg/e2e/hoh-local-policy_test.go
test/pkg/e2e/hoh-policy_test.go
test/pkg/e2e/hoh-prune_test.go
test/pkg/utils/client.go
test/pkg/utils/options.go
test/resources/policy/local-enforce-limitrange-policy.yaml
test/resources/policy/local-inform-limitrange-policy.yaml
test/setup/hoh/postgres_setup.sh

correct the local policy e2e test

---

operator/pkg/controllers/hubofhubs/manifests/grafana/deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/serviceaccount.yaml

refs: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.2/html/authentication/using-service-accounts-as-oauth-client

fixed grafna auth issue

---

README.md
go.mod
go.sum
manager/cmd/manager/main.go
manager/cmd/manager/main_test.go
manager/pkg/config/manager_config.go
manager/pkg/nonk8sapi/non_k8s_api_test.go
manager/pkg/specsyncer/db2transport/db/postgresql/postgresql.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/syncers_suite_test.go
manager/pkg/specsyncer/db2transport/syncer/syncers.go
manager/pkg/specsyncer/spec2db/controller/controllers_suite_test.go
manager/pkg/statussyncer/transport2db/db/postgresql/postgresql.go
manager/pkg/statussyncer/transport2db/db/workerpool/db_worker_pool.go
manager/pkg/statussyncer/transport2db/syncer/dbsyncer/suite_test.go
manager/pkg/statussyncer/transport2db/syncer/syncers.go
manager/pkg/statussyncer/transport2db/syncer/syncers_test.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/samples/storage/deploy_postgres.sh
operator/pkg/controllers/hubofhubs/database.go
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller_test.go
pkg/database/connection.go
test/pkg/e2e/hoh-local-policy_test.go

Resolved: https://github.com/stolostron/multicluster-global-hub/issues/343

enable postgres tls connection for global hub manager

---

README.md
test/README.md

move e2e architecture graph from root to test

add e2e architecture

---

operator/pkg/controllers/addon/addon.go
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-deployment.yaml
operator/pkg/controllers/addon/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-deployment.yaml
operator/pkg/controllers/addon/manifests/templates/hubcluster/hubcluster-mch.yaml
operator/pkg/controllers/hubofhubs/grafana.go
operator/pkg/controllers/hubofhubs/manager.go
operator/pkg/controllers/hubofhubs/manifests/grafana/deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller_test.go
operator/pkg/renderer/testdata/app/nginx-deployment.yaml

support nodeSelector and tolerations for global hub operands.
FYI @hchenxa

nodeSelector and tolerations support

---

README.md
doc/README.md

add the readme comment for global hub grafana service

---

doc/reserved_names/README.md
operator/config/samples/operator_v1alpha2_multiclusterglobalhub.yaml

add 'mgh-image-repository' annotation to the readme

---

operator/pkg/controllers/hubofhubs/manifests/grafana/deployment.yaml

ref to https://github.com/stolostron/backlog/issues/16412 to fix https://issues.redhat.com/browse/ACM-4598

Do not skip the provider button

---

operator/pkg/constants/constants.go
operator/pkg/controllers/addon/addon_integration_test.go
operator/pkg/controllers/addon/addon_manifests.go
operator/pkg/controllers/addon/addon_suite_test.go
operator/pkg/controllers/hubofhubs/globalhub_grafana.go
operator/pkg/controllers/hubofhubs/globalhub_manager.go
operator/pkg/controllers/hubofhubs/integration_test.go

fixed: https://issues.redhat.com/browse/ACM-4731

remove the default hardcoded pull secret

---

README.md
doc/README.md

add the doc for postgres connection

---

test/pkg/e2e/hoh-local-policy_test.go

Description: The e2e test might fail sometimes. Because adding labels one by one in a for loop can easily cause timeouts. So instead, we add labels to each cluster first, and then check if the labels are added, so that we can add labels to multiple clusters in parallel and finish the test within the specified time.

fixed the e2e issue that managed cluster label isn't added

---

operator/pkg/controllers/hubofhubs/manifests/grafana/role.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/rolebinding.yaml

Referrences: https://issues.redhat.com/browse/ACM-4795

switch the grafana clusterrole to role

---

operator/config/samples/storage/postgres-cluster/postgres-cluster.yaml
test/setup/hoh/postgres_setup.sh

Fixed: https://github.com/stolostron/multicluster-global-hub/issues/373

enable HA for the postgres cluster

---

agent/cmd/agent/main.go

ref: https://issues.redhat.com/browse/ACM-5108

Allow create ACM

---

operator/config/samples/transport/kafka-cluster.yaml
operator/config/samples/transport/kafka-operator.yaml

refer https://strimzi.io/docs/operators/0.33.0/configuring.html#assembly-fips-support-str

update kafka to the FIPS supported version

---

go.mod
go.sum
manager/cmd/manager/main.go
manager/pkg/cronjob/sheduler.go
manager/pkg/cronjob/sheduler_test.go
manager/pkg/cronjob/task/compliance_history.go
manager/pkg/cronjob/task/compliance_history_test.go
manager/pkg/cronjob/task/task_suite_test.go

Reference: https://issues.redhat.com/browse/ACM-4099

add cronjob to sync data to local_status.compliance_history

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-cluster-group-compliancy-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-policies.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-policy-group-compliancy-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/deployment.yaml

Jira issue: https://issues.redhat.com/browse/ACM-4026

[ACM-4026] updated policies dashboards

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-cluster-group-compliancy-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml

Jira Issue: https://issues.redhat.com/browse/ACM-4026

[ACM-4026] Updated cluster policy dashboard label filter

---

operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml

refers: https://github.com/stolostron/acm-threat-model/pull/158

remove the rbac(*) for the global hub agent

---

doc/troubleshooting.md

ref: https://issues.redhat.com/browse/ACM-4575

add database dump and restore example.

---

doc/simulation/local-policies/README.md
doc/simulation/local-policies/create_local_policies.sql

ref: https://issues.redhat.com/browse/ACM-4104

add local policies simulation.

---

manager/pkg/cronjob/task/compliance_history.go
manager/pkg/cronjob/task/compliance_history_test.go

refs: https://github.com/stolostron/multicluster-global-hub/pull/413

fixed the trace for cronjob mightn't record the error message

---

agent/cmd/agent/main.go
agent/pkg/controllers/controllers.go
agent/pkg/controllers/controllers_suite_test.go
agent/pkg/controllers/event_exporter.go

we need to know the leaf hub name from event to do the following process.

set leafhubname as event clustername

---

OWNERS

Thanks @yanmxa for your contribution. Now, you are a qualified approver. Congrats! Keep your great work!

Add Meng as an approver

---

operator/pkg/controllers/addon/addoninstall_reconciler.go

Refer: https://issues.redhat.com/browse/ACM-5591

filter the target managedclusters of the agentaddon when manageraddon update/create

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-policies.yaml

refer https://issues.redhat.com/browse/ACM-5707

update the color

---

operator/pkg/controllers/hubofhubs/database/2.functions.sql
operator/pkg/controllers/hubofhubs/database/3.tables.sql
operator/pkg/controllers/hubofhubs/database/4.trigger.sql

Refers: https://issues.redhat.com/browse/ACM-5703
Blocked By: https://github.com/stolostron/multicluster-global-hub/pull/454

backup local policies to history when deleting it

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-cluster-group-compliancy-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-policies.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-policy-group-compliancy-overview.yaml

https://issues.redhat.com/browse/ACM-5729
https://issues.redhat.com/browse/ACM-5730

handle unknown status

---

agent/pkg/event/enhancers/policy_event.go
agent/pkg/event/enhancers/policy_event_test.go
agent/pkg/event/watcher.go
go.mod
go.sum
manager/cmd/manager/main.go
manager/pkg/eventcollector/event_collector.go
manager/pkg/eventcollector/event_collector_test.go
manager/pkg/eventcollector/processor/policy_processor.go
manager/pkg/eventcollector/processor/policy_processor_test.go
manager/pkg/eventcollector/processor/suite_test.go
operator/pkg/controllers/hubofhubs/database/3.tables.sql
pkg/constants/constants.go
pkg/database/gorm_conn.go
pkg/database/models/event.go
test/resources/policy/local-inform-limitrange-policy-placement.yaml

Refers: https://issues.redhat.com/browse/ACM-5737

collect root policy events

---

operator/pkg/condition/condition.go
operator/pkg/controllers/hubofhubs/globalhub_mch.go
operator/pkg/controllers/hubofhubs/globalhub_mch_test.go
operator/pkg/controllers/hubofhubs/integration_test.go

related to https://github.com/stolostron/multicluster-global-hub/pull/450
ref: https://issues.redhat.com/browse/ACM-5654

disable app-lifecycle in global hub.

---

README.md
doc/disconnected_environment/README.md
doc/simulation/local-policies/README.md
operator/README.md
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
samples/README.md
samples/config/storage_secret.go
samples/config/transport_secret.go
test/setup/common.sh

Refers: https://issues.redhat.com/browse/ACM-4732

update document for storage/transport secret names

---

manager/pkg/cronjob/task/compliance_history.go
manager/pkg/cronjob/task/compliance_history_test.go

This is to make the dashboard with simulated data more like real data.

generate random compliance when inserting simulated history policy compliance data

---

operator/pkg/controllers/addon/addoninstall_reconciler.go

Refers: https://issues.redhat.com/browse/ACM-5980

fixed addon log panic

---

doc/disconnected_environment/README.md
doc/disconnected_environment/imagecontentsourcepolicy.yaml
doc/disconnected_environment/operatorgroup.yaml
doc/disconnected_environment/subscription.yaml

refer https://issues.redhat.com/browse/ACM-4583

update dis doc

---

go.mod
go.sum
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/main.go
operator/pkg/controllers/addon/addon_integration_test.go
operator/pkg/controllers/addon/addon_suite_test.go
operator/pkg/controllers/addon/addoninstall_reconciler.go
operator/pkg/controllers/addon/addoninstall_reconciler_test.go
operator/pkg/controllers/hubofhubs/globalhub_controller.go
pkg/testdata/crds/0000_00_agent.open-cluster-management.io_klusterletaddonconfigs_crd.yaml
test/setup/hoh/hoh_setup.sh

ref: https://issues.redhat.com/browse/ACM-5999

disable application and policy from klusteraddonconfig.

---

doc/README.md

Added context to `doc/README.md` grafana dashboard topic.

Updated doc README Grafana dashboard section

---

agent/pkg/scheme/scheme.go
agent/pkg/status/bundle/hubcluster/hub_cluster_bundle.go
agent/pkg/status/controller/controlinfo/control_info_controller.go
agent/pkg/status/controller/controller.go
agent/pkg/status/controller/controller_integration_test.go
agent/pkg/status/controller/controller_suite_test.go
agent/pkg/status/controller/hubcluster/clusters_status_sync.go
manager/pkg/statussyncer/syncers.go
manager/pkg/statussyncer/syncers/hub_cluster_info_db_syncer.go
manager/pkg/statussyncer/syncers/hub_cluster_info_db_syncer_test.go
manager/pkg/statussyncer/syncers/local_spec_placementrule_syncer.go
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
operator/pkg/controllers/hubofhubs/database/2.tables.sql
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-policies.yaml
pkg/bundle/status/base_leaf_hub_cluster.go
pkg/conflator/conflation_priority.go
pkg/constants/constants.go
pkg/database/constants.go
pkg/database/models/status.go
pkg/objects/leader_election.go

https://issues.redhat.com/browse/ACM-6059

add status.leaf_hubs table to store the leaf hub information

---

operator/pkg/controllers/hubofhubs/database/2.tables.sql

Refers: https://issues.redhat.com/browse/ACM-6187

remove the not null constrait for cluster_id

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml

update operator version for main branch.

update operator version.

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-policies.yaml

fixes: https://issues.redhat.com/browse/ACM-6212

Fix dashboard links

---

test/pkg/e2e/hoh-deploy_test.go
test/pkg/e2e/hoh-e2e-test_suite_test.go
test/setup/hoh/hoh_setup.sh

move initiate MGH CR from shell to Golang

---

cicd-scripts/run-local-e2e-test.sh
test/pkg/e2e/hoh-deploy_test.go
test/pkg/e2e/hoh-e2e-test_suite_test.go
test/pkg/e2e/hoh-label_test.go
test/pkg/utils/options.go
test/setup/hoh/hoh_setup.sh

Move initiate MGH operator from shell to golang

---

doc/README.md
doc/dev-preview.md
doc/disconnected_environment/README.md
doc/global_hub_use_cases.md
doc/how_global_hub_works.md
doc/troubleshooting.md

cherry-pick https://github.com/stolostron/multicluster-global-hub/pull/532 manually

Cherry-pick 09396a manually

---

pkg/compressor/gzip_compressor.go
pkg/database/pgx_conn.go
pkg/transport/config/config_test.go
pkg/transport/config/helpers.go
pkg/transport/config/saram_config.go
pkg/utils/utils.go
test/pkg/testpostgres/testdatabase.go

repalce the deprecated ioutil with is/os

---

doc/hypershift/README.md
doc/hypershift/hypershift-aws.md
doc/hypershift/hypershift-bm.md
doc/hypershift/hypershift-regionalhub-import-cluster.md
doc/reserved_names/README.md
doc/simulation/README.md

ref: https://issues.redhat.com/browse/ACM-6014

Review updates

---

operator/pkg/controllers/hubofhubs/database/2.tables.sql

Ref: https://issues.redhat.com/browse/ACM-6441

add index for the `deleted_at` columns

---

operator/pkg/controllers/hubofhubs/database/2.tables.sql

Ref: https://github.com/stolostron/multicluster-global-hub/pull/558

fixed the deleted_at index issue

---

agent/pkg/incarnation/incarnation.go
doc/README.md
manager/pkg/cronjob/task/task_suite_test.go
manager/pkg/statussyncer/bundle/base_bundle.go
manager/pkg/statussyncer/bundle/clusters_per_policy_bundle.go
manager/pkg/statussyncer/bundle/complete_compliance_status_bundle.go
manager/pkg/statussyncer/bundle/control_info_bundle.go
manager/pkg/statussyncer/bundle/delta_compliance_status_bundle.go
manager/pkg/statussyncer/bundle/local_placement_rules_bundle.go
manager/pkg/statussyncer/bundle/minimal_compliace_status_bundle.go
manager/pkg/statussyncer/dispatcher/transport_dispatcher.go
manager/pkg/statussyncer/syncers/policies_db_syncer_test.go
pkg/bundle/status/base_leaf_hub_cluster.go
pkg/bundle/status/base_policy_history_event_bundle.go
pkg/bundle/status/bundle.go
pkg/conflator/bundle_info.go
pkg/conflator/bundle_info_test.go
pkg/conflator/complete_state_bundle_info.go
pkg/conflator/conflation_unit.go
pkg/conflator/delta_state_bundle_info.go

ref: https://issues.redhat.com/browse/ACM-6258

reset the bundle version when the agent start without the version info

---

doc/README.md
doc/disconnected_environment/README.md
doc/simulation/local-policies/README.md
operator/config/samples/kustomization.yaml
operator/config/samples/operator_v1alpha4_multiclusterglobalhub.yaml

Modify the global hub sample with API v1alpha4

---

doc/README.md

ref: https://issues.redhat.com/browse/ACM-6526

Support matrix

---

operator/pkg/controllers/hubofhubs/suite_test.go

Remove the vulnerable password from code

---

manager/pkg/statussyncer/syncers/hub_cluster_info_db_syncer.go
manager/pkg/statussyncer/syncers/local_policies_event_syncer.go
manager/pkg/statussyncer/syncers/local_spec_policies_syncer.go
operator/pkg/controllers/hubofhubs/database/2.tables.sql

1. Extend the size of the resource name for the tables.
2. Callback once the SQL transaction fails.

Extend the size of the resource name for the tables.

---

manager/pkg/cronjob/task/data_retention.go
manager/pkg/cronjob/task/data_retention_test.go

- rename the partition to retention
- add deleted record UT

add retention record with deleted time

---

manager/pkg/cronjob/task/data_retention.go

refer https://issues.redhat.com/browse/ACM-7029

fix code error

---

manager/pkg/nonk8sapi/non_k8s_api.go
operator/apis/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/pkg/controllers/hubofhubs/globalhub_grafana.go
operator/pkg/controllers/hubofhubs/globalhub_grafana_test.go
operator/pkg/controllers/hubofhubs/globalhub_manager.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/controllers/hubofhubs/manifests/grafana/deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
test/pkg/e2e/grafana_test.go

ref: https://issues.redhat.com/browse/ACM-6255

Support HA for manager

---

operator/pkg/controllers/hubofhubs/globalhub_postgres.go

update the secret name when the secret was not found.

update the secret name

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/pkg/constants/constants.go
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/globalhub_managedhubs.go
operator/pkg/controllers/hubofhubs/globalhub_prune.go
operator/pkg/controllers/hubofhubs/integration_test.go

ref: https://issues.redhat.com/browse/ACM-7336

add Annotations to prevent deleting app and policy crds in the managed hub cluster when deleting the corresponding addons

---

operator/pkg/controllers/hubofhubs/globalhub_grafana.go
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-default-alerting.yaml
test/pkg/e2e/grafana_test.go

https://issues.redhat.com/browse/ACM-7335

format alert info

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-default-alerting.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/alert-service.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/config-secret.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/deployment.yaml

https://issues.redhat.com/browse/ACM-7393

support alert ha

---

manager/cmd/manager/main.go
manager/pkg/config/manager_config.go
manager/pkg/cronjob/scheduler_test.go
manager/pkg/cronjob/sheduler.go
manager/pkg/cronjob/task/data_retention.go
manager/pkg/cronjob/task/data_retention_test.go
operator/pkg/controllers/hubofhubs/globalhub_manager.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
pkg/utils/time.go
pkg/utils/time_test.go

ref: https://issues.redhat.com/browse/ACM-7168

Replace the duration with month(int) for the data retention

---

operator/pkg/condition/condition.go
operator/pkg/condition/condition_test.go

Ref: https://issues.redhat.com/browse/ACM-7428

Fixed the bug that multiclusterglobalhub status is not updated

---

operator/pkg/controllers/hubofhubs/database/2.tables.sql

Fixed the sql bug when executing sql multiple times

---

operator/pkg/constants/constants.go
operator/pkg/controllers/hubofhubs/globalhub_managedhubs.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/utils/utils.go

ref: https://issues.redhat.com/browse/ACM-7150
add the annotation of "policy.open-cluster-management.io/sync-policies-on-multicluster-hub=true" to enable policy spec syncer

Sync policies

---

pkg/jobs/prune_finalizer.go

Ref: https://issues.redhat.com/browse/ACM-7373

Remove the version v1beta1 for clusterset and clustersetbinding

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-adhoc-investigation.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-policies.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-policies.yaml

https://issues.redhat.com/browse/ACM-7524

fix policy_name has mutiple policy_id

---

operator/pkg/controllers/hubofhubs/globalhub_grafana.go
operator/pkg/controllers/hubofhubs/integration_test.go

https://issues.redhat.com/browse/ACM-7489

restart grafana when datasource changed

---

sonar-project.properties

ref: https://github.com/stolostron/multicluster-global-hub/pull/601

Skip python scripts from sonarcloud

---

operator/pkg/controllers/hubofhubs/database/3.functions.sql

ref: https://issues.redhat.com/browse/ACM-7749

get not deleted managed cluster

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-overview.yaml

https://issues.redhat.com/browse/ACM-7867
https://issues.redhat.com/browse/ACM-7868

filter out deleted policies and clusters

---

manager/pkg/cronjob/task/local_compliance_history.go
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/controllers/addon/addon_manifests.go
operator/pkg/controllers/addon/addoninstall_reconciler.go
operator/pkg/controllers/hubofhubs/globalhub_config.go
operator/pkg/controllers/hubofhubs/globalhub_controller.go

Ref: https://issues.redhat.com/browse/ACM-4732

Watch the image pull secret and propagate it to components

---

agent/cmd/agent/main.go
agent/pkg/config/agent_config.go
operator/main.go
operator/main_test.go
operator/pkg/constants/constants.go
operator/pkg/controllers/addon/addon_controller.go
operator/pkg/controllers/addon/addon_manifests.go
operator/pkg/controllers/addon/addon_manifests_test.go
operator/pkg/controllers/addon/addon_suite_test.go
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-deployment.yaml
pkg/constants/constants.go
test/pkg/e2e/resources/leader-election-configmap.yaml

https://issues.redhat.com/browse/ACM-5096

set qps and burst for agent rest config

---

manager/pkg/cronjob/task/local_compliance_history.go
operator/pkg/kafka/kafka.go

Add kafka resource reservation

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-adhoc-investigation.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-policies.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/dashboard-source.yaml

https://issues.redhat.com/browse/ACM-7881

change default foder and fix leafhub rejoin issue

---

manager/cmd/manager/main.go
manager/pkg/cronjob/task/local_compliance_history.go
manager/pkg/metrics/cronjob.go

Ref: https://issues.redhat.com/browse/ACM-7866

Remove the duplicate metrics under a high availability condition

---

operator/pkg/controllers/hubofhubs/database/2.tables.sql

Ref: https://issues.redhat.com/browse/ACM-8202

Fixed the `leafhub_name/cluster_name` conflict on the managed clusters

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-overview.yaml

Update compliance status info

---

pkg/database/models/local_spec.go
pkg/database/models/status.go

Ref: https://issues.redhat.com/browse/ACM-7921

Trigger to update the updatedAt column

---

manager/pkg/cronjob/task/local_compliance_history.go

Ref: https://issues.redhat.com/browse/ACM-8220
The Summarization rule: https://github.com/stolostron/multicluster-global-hub/blob/main/doc/how_global_hub_works.md

Align the compliance aggragation with summarization rule

---

operator/pkg/kafka/kafka.go

Resolved: https://github.com/stolostron/multicluster-global-hub/issues/685

Fix the Kafka version to avoid bugs caused by version upgrades

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-cluster-group-compliancy-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-policy-group-compliancy-overview.yaml

ref: https://issues.redhat.com/browse/ACM-8229

Address review comments

---

doc/README.md

https://issues.redhat.com/browse/ACM-6230
https://issues.redhat.com/browse/ACM-7461

add known issue

---

doc/troubleshooting.md

Update the document for postgres connection

---

operator/pkg/controllers/hubofhubs/integration_test.go
test/pkg/e2e/grafana_test.go
test/pkg/utils/client.go

https://issues.redhat.com/browse/ACM-6245

add grafana e2e

---

operator/pkg/controllers/hubofhubs/globalhub_metrics.go

Extend the ServiceMonitor interval for metrics

---

agent/pkg/status/bundle/hubcluster/hub_cluster_bundle.go
agent/pkg/status/controller/hubcluster/clusters_status_sync.go
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-overview.yaml

https://issues.redhat.com/browse/ACM-8337
https://issues.redhat.com/browse/ACM-8390

fix obs url

---

manager/pkg/specsyncer/db2transport/db/gorm/spec.go
operator/main.go
operator/pkg/controllers/addon/addon_controller.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/utils/utils_test.go
pkg/utils/utils.go

resolved: https://github.com/stolostron/multicluster-global-hub/issues/607
- Format: add the color identification for different log level
- Trace the error log location when catch the error log
Example:

Trace the error log location

---

agent/pkg/status/controller/controller_integration_test.go
agent/pkg/status/controller/hubcluster/clusters_status_sync.go
manager/pkg/cronjob/task/data_retention_test.go
manager/pkg/statussyncer/syncers.go
manager/pkg/statussyncer/syncers/hub_cluster_info_db_syncer_test.go
manager/pkg/statussyncer/syncers/hub_cluster_info_syncer.go
operator/pkg/controllers/hubofhubs/database/2.tables.sql
operator/pkg/controllers/hubofhubs/globalhub_database.go
operator/pkg/controllers/hubofhubs/globalhub_database_test.go
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-adhoc-investigation.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-policies.yaml
operator/pkg/controllers/hubofhubs/upgrade/1.upgrade.sql
pkg/bundle/base/base_hub_cluster_bundle.go
pkg/bundle/cluster/hub_cluster_bundle.go
pkg/constants/constants.go
pkg/database/models/status.go

https://issues.redhat.com/browse/ACM-8409

add leaf hub id

---

cicd-scripts/run-prow-e2e-test.sh
manager/pkg/statussyncer/dispatcher/conflation_dispatcher.go
manager/pkg/statussyncer/dispatcher/transport_dispatcher.go
manager/pkg/statussyncer/syncers/hub_cluster_info_db_syncer_test.go
manager/pkg/statussyncer/syncers/local_placementrule_spec_syncer_test.go
manager/pkg/statussyncer/syncers/local_policy_spec_syncer_test.go
manager/pkg/statussyncer/syncers/policy_compliance_handler_test.go
pkg/bundle/metadata/bundle_status.go
pkg/conflator/conflation_bundle.go
pkg/conflator/conflation_complete_bundle.go
pkg/conflator/conflation_delta_bundle.go
pkg/conflator/conflation_element.go
pkg/conflator/conflation_unit.go
test/pkg/testpostgres/testdatabase.go

Add a new bundle status implementation that supports retry handling.
ref: https://github.com/stolostron/multicluster-global-hub/issues/729

Retrying insert bundle into with a threshold

---

agent/pkg/controllers/utils.go
agent/pkg/status/controller/local_policies/local_replicated_policy_sync.go
agent/pkg/status/controller/local_policies/local_root_policy_sync.go
agent/pkg/status/controller/policies/policy_status_sync.go
operator/main.go
operator/pkg/condition/condition.go
operator/pkg/controllers/backup/backup.go
operator/pkg/controllers/backup/backup_reconcile.go
operator/pkg/controllers/backup/backup_start.go
operator/pkg/controllers/backup/configmap.go
operator/pkg/controllers/backup/crd.go
operator/pkg/controllers/backup/globalhub.go
operator/pkg/controllers/backup/integration_test.go
operator/pkg/controllers/backup/kafka.go
operator/pkg/controllers/backup/kafkatopic.go
operator/pkg/controllers/backup/kafkauser.go
operator/pkg/controllers/backup/pvc.go
operator/pkg/controllers/backup/secret.go
operator/pkg/controllers/backup/suite_test.go
operator/pkg/utils/utils.go
pkg/utils/meta.go
pkg/utils/utils.go
test/pkg/e2e/backup_test.go
test/setup/e2e_setup.sh

https://issues.redhat.com/browse/ACM-8873
1. Check backup enabled based on mch
2. Add backup condition in mgh status

check backup enabled and add backup condition to mgh

---

operator/apis/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/pkg/constants/constants.go
operator/pkg/controllers/addon/addon_controller_manifests.go
operator/pkg/controllers/addon/addon_installer.go
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-deployment.yaml
operator/pkg/controllers/hubofhubs/globalhub_grafana.go
operator/pkg/controllers/hubofhubs/globalhub_manager.go
operator/pkg/controllers/hubofhubs/globalhub_postgres.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/controllers/hubofhubs/manifests/grafana/deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/postgres/statefulset.yaml
operator/pkg/transporter/strimzi_transporter.go
operator/pkg/transporter/strimzi_transporter_test.go
operator/pkg/utils/utils.go
operator/pkg/utils/utils_test.go

ref: https://issues.redhat.com/browse/ACM-9140

Support resources

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

ref: https://issues.redhat.com/browse/ACM-9179

Support upgrade from 1.0.0

---

operator/pkg/controllers/addon/manifests/templates/hubcluster/hubcluster-mch.yaml

ref: https://issues.redhat.com/browse/ACM-9292

Check .TolerationSeconds

---

operator/pkg/controllers/hubofhubs/upgrade/1.upgrade.sql

ref: https://issues.redhat.com/browse/ACM-9319

Fix the opeartor database reconcile error

---

operator/pkg/controllers/addon/addon_installer.go

If we delete the `kafkaTopic` and `kafkaUser` before the the `addon`, it will throw the following error when updating the manifestwork.
```bash
"addon-deploy-controller" controller failed to sync "acmqe-hoh-auto-z7ln7z/multicluster-global-hub-controller", err: Secret "acmqe-hoh-auto-z7ln7z-kafka-user" not found
```
ref: https://issues.redhat.com/browse/ACM-9426

Remove the `kafkaTopic/kafkauser` after the addon is deleted

---

manager/cmd/manager/main.go
manager/pkg/cronjob/task/local_compliance_history.go
manager/pkg/metrics/cronjob.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/syncres_suite_test.go
manager/pkg/specsyncer/db2transport/syncer/syncers.go
manager/pkg/specsyncer/syncers.go

Ref: https://issues.redhat.com/browse/ACM-9125

Enable metrics logs

---

operator/pkg/controllers/addon/addon_installer.go

Resolved: https://issues.redhat.com/browse/ACM-9429

Fixed the addon resourceVersion error for the updating

---

manager/pkg/statussyncer/syncers/hub_cluster_heartbeat_syncer.go
manager/pkg/statussyncer/syncers/hub_cluster_info_syncer.go
pkg/database/models/status.go

Resolve: https://issues.redhat.com/browse/ACM-9623

Fix the bug that the `deleted_at` of leaf hub info isn't removed

---

samples/config/confluent_config.go
samples/config/sarama_config.go

Fixed the sample type error

---

operator/pkg/controllers/backup/backup_reconcile.go
operator/pkg/controllers/backup/backup_start.go
operator/pkg/controllers/backup/configmap.go
operator/pkg/controllers/backup/crd.go
operator/pkg/controllers/backup/globalhub.go
operator/pkg/controllers/backup/integration_test.go
operator/pkg/controllers/backup/kafka.go
operator/pkg/controllers/backup/kafka_test.go
operator/pkg/controllers/backup/kafkatopic.go
operator/pkg/controllers/backup/kafkauser.go
operator/pkg/controllers/backup/pvc.go
operator/pkg/controllers/backup/secret.go
pkg/constants/constants.go
pkg/utils/meta.go
test/pkg/e2e/backup_test.go
test/setup/hoh/kafka/kafka-cluster/kafka-cluster.yaml

Kafka auto add "cluster.open-cluster-management.io/backup=globalhub" label to entity operator and all kafka pvcs, so we need to exclude it.

do not backup kafka pvc

---

manager/pkg/cronjob/task/data_retention.go
manager/pkg/cronjob/task/data_retention_test.go

ref: https://github.com/golang/go/issues/65397, https://github.com/golang/go/issues/57139

Fixed the month operation(addDate) incorrect with 31days

---

manager/pkg/cronjob/task/data_retention.go
manager/pkg/specsyncer/spec2db/controller/managedhub_spec_sync.go

Cleanup the heartbeat records based on the retention

---

operator/pkg/transporter/strimzi_transporter.go
operator/pkg/utils/utils.go
operator/pkg/utils/utils_test.go
test/pkg/kafka/strimzi_kafka.go
test/setup/hoh/kafka/kafka-cluster/kafka-cluster.yaml
test/setup/hoh/kafka/kafka-operator/manager/060-Deployment-strimzi-cluster-operator.yaml

refer to: https://issues.redhat.com/browse/ACM-9707

upgrade amq to 2.6.x

---

operator/pkg/controllers/hubofhubs/database/2.tables.sql
operator/pkg/controllers/hubofhubs/upgrade/1.upgrade.sql

Resolved: https://issues.redhat.com/browse/ACM-9786

Fix the sql bug for upgrading

---

operator/pkg/controllers/addon/addon_installer.go

https://issues.redhat.com/browse/ACM-9829

fix upgrade kafka user not found

---

pkg/conflator/conflation_committer.go

Remove the heartbeat log

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

ref: https://issues.redhat.com/browse/ACM-9622

add initialization-resource

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/aggregated_role.yaml
operator/pkg/controllers/hubofhubs/manifests/manager/role.yaml

ref: https://issues.redhat.com/browse/ACM-10028
Need run `make bundle` under `operator` folder to add the required permissions.

Add persistentvolumeclaims permissions

---

operator/pkg/transporter/strimzi_transporter.go
operator/pkg/transporter/strimzi_transporter_test.go

https://issues.redhat.com/browse/ACM-9788
The operator image pull secret could be specified in catalogsource.
https://olm.operatorframework.io/docs/tasks/make-catalog-available-on-cluster/#using-registry-images-that-require-authentication-as-catalogbundleoperatoroperand-images
So there is no need to set it for kafka in globalhub part.

add imagepull secret to kafka related pod

---

operator/pkg/controllers/hubofhubs/globalhub_managedhubs.go

Reference: https://issues.redhat.com/browse/ACM-9760

Remove the finalizer when uninstall the global hub

---

manager/pkg/statussyncer/hubmanagement/hub_management.go
pkg/conflator/workerpool/worker.go
pkg/database/gorm_conn.go

https://issues.redhat.com/browse/ACM-10145

fix db connnection

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

ref: https://issues.redhat.com/browse/ACM-10211

update RHACM support version

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-default-alerting.yaml

ref: https://issues.redhat.com/browse/ACM-10276

upgrade grafana to 10.3.1

---

operator/pkg/controllers/hubofhubs/globalhub_grafana.go
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-default-alerting.yaml

https://github.com/stolostron/multicluster-global-hub/issues/841

replace holder

---

doc/message.md

Format the message with cloudevent

---

pkg/conflator/workerpool/worker_pool.go

Resolved: https://issues.redhat.com/browse/ACM-10114

Fix the db work pool log 

---

pkg/transport/config/confluent_config.go

Reference: https://issues.redhat.com/browse/ACM-10642

Reduce the manager producer footprint

---

doc/simulation/inspector/src/cpu_usage.py
doc/simulation/inspector/src/memory_usage.py

If the value isn't ordered on the x-axis, then the chart is not plotted in chronological order.

Fix global hub inspector chart issue

---

operator/config/rbac/role.yaml
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/globalhub_postgres.go
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-postgres-exporter.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/dashboard-source.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/deployment.yaml
operator/pkg/controllers/hubofhubs/manifests/postgres/conf-configmap.yaml
operator/pkg/controllers/hubofhubs/manifests/postgres/postgres-alert.yaml
operator/pkg/controllers/hubofhubs/manifests/postgres/secret.yaml
operator/pkg/controllers/hubofhubs/manifests/postgres/service-monitor.yaml
operator/pkg/controllers/hubofhubs/manifests/postgres/service.yaml
operator/pkg/controllers/hubofhubs/manifests/postgres/statefulset.yaml
operator/pkg/transporter/strimzi_transporter.go

add postgres metric

---

manager/pkg/statussyncer/syncers/local_policy_complete_handler.go
manager/pkg/statussyncer/syncers/local_policy_compliance_handler_test.go
manager/pkg/statussyncer/syncers/policy_complete_handler.go
manager/pkg/statussyncer/syncers/policy_compliance_handler_test.go

Reference: https://issues.redhat.com/browse/ACM-10753

Fix the compliance handler(with all compliant)

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/metadata/annotations.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

ref: https://issues.redhat.com/browse/ACM-10727

update release channel

---

.github/pull_request_template.md
.github/workflows/go.yml

1. setup a pull request template
2. introduce github action to verify the code

Setup github action for verify

---

.github/workflows/go.yml
Makefile
operator/main_test.go
pkg/bundle/version/version.go
pkg/constants/constants.go
pkg/database/dao/generic_dao.go
pkg/database/gorm_conn_test.go
pkg/transport/consumer/generic_consumer.go
pkg/transport/consumer/sarama_consumer.go
pkg/transport/kafka_confluent/option.go
pkg/transport/kafka_confluent/protocol.go
pkg/transport/producer/generic_producer.go
pkg/utils/utils.go
test/pkg/e2e/backup_test.go
test/pkg/kafka/mocksaram.go

fix github actions to run `make strict-fmt`
Fixes #

:bug: Fix default folder

---

manager/pkg/statussyncer/syncers/local_policy_compliance_handler.go
manager/pkg/statussyncer/syncers/local_policy_compliance_handler_test.go
manager/pkg/statussyncer/syncers/policy_compliance_handler.go

Reference: https://issues.redhat.com/browse/ACM-10798

Fix the bug that manager might cleanup compliance after it restart

---

.github/workflows/go.yml
operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/bundle/metadata/annotations.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml

Introduce `make bundle` to avoid forgetting to update the bundle.
Fixes #

:sparkles: Verify bundle

---

operator/pkg/controllers/hubofhubs/globalhub_config.go
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/globalhub_kafka_controller.go
operator/pkg/controllers/hubofhubs/globalhub_middleware.go

Cannot create kafka by default.
Fixes #

:bug: Cannot create kafka

---

manager/cmd/manager/main.go
manager/pkg/backup/backup_intergration_test.go
manager/pkg/backup/pvc_controller.go
manager/pkg/nonk8sapi/util/crd.go
manager/pkg/nonk8sapi/util/until.go
manager/pkg/specsyncer/db2transport/syncer/dbsyncer/generic_db_to_transport_syncer.go
manager/pkg/statussyncer/syncers/managed_clusters_syncer.go
manager/pkg/statussyncer/syncers/policy_compliance_handler.go
operator/main_test.go
operator/pkg/controllers/backup/backup_start.go
operator/pkg/controllers/hubofhubs/globalhub_grafana.go
operator/pkg/utils/utils.go
pkg/bundle/cluster/hub_cluster_heartbeat_bundle.go
pkg/bundle/metadata/bundle_version.go
pkg/constants/constants.go
pkg/database/gorm_conn_test.go
pkg/transport/config/confluent_config.go
pkg/transport/consumer/generic_consumer.go

Limit the channel size of the producer and consumer
Fixes # https://issues.redhat.com/browse/ACM-10814

:bug: [ Release - 2.10 ] Reduce the footprint of the transporter

---

operator/pkg/controllers/hubofhubs/integration_test.go

Add checking for strimzi subscription. it is a follow up PR for #875 
Fixes #

Check strimiz subscription in integration test

---

agent/pkg/status/controller/placement/integration_test.go
agent/pkg/status/controller/placement/placement_decision_syncer.go
agent/pkg/status/controller/placement/placement_rule_syncer.go
agent/pkg/status/controller/placement/placement_syncer.go

We will only enable the placement/placementrule/placementdecision for global resources and disable them for local resource
Fixes #

Enable placement syncers for global resouces

---

agent/pkg/status/controller/event/local_root_policy_emitter.go
manager/pkg/statussyncer/syncers/local_policy_compliance_handler.go
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-adhoc-investigation.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-policies.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-overview.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-whats-changed-policies.yaml

1. change the color of pending policy
2. fix the pending policy status lost in db.
Fixes #
https://issues.redhat.com/browse/ACM-11172

:bug: fix some pending policy

---

manager/pkg/nonk8sapi/authentication/authentication.go
manager/pkg/specsyncer/db2transport/db/postgresql/postgresql.go
manager/pkg/specsyncer/spec2db/controller/generic_spec_to_db_reconciler.go
pkg/database/pgx_conn.go
pkg/utils/meta.go

Ignore the sonar issue.		
`InsecureSkipVerify: true, // #nosec G402`
https://github.com/securego/gosec?tab=readme-ov-file#annotating-code
https://github.com/stolostron/multicluster-global-hub/issues/896
Fixes #

:bug: fix sonar issues

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-strimzi-kafka.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-strimzi-operator.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-strimzi-zookeeper.yaml

Some enhancement for kafka related dashaboards

:bug: update the kafka dashboards

---

operator/pkg/controllers/hubofhubs/integration_test.go

fix ut not stable

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-strimzi-operator.yaml

update kafka dashboard 

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/controllers/hubofhubs/globalhub_postgres.go
operator/pkg/controllers/hubofhubs/manifests/postgres/statefulset.yaml

Use the postgres downstream image 
https://issues.redhat.com/browse/ACM-10597
Fixes #

use postgres downstream image

---

doc/simulation/backup_restore/backupenv.sh
doc/simulation/backup_restore/restoreenv.sh

update backup script

---

operator/pkg/controllers/addon/addon_installer.go
operator/pkg/controllers/hubofhubs/globalhub_middleware.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/transporter/byo_transporter.go
operator/pkg/transporter/strimzi_transporter.go
operator/pkg/transporter/strimzi_transporter_test.go
pkg/transport/transport.go

As we discussed in meeting, we should update the topic replica to 3.
Fixes #

update topic replica to 3

---

doc/simulation/backup_restore/backupenv.sh
doc/simulation/backup_restore/restoreenv.sh

This reverts commit aa6e42a56b48cd0cebab4f38801193900b6a4849.
Fixes #

Revert "update backup script (#912)"

---

operator/apis/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml

Fixes # See Jira: https://issues.redhat.com/browse/ACM-9275

added doc review to global hub api descriptions

---

agent/cmd/agent/main.go
agent/pkg/config/agent_config.go
manager/cmd/manager/main.go
manager/pkg/config/manager_config.go
operator/main.go
operator/pkg/config/operator_config.go
operator/pkg/controllers/addon/addon_controller.go
operator/pkg/controllers/addon/addon_controller_manifests.go
operator/pkg/controllers/addon/addon_suite_test.go
operator/pkg/controllers/addon/manifests/templates/agent/multicluster-global-hub-agent-deployment.yaml
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/globalhub_database.go
operator/pkg/controllers/hubofhubs/globalhub_manager.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/controllers/hubofhubs/manifests/manager/deployment.yaml
operator/pkg/controllers/hubofhubs/suite_test.go
pkg/utils/pprof.go

Add the pprof tool options for footprint investigate
Fixes # https://github.com/stolostron/multicluster-global-hub/pull/849

:sparkles: Add pprof option for global hub components

---

doc/simulation/scenario/Scenario3: 3000_clusters_500_policies.md
doc/simulation/scenario/Scenario4: kafka_metrics.md

:book: Patch the simulation documents

---

manager/pkg/cronjob/task/data_retention.go

Blocked by: https://github.com/stolostron/multicluster-global-hub/pull/911
Fixes # https://issues.redhat.com/browse/ACM-11542

:sparkles: Create/Delete cluster events partition table by the rentetion job

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml

:bug: fix postgres image

---

operator/pkg/controllers/hubofhubs/database/1.schemas.sql
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-postgres-exporter.yaml

https://issues.redhat.com/browse/ACM-11329
Fixes #

add some performance dashboard for psotgres

---

agent/cmd/agent/main.go

Fix the bug that event is missing from the database.
Fixes #

:bug: Update the agent cache filter for cluster event

---

operator/pkg/controllers/crd/crd_controller.go

The race condition exists in the operator crd controllers. It might through error with:
```bash
☁  multicluster-global-hub [br_cache_filter] ⚡  oc logs -f -l name=multicluster-global-hub-operator -n multicluster-global-hub
2024-05-16T23:46:16.868Z        INFO    setup   Go Version: go1.21.10
2024-05-16T23:46:16.868Z        INFO    setup   Go OS/Arch: linux/amd64
2024-05-16T23:46:16.895Z        INFO    setup   starting manager
2024-05-16T23:46:16.895Z        INFO    controller-runtime.metrics      Starting metrics server
2024-05-16T23:46:16.896Z        INFO    starting server {"kind": "health probe", "addr": "[::]:8081"}
2024-05-16T23:46:16.896Z        INFO    controller-runtime.metrics      Serving metrics server  {"bindAddress": ":8080", "secure": false}
I0516 23:46:16.896212       1 …
```

:bug: The operator crd maps concurrent error

---

pkg/transport/producer/generic_producer.go

Fixes # https://github.com/open-cluster-management-io/sdk-go/pull/44

:seedling: Ignore the all broker is down error for producer client

---

doc/reserved_names/README.md
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/globalhub_metrics.go
operator/pkg/controllers/hubofhubs/globalhub_prune.go
operator/pkg/controllers/hubofhubs/globalhub_prune_test.go
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-postgres-exporter.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-strimzi-kafka.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-strimzi-operator.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-strimzi-zookeeper.yaml
operator/pkg/controllers/hubofhubs/manifests/kafka/metrics.yaml
operator/pkg/controllers/hubofhubs/manifests/kafka/podmonitor.yaml
operator/pkg/controllers/hubofhubs/manifests/postgres/postgres-alert.yaml
operator/pkg/controllers/hubofhubs/manifests/postgres/service-monitor.yaml
pkg/constants/constants.go

:bug: clean up metric resource when disable metrics

---

agent/pkg/status/controller/event/managedcluster_emitter_test.go
pkg/database/gorm_conn.go
test/pkg/e2e/clusterlabel_test.go
test/pkg/e2e/suite_test.go

Fixes # https://issues.redhat.com/browse/ACM-11690

:seedling:  mock cluster event for e2e test

---

operator/pkg/transporter/strimzi_transporter.go

:bug: update kafka replica to 3 by default

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-postgres-tables.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-postgres.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/deployment.yaml

:sparkles:add postgrestable dashboard

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-managedclusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/dashboard-source.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/deployment.yaml

:sparkles: add cluster dashboard

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-managedclusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-postgres-tables.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-postgres.yaml

https://issues.redhat.com/browse/ACM-11889
Fixes #

:sparkles: add dev-preview and technical preview tag

---

operator/pkg/controllers/hubofhubs/globalhub_kafka_controller.go
operator/pkg/controllers/hubofhubs/globalhub_middleware.go
operator/pkg/transporter/strimzi_transporter.go

1. We do not watch mgh in kafka controller.
2. We should get the latest mgh in kafka controller.
https://issues.redhat.com/browse/ACM-11866
https://issues.redhat.com/browse/ACM-11754
Fixes #

:bug: fix kafka reconcile logic

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-managedclusters.yaml

https://issues.redhat.com/browse/ACM-11890

:sparkles: add version filter "> < =" in cluster dashboard

---

doc/simulation/local-policies/README.md
doc/simulation/local-policies/history_local_compliance.sql

:sparkles: add generate history.local_compliance data script

---

doc/simulation/scenario/Scenario5: postgres_metrics.md

:bug: fix postgres metric doc title

---

operator/apis/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml

https://issues.redhat.com/browse/ACM-11627
Fixes #

:bug: update enablemetrics description

---

manager/pkg/nonk8sapi/authentication/authentication.go
pkg/database/pgx_conn.go

fix soner go sec issue

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-adhoc-investigation.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-managedclusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-postgres.yaml

:bug: change default time of dashboards

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-postgres.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-strimzi-kafka.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-strimzi-operator.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-strimzi-zookeeper.yaml

https://issues.redhat.com/browse/ACM-11598
Fixes #

:bug: fix some dashboard error

---

agent/pkg/status/controller/event/local_replicated_policy_emitter.go
agent/pkg/status/controller/policies/status_event_emitter.go
doc/events-api.md
manager/pkg/cronjob/task/local_compliance_history_test.go
manager/pkg/statussyncer/syncers.go
manager/pkg/statussyncer/syncers/local_replicated_policy_event_handler.go
manager/pkg/statussyncer/syncers/local_replicated_policy_event_handler_test.go
manager/pkg/statussyncer/syncers/local_root_policy_event_handler.go
manager/pkg/statussyncer/syncers/local_root_policy_event_handler_test.go
operator/pkg/controllers/hubofhubs/database/2.tables.sql
operator/pkg/controllers/hubofhubs/upgrade/1.upgrade.sql
pkg/bundle/event/policy_event_bundle.go
pkg/database/models/event.go
pkg/enum/event_type.go

Fixes #https://issues.redhat.com/browse/ACM-11622

:bug: Update event api

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-adhoc-investigation.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-clusters.yaml
operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-offending-policies.yaml

https://issues.redhat.com/browse/ACM-12015
Fixes #

:bug: fix date farmat

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-postgres.yaml

:bug: add tp in postgres dashboard

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/globalhub_prune.go
operator/pkg/controllers/hubofhubs/globalhub_prune_test.go

https://issues.redhat.com/browse/ACM-10754

:bug: clean strimi resources when delete mgh

---

test/pkg/e2e/suite_test.go
test/setup/common.sh
test/setup/e2e_setup.sh
test/setup/resource/kafka/kafka-cluster/kafka-topics.yaml
test/setup/resource/kafka/kafka-cluster/kafka-user.yaml
test/setup/resource/kafka/kafka_setup.sh
test/setup/resource/postgres/postgres_setup.sh

Fixes # https://github.com/stolostron/multicluster-global-hub/pull/957

:bug: wait the kafka users and topics are ready

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

use `amq-streams-cluster-operator-v2.6.0-2-f49bf7559-569mw` instead of `strimzi-cluster-operator-v0.36.1-684d7cccb7-zjbf9`
Fixes #

:bug: update bundle with latest

---

manager/pkg/statussyncer/syncers/local_replicated_policy_event_handler.go
manager/pkg/statussyncer/syncers/local_root_policy_event_handler.go

Fixes # https://issues.redhat.com/browse/ACM-11992

:bug:  Add source value for the policy event

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

https://issues.redhat.com/browse/ACM-11627
Fixes #

fix enablemetrics csv description

---

operator/pkg/controllers/hubofhubs/manifests/grafana/acm-global-managedclusters.yaml

update managedcluster view dashboard

---

operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-managedclusters.yaml

https://issues.redhat.com/browse/ACM-12303
Fixes #

fix clusteroverview dashboard error with no data

---

operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go

I try to use make deploy to deploy globalhub env, but the kafka related resources can not be created.
Fixes #

kafka can not be deployed in latest env

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/config/rbac/role.yaml
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/config/multiclusterglobalhub_config_test.go
operator/pkg/config/scheme_config.go
operator/pkg/controllers/hubofhubs/globalhub_controller.go
operator/pkg/controllers/hubofhubs/globalhub_grafana.go
operator/pkg/controllers/hubofhubs/globalhub_manager.go
operator/pkg/controllers/hubofhubs/integration_test.go
operator/pkg/controllers/hubofhubs/suite_test.go
pkg/testdata/crds/0000_06_config.openshift.io_clusterversions.crd.yaml
test/e2e/suite_test.go
test/script/e2e_setup.sh
test/script/util.sh

Reference: https://github.com/stolostron/multiclusterhub-operator/pull/778
Fixes #

[ Release 2.11 ] upgrade oauth proxy for ocp4.16+

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/pkg/config/multiclusterglobalhub_config.go
test/script/util.sh

Fixes # https://issues.redhat.com/browse/ACM-12539

:sparkles: Use grafana 11.1.0

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

Remove the concrete ACM version to avoid modify each release. Just ask the customer to look it from the official document
Fixes #

:bug: Remove the concrete ACM version

---

operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go

Fixes # https://github.com/stolostron/multicluster-global-hub/pull/1009

fix the kafka upgrade

---

.github/workflows/go.yml
agent/Dockerfile
go.mod
manager/Dockerfile
operator/Dockerfile
test/script/util.sh

https://issues.redhat.com/browse/ACM-12541
Fixes #

upgrade golang to 1.22

---

test/script/e2e_kafka.sh
test/script/e2e_setup.sh

the built-in Kafka will cover the certificate signing for each managed hub
Fixes #

enable built-in kafka for the global hub

---

test/e2e/grafana_test.go

https://github.com/stolostron/multicluster-global-hub/issues/1026
Fixes #

fix grafana test error

---

.tekton/multicluster-global-hub-agent-globalhub-1-3-pull-request.yaml
.tekton/multicluster-global-hub-agent-globalhub-1-3-push.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-3-pull-request.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-3-push.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-3-pull-request.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-3-push.yaml

onboard konflux on main branch by following this document: https://docs.google.com/document/d/1SWKV-9xBYKx6qIQZrJv58yP34s5LMh-pXbOx9BoJiKI/edit#heading=h.u2orph60mc1u
Fixes #

:sparkles: Onboard konflux to main

---

pkg/database/pgx_conn.go

https://github.com/stolostron/multicluster-global-hub/issues/896
Fixes #

fix sonar issue

---

.tekton/multicluster-global-hub-agent-globalhub-1-3-pull-request.yaml
.tekton/multicluster-global-hub-agent-globalhub-1-3-push.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-3-pull-request.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-3-push.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-3-pull-request.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-3-push.yaml
agent/Containerfile.operator
manager/Containerfile.operator
operator/Containerfile.operator

Fixes https://issues.redhat.com/browse/ACM-12399

Introudce Containerfile.operator for Productized build

---

operator/pkg/controllers/crd/crd_controller.go
operator/pkg/controllers/hubofhubs/controller.go

In our e2e, there is no imagestream api available. Watch an unavailable API should throw error so that the controller cannot continue reconciling others.
Fixes #

Ensure imagestream api before watching

---

test/Makefile
test/script/e2e_log.sh
test/script/e2e_prow.sh

E2E logs for the operator and manager

---

operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/controllers/addon/addon_controller.go
operator/pkg/controllers/hubofhubs/controller.go
operator/pkg/utils/utils.go

We should always use the same addon manager(which adds the addon agent) to update the manifests. Otherwise, it might not be triggerred to update
Fixes # https://github.com/open-cluster-management-io/addon-framework/issues/281

:bug: Update the manifestwork with addon manager

---

operator/apis/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml

Fixes # https://github.com/stolostron/multicluster-global-hub/pull/1046

Update the topic comment of the API

---

operator/pkg/controllers/addon/addon_controller.go

Fixes # https://issues.redhat.com/browse/ACM-13198

:bug: Remove the registration for the BYO case

---

operator/pkg/controllers/hubofhubs/controller.go
operator/pkg/controllers/hubofhubs/status/status_reconciler.go

Fixes https://issues.redhat.com/browse/ACM-13124

:bug: Update the mgh status for the deployment

---

operator/pkg/controllers/hubofhubs/storage/storage_reconciler.go

Fixes #https://issues.redhat.com/browse/ACM-13122

:bug: hidden database password in log

---

pkg/transport/config/confluent_config.go
samples/cloudevent/confluent-receiver/main.go
samples/cloudevent/confluent-sender/main.go
samples/config/confluent_config.go

update cloudevents samples

---

operator/pkg/controllers/hubofhubs/controller.go
operator/pkg/controllers/hubofhubs/controller_test.go
operator/pkg/controllers/hubofhubs/transporter/protocol/byo_transporter.go
operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_kafka_controller.go
operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
operator/pkg/controllers/hubofhubs/transporter/transport_reconciler.go
pkg/transport/transport.go
test/integration/operator/hubofhubs/transporter_test.go

1. Cannot create the kafka instance from scratch
2. avoid to use `wait.PollUntilContextTimeout` in reconcile method, it will create multiple times with timeout. 
Fixes #

:bug: initialize kafka

---

test/manifest/kafka/kafka-cluster/kafka-byo-resource.yaml
test/script/e2e_kafka.sh
test/script/e2e_log.sh
test/script/e2e_setup.sh

Fixes #
Reference: https://github.com/stolostron/multicluster-global-hub/pull/1071

:bug: BYO for e2e

---

operator/Makefile
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/config/multiclusterglobalhub_config_test.go
operator/pkg/controllers/addon/addon_controller_manifests.go
operator/pkg/controllers/addon/addon_installer.go
operator/pkg/controllers/addon/addon_installer_test.go
operator/pkg/controllers/crd/crd_controller.go
operator/pkg/controllers/crd/crd_controller_test.go
operator/pkg/controllers/hubofhubs/controller.go
operator/pkg/controllers/hubofhubs/prune/prune_reconciler.go
operator/pkg/controllers/hubofhubs/prune/prune_reconciler_test.go
operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_kafka_controller.go
operator/pkg/utils/utils_test.go
test/integration/operator/hubofhubs/controller_test.go
test/integration/operator/hubofhubs/grafana_test.go
test/integration/operator/hubofhubs/manager_test.go
test/integration/operator/hubofhubs/metrics_test.go
test/integration/operator/hubofhubs/storage_test.go
test/integration/operator/hubofhubs/transporter_test.go
test/integration/utils/utils.go

kafkatopic should be deleted before the kafkaoperator.
https://issues.redhat.com/browse/ACM-13119
Fixes #

fix kafkatopic can not be deleted

---

operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/pkg/config/transport_config.go
pkg/transport/type.go
test/integration/operator/hubofhubs/transporter_test.go
test/manifest/kafka/kafka-cluster/kafka-byo-resource.yaml
test/manifest/kafka/kafka-cluster/kafka-topics.yaml
test/manifest/kafka/kafka-cluster/kafka-user.yaml
test/script/e2e_kafka.sh

Related: https://github.com/stolostron/rhacm-docs/pull/6805

Switch the default topic name from `gh-event`  to `gh-status`

---

operator/pkg/controllers/addons/addons_controller.go
operator/pkg/controllers/addons/addons_controller_test.go

fix issue about importing hosted hub

---

operator/pkg/certificates/cert_controller.go
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/config/storage_config.go
operator/pkg/controllers/hubofhubs/inventory/inventory_reconciler.go

1. use stolostron/grafana image which is the same version as glo-grafana
2. fix integration test issue to pass the kubeclient in
Fixes #

:bug: Use stolostron grafana image

---

operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
test/manifest/kafka/kafka-cluster/kafka-cluster.yaml
test/script/e2e_kafka.sh
test/script/util.sh

:memo: Use KRaft for BYO e2e

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/pkg/constants/constants.go
operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
test/Makefile
test/e2e/backup_test.go
test/e2e/suite_test.go
test/manifest/crd/0000_03_config-operator_01_proxies.crd.yaml
test/script/e2e_clean_globalhub.sh
test/script/e2e_kafka.sh
test/script/e2e_postgres.sh
test/script/e2e_run.sh
test/script/e2e_run_byo.sh
test/script/e2e_setup.sh
test/script/util.sh

https://issues.redhat.com/browse/ACM-13318
Fixes #

run e2e using default middleware and byo middleware

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/pkg/constants/constants.go
operator/pkg/controllers/hubofhubs/inventory/inventory_reconciler.go
operator/pkg/controllers/hubofhubs/inventory/manifests/deployment.yaml
operator/pkg/controllers/hubofhubs/inventory/manifests/kafka-certs.yaml
operator/pkg/controllers/hubofhubs/inventory/manifests/secret.yaml
operator/pkg/controllers/hubofhubs/transporter/protocol/manifests/global-hub-kafka.yaml
operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
test/kessel_e2e/setup/e2e_setup.sh

:sparkles: Wire inventory to Kafka

---

operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-adhoc-investigation.yaml
operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-managedclusters.yaml
operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-offending-clusters.yaml
operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-offending-policies.yaml
operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-overview.yaml
operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-whats-changed-clusters.yaml
operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-whats-changed-policies.yaml

https://issues.redhat.com/browse/ACM-13345
Test cases:
install the globalhub, and check all the dashboard, make sure all the key word changed.

change compliance keyword to violiation

---

operator/pkg/controllers/hubofhubs/grafana/manifests/acm-global-postgres.yaml

https://issues.redhat.com/browse/ACM-12591
Fixes #

:bug: fix postgres dashboard format error

---

operator/pkg/controllers/hubofhubs/transporter/protocol/manifests/global-hub-kafka-topic.yaml
operator/pkg/controllers/hubofhubs/transporter/protocol/manifests/global-hub-kafka-user.yaml
operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go

Need to create `kessel-inventory` topic and grant the permission to global hub user.
Fixes #

:bug: Create inventory topic

---

.github/pull_request_template.md

Update pull request template to remind the tests

---

agent/pkg/status/controller/filter/time_filter.go
agent/pkg/status/controller/filter/time_filter_test.go
agent/pkg/status/controller/policies/status_event_emitter.go
test/integration/agent/status/localpolicy_event_test.go

Fixes # https://issues.redhat.com/browse/ACM-14262

:bug: Fix the issue of event loss caused by time filtering.

---

test/script/util.sh

Fixes # https://github.com/stolostron/multicluster-global-hub/issues/1031

:bug: e2e kind cluster creating error

---

doc/dev-preview.md

The levels of the sections are incorrect, this patch fixes them.
https://issues.redhat.com/browse/ACM-14143
https://issues.redhat.com/browse/MGMT-18591

ACM-14143: Fix section levels in StackRox integration doc

---

operator/pkg/controllers/hubofhubs/webhook/manifests/addondeploymentconfig.yaml

https://issues.redhat.com/browse/ACM-14314
Fixes #

fix install hosted in other ns

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/samples/global_hub_v1alpha1_managedclustermigration.yaml
operator/config/samples/kustomization.yaml

provided an example annotation for new API - managedclustermigration
Fixes # CVP issue
```
{
"kind": "Test",
"apiVersion": "scorecard.operatorframework.io/v1alpha3",
"spec": {
"image": "quay.io/operator-framework/scorecard-test:v1.19.1",
"entrypoint": [
"scorecard-test",
"olm-bundle-validation"
],
"labels": {
"suite": "olm",
"test": "olm-bundle-validation-test"
},
"storage": {
"spec": {
"mountPath": {}
}
}
},
"status": {
"results": [
{
"name": "olm-bundle-validation",
"log": "time=\"2024-09-19T15:35:41Z\" level=debug msg=\"Found manifests directory\" name=bundle-test\ntime=\"2024-09-19T15:35:41Z\" level=debug msg=\"Found metadata directory\" name=bundle-test\ntime=\"2024-09-19T15:35:41Z\" level=debug msg=\"Getting mediaType info from manifests directory\" …
```

:bug:  Add managedclustermigration example

---

Makefile
go.mod
go.sum
manager/Containerfile.operator
manager/Dockerfile
manager/cmd/manager/main.go
manager/pkg/config/manager_scheme.go
manager/pkg/migration/migration_controller.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
operator/pkg/controllers/hubofhubs/controller.go
operator/pkg/controllers/hubofhubs/manager/manifests/clusterrole.yaml
pkg/constants/constants.go
test/integration/manager/controller/backup_test.go
test/integration/manager/controller/migration_test.go
test/integration/manager/controller/suite_test.go
test/manifest/crd/0000_06_authentication.open-cluster-management.io_managedserviceaccounts.crd.yaml

Have a migration controller to reconcile the managedclustermigation CR

---

operator/pkg/controllers/addons/addons_controller.go

Fixes #
Manually tested it in QE env

fix default ns in hosted mode

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/pkg/config/multiclusterglobalhub_config.go

Use inventory api community image and enable the midstream replacement.
Fixes #
- Tested by management inventory team

:sparkles: Use inventory api community image

---

operator/pkg/controllers/crd/crd_controller.go
test/e2e/cluster_test.go

https://issues.redhat.com/browse/ACM-13443
Fixes #
manually test the update and create managedcluster, the annotations will be added.

fix managedcluster watch do not work

---

operator/pkg/config/condition.go
operator/pkg/controllers/hubofhubs/prune/prune_reconciler.go

1. if install global hub without ACM, it throws error during un-installing so that cannot uninstall GH
2. correct message
Fixes #

Fix uninstall error

---

agent/pkg/spec/controller/controller.go
agent/pkg/spec/controller/syncers/clusterlabel_syncer.go
agent/pkg/spec/controller/syncers/dispatcher.go
agent/pkg/spec/controller/syncers/generic_syncer.go
agent/pkg/spec/controller/syncers/interface.go
agent/pkg/spec/controller/syncers/migration_from_syncer.go
agent/pkg/spec/controller/syncers/migration_from_syncer_test.go
agent/pkg/spec/controller/syncers/migration_to_syncer.go
agent/pkg/spec/controller/syncers/migration_to_syncer_test.go
agent/pkg/spec/controller/syncers/resync_syncer.go
manager/pkg/migration/migration_controller.go
pkg/constants/constants.go
test/integration/manager/controller/migration_test.go

Follow up PR for #1111 
To address:
- cannot create msa when delete msa
- update the clusterrole and clusterrolebinding in the MigrationTo hub

enhance managedcluster migration controller and syncers.

---

agent/pkg/spec/controller/syncers/migration_from_syncer.go
agent/pkg/spec/controller/syncers/migration_from_syncer_test.go
go.sum

clean up managed clusters after migration is done. 
Fixes #
/hold

clean up managed clusters after migration is done. 

---

operator/pkg/controllers/hubofhubs/controller.go

https://issues.redhat.com/browse/ACM-14541
Fixes #

fix unintall panic

---

manager/pkg/migration/migration_controller.go
test/integration/manager/controller/migration_test.go
test/integration/manager/controller/suite_test.go

This pull request introduces the ability to query the migration.from hub in the database.
Fixes #

allow to query migration.from hub in database.

---

operator/pkg/controllers/crd/crd_controller.go

rove lock in crd controller

---

operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter.go
operator/pkg/controllers/hubofhubs/transporter/protocol/strimzi_transporter_test.go
operator/pkg/controllers/status/status_reconciler.go
operator/pkg/controllers/status/status_reconciler_test.go
test/e2e/suite_test.go

fix kafka components status

---

.tekton/multicluster-global-hub-agent-globalhub-1-3-pull-request.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-3-pull-request.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-3-pull-request.yaml

:seedling: Update Konflux to use release-2.12 branch

---

operator/pkg/utils/utils.go

fix annotation did not added

---

agent/pkg/status/controller/security/stackrox_syncer.go
test/integration/manager/status/security_alert_counts_handler_test.go

Use one version object throughout `stackrox` syncing and increment it accordingly.

:bug: Increment version in stackrox syncer

---

doc/dev-preview.md

🐛 remove the strimiz and postgresql metrics from dev-preview doc

---

agent/pkg/status/status.go

:seedling: Disable the agent heart beat in the standalone mode

---

Makefile
agent/Dockerfile
manager/Dockerfile
operator/Dockerfile
pkg/utils/utils.go

Need to update the downstream build
Fixes # https://github.com/stolostron/multicluster-global-hub/issues/1115

:sparkles: Add git commit to the to the images

---

operator/pkg/controllers/hubofhubs/webhook/manifests/placement.yaml

Fixes # https://issues.redhat.com/browse/ACM-14443

:bug: fix the issue of ACM-14443

---

doc/dev-preview.md

:book: Managed cluster migration

---

doc/troubleshooting.md

https://github.com/stolostron/multicluster-global-hub/issues/1178
https://github.com/stolostron/multicluster-global-hub/pull/1184
https://github.com/stolostron/multicluster-global-hub/pull/1185
Fixes #

:book: Add the document to adjust the log level 

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/metadata/annotations.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

fix operator-accidental-unpublishing-of-released-operators-bundle-image problem:
http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/multicluster-globalhub-operator-bundle-container-v1.4.0-5/81eca2fe-1525-40f9-9913-530c15880a81/operator-accidental-unpublishing-of-released-operators-bundle-image-output.txt
Fixes #

:bug: Bump to 1.4.0

---

test/integration/operator/controllers/storage_test.go

fix intergration

---

test/script/util.sh

cherry-pick from #1204
Fixes #

:bug: Fix e2e issue

---

test/script/util.sh

:bug: Fix the e2e error

---

test/integration/agent/status/localpolicy_event_test.go

Fix the local policy event issue in integration test

---

Makefile
operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

Bump to v1.3.1
Fixes # 
[http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation[…]g-of-released-operators-bundle-image-output.txt](http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/multicluster-globalhub-operator-bundle-container-v1.3.1-2/47af7b93-7ace-4e33-9b8e-b014c24c7e52/operator-accidental-unpublishing-of-released-operators-bundle-image-output.txt)

:sparkles: Bump to v1.3.1

---

test/e2e/suite_test.go

In e2e, we must make sure the operator get the lease, then create the mgh.
Fixes #

create mgh after operator started in e2e

---

agent/pkg/status/controller/managedclusters/managed_cluster_info_syncer.go
agent/pkg/status/controller/policies/policy_controller.go

manually cherry-pick https://github.com/stolostron/multicluster-global-hub/pull/1172
Fixes # [ACM-15526](https://issues.redhat.com/browse/ACM-15526)

Fix multiple creation events

---

.github/dependabot.yml

:sparkles: Introduce dependabot

---

test/script/e2e_cleanup.sh

:bug: Correct the cleanup command

---

.github/dependabot.yml

It is too noisy to update go.mod daily. move it to weekly
Fixes #

Update dependabot frequence

---

go.mod
manager/cmd/main.go
manager/pkg/configs/scheme.go
manager/pkg/processes/hubmanagement/hub_addon_controller.go
manager/pkg/processes/hubmanagement/hub_addon_controller_test.go
manager/pkg/processes/hubmanagement/hub_management.go
operator/pkg/config/addon_config.go
operator/pkg/constants/constants.go
operator/pkg/controllers/agent/addon_manager.go
operator/pkg/controllers/agent/default_agent_controller.go
operator/pkg/controllers/agent/default_agent_controller_test.go
operator/pkg/controllers/agent/hosted_agent_controller.go
operator/pkg/controllers/agent/hosted_agent_controller_test.go
operator/pkg/controllers/manager/manifests/clusterrole.yaml
operator/pkg/utils/utils_test.go
pkg/constants/constants.go
test/e2e/cluster_test.go
test/integration/operator/controllers/agent/cluster_default_addon_test.go
test/integration/operator/controllers/agent/cluster_hosted_addon_test.go

Fixes # https://issues.redhat.com/browse/ACM-14959

:bug: Inactive the managed hub by addon

---

go.mod
operator/pkg/controllers/agent/default_agent_controller.go
operator/pkg/utils/utils.go
operator/pkg/utils/utils_test.go
test/e2e/suite_test.go

remove wait logic in operator

---

.webui_secret_key
manager/pkg/processes/hubmanagement/hub_management.go

:bug: Add addon controller to the hub management 

---

manager/pkg/processes/cronjob/scheduler.go
test/integration/manager/controller/scheduler_test.go

https://issues.redhat.com/browse/ACM-15524
Fixes #
manually test it, and the metrics created.

fix metric lost

---

agent/pkg/configs/scheme.go
agent/pkg/controllers/init_controller.go
agent/pkg/spec/spec.go
agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_from_syncer_test.go
agent/pkg/spec/syncers/migration_to_syncer.go
agent/pkg/spec/syncers/migration_to_syncer_test.go
manager/pkg/configs/scheme.go
manager/pkg/controllers/migration_controller.go
manager/pkg/status/conflator/conflation_priority.go
manager/pkg/status/handlers/handlers.go
manager/pkg/status/handlers/managedcluster/klusterlet_addon_config_handler.go
manager/pkg/status/handlers/managedcluster/klusterlet_addon_config_handler_test.go
manager/pkg/status/status.go
operator/pkg/controllers/agent/manifests/templates/agent/multicluster-global-hub-agent-clusterrole.yaml
pkg/bundle/event/managedcluster_migration_event.go
pkg/constants/constants.go
pkg/enum/event_type.go
pkg/transport/controller/controller.go
test/integration/agent/spec/suite_test.go

:sparkles: Put klusterletaddonconfig into managedclustermigration CR

---

operator/pkg/controllers/storage/storage_reconciler.go

print database error

---

agent/Containerfile.operator
manager/Containerfile.operator
operator/Containerfile.operator

https://github.com/stolostron/multicluster-global-hub/issues/1115
Fixes #

:seedling: Add git commit to downstream images

---

operator/pkg/controllers/grafana/manifests/acm-global-strimzi-kraft.yaml
operator/pkg/controllers/grafana/manifests/deployment.yaml

Kraft-dashboard: 
Kafka-dashboard(removed zookeeper related pannel):
https://issues.redhat.com/browse/ACM-16108
Fixes #

Add kraft dashboard and update kafka dashboard (#1270)

---

.tekton/multicluster-global-hub-agent-globalhub-1-4-pull-request.yaml
.tekton/multicluster-global-hub-agent-globalhub-1-4-push.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-4-pull-request.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-4-push.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-4-pull-request.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-4-push.yaml

Containerfile.operator is designed for Konflux.
Fixes #

Use Containerfile.operator in Konflux build

---

agent/pkg/status/filter/time_filter.go
test/integration/agent/status/localpolicy_event_test.go

:bug: not received event for the agent status integartion test

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

:seedling: Bump version to 1.3.2

---

operator/Makefile
operator/bundle/konflux-patch.sh
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml

Remove `relatedImages` for CPaaS build
Fixes #

:bug: remove relatedImages

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

Fixes # https://issues.redhat.com/browse/ACM-16807

Remove redundant annotations

---

agent/pkg/status/controller/managedclusters/managed_cluster_info_syncer.go

missed using clusterId in https://github.com/stolostron/multicluster-global-hub/pull/1291. refer to https://github.com/stolostron/multicluster-global-hub/pull/1290
Fixes #

Use passed clusterId

---

test/script/e2e_setup.sh
test/script/util.sh

Sometimes, the KinD cluster creation is failed. it will keep trying all the time without exit. 
Fixes #
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stolostron_multicluster-global-hub/1311/pull-ci-stolostron-multicluster-global-hub-main-test-e2e/1876137001376288768

Delete the container forcely

---

.github/workflows/go.yml
operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
test/script/util.sh

Bump version to 1.2.1 to fix the CVE issues
Fixes #

Bump version to 1.2.1

---

doc/README.md
doc/global_hub_builtin_postgresql.md

Fixes #https://issues.redhat.com/browse/ACM-16818, https://issues.redhat.com/browse/ACM-16887

:book: Add the document for the pg feature and configuration

---

operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml

use lowercase for installAgentOnLocal

---

tools/generate-kafka-config.sh

:sparkles: generate kafka config script

---

doc/simulation/inspector/src/cpu_usage.py
doc/simulation/inspector/src/memory_usage.py
doc/simulation/inspector/src/pvc_usage.py
doc/simulation/setup/README.md

Fixes # https://issues.redhat.com/browse/ACM-16109

:seedling: Correct the simulation scripts to align with the kraft mode

---

manager/pkg/status/conflator/workerpool/worker.go
manager/pkg/status/handlers/managedcluster/managedcluster_event_handler.go
manager/pkg/status/handlers/managedcluster/managedcluster_handler.go

Fixes # https://github.com/stolostron/multicluster-global-hub/issues/1334

:bug: Fix the performance issue in high-scale tests

---

doc/global_hub_builtin_postgresql.md
operator/pkg/constants/constants.go
operator/pkg/controllers/storage/postgres_statefulset.go
operator/pkg/controllers/storage/storage_reconciler.go
test/integration/operator/controllers/storage_test.go

Fixes #https://issues.redhat.com/browse/ACM-16818

:seedling: Utilize configmap to initialize pg users and databases

---

operator/pkg/controllers/managedhub/managedhub_controller.go

https://issues.redhat.com/browse/ACM-17611
Fixes #

fix mgh can not deleted when there is no managedcluster

---

doc/global_hub_builtin_postgresql.md
operator/pkg/controllers/storage/postgres_statefulset.go
operator/pkg/controllers/storage/storage_reconciler.go
test/integration/operator/controllers/storage_test.go

:seedling: Format the keys for postgres customized user

---

operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
operator/pkg/controllers/transporter/protocol/strimzi_transporter_test.go

https://issues.redhat.com/browse/ACM-17612
Fixes #

fix kafka recreate when change AvailabilityConfig

---

operator/pkg/controllers/transporter/protocol/strimzi_transporter.go

The default kafkatopic is `gh-status.*`, so we should replace `.*` to ""
https://issues.redhat.com/browse/ACM-17612
Fixes #

fix kafka recreate when mgh change

---

manager/pkg/controllers/migration_controller.go

:bug: Watch msa for deletion

---

.github/dependabot.yml

Update dependabot with ok-to-test label

---

.tekton/multicluster-global-hub-agent-globalhub-1-4-pull-request.yaml
.tekton/multicluster-global-hub-agent-globalhub-1-4-push.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-4-pull-request.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-4-push.yaml
.tekton/multicluster-global-hub-operator-bundle-globalhub-1-4-pull-request.yaml
.tekton/multicluster-global-hub-operator-bundle-globalhub-1-4-push.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-4-pull-request.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-4-push.yaml

Preventing redundant builds - https://konflux.pages.redhat.com/docs/users/how-tos/configuring/redundant-rebuilds.html
Fixes #

:sparkles: Preventing redundant builds

---

test/Makefile
test/e2e/backup_test.go
test/e2e/grafana_test.go
test/e2e/prune_test.go
test/e2e/suite_test.go
test/e2e/utils/render.go
test/manifest/resources/kustomization.yaml
test/script/e2e_clean_globalhub.sh
test/script/e2e_kafka.sh
test/script/e2e_prow.sh
test/script/e2e_run.sh
test/script/e2e_run_byo.sh

This pr add the test case in e2e:
- install globalhub in mgh namespace.
Fixes #

Add test case: install globalhub in mgh namespace

---

test/Makefile
test/script/e2e_run_qe.sh

add qe e2e cases in each pr

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/pkg/controllers/webhook/webhook_controller.go
operator/pkg/controllers/webhook/webhook_controller_test.go

1. did not pass `Manager` in. but we use it, that is the panic reason
2. Need to give the proper permissions to bind to the global managedclusterset
3. Need to allow service ca to inject caBundle into mutatingwebhookconfigration
Fixes https://issues.redhat.com/browse/ACM-18293

:bug: Webhook

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/pkg/controllers/webhook/webhook_controller.go
operator/pkg/controllers/webhook/webhook_controller_test.go

ref: https://github.com/stolostron/multicluster-global-hub/pull/1426

Manually cherry-pick 1426

---

operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

:bug: Format installAgentOnLocal

---

doc/reserved_names/README.md
pkg/constants/constants.go
pkg/transport/controller/controller.go
pkg/transport/controller/controller_test.go

https://issues.redhat.com/browse/ACM-18120
Fixes #

fix agent can not connect to kafka in dr case

---

operator/pkg/controllers/transporter/protocol/strimzi_transporter.go

fix kafka recreate when mgh config change

---

test/e2e/suite_test.go
test/e2e/utils/options.go
test/script/e2e_postgres.sh
test/script/e2e_prow.sh
test/script/e2e_run.sh
test/script/util.sh

Fix This file contained potentially sensitive information issue
cannot see the logs of e2e.
Fixes #

Fix This file contained potentially sensitive information issue

---

.github/workflows/go.yml
.tekton/multicluster-global-hub-agent-globalhub-1-4-pull-request.yaml
.tekton/multicluster-global-hub-agent-globalhub-1-4-push.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-4-pull-request.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-4-push.yaml
.tekton/multicluster-global-hub-operator-bundle-globalhub-1-4-pull-request.yaml
.tekton/multicluster-global-hub-operator-bundle-globalhub-1-4-push.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-4-pull-request.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-4-push.yaml
agent/Dockerfile
manager/Dockerfile
operator/Dockerfile

1. update to use golang 1.23
2. update konflux configuration towards to release-2.13 branch
Fixes #

:seedling:  Do hygiene

---

samples/cloudevent/confluent-receiver/main.go
samples/cloudevent/confluent-sender/main.go
samples/config/confluent_config.go

update the samples

---

agent/pkg/controllers/init_controller.go
agent/pkg/spec/spec.go
agent/pkg/spec/syncers/clusterlabel_syncer.go
pkg/transport/controller/controller.go
pkg/transport/controller/controller_test.go
test/Makefile
test/e2e/cluster_test.go
test/e2e/suite_test.go
test/integration/manager/migration/migration_test.go
test/script/e2e_clean_globalhub.sh
test/script/e2e_cleanup.sh
test/script/e2e_log.sh
test/script/e2e_run.sh

The kafka consumer will not reconnect when it close. So we need to reconnect the consumer.
Fixes #

fix e2e failed

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

Fixes #. https://issues.redhat.com/browse/ACM-18876

Bump version to 1.3.3

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

Bump version to 1.2.2

---

renovate.json

ignore pin, pinDigest, digest, lockFileMaintenance, rollback, bump, replacement
and group packages
Fixes #

:seedling: Configure renovate

---

go.mod
go.sum

https://issues.redhat.com/browse/ACM-18998
Fixes #

Upgrade addon framework to 0.12.0

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

pin 1.2.3 verion

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

pin 1.4.1 bundle version

---

operator/pkg/controllers/agent/local_agent_controller.go

https://issues.redhat.com/browse/ACM-19731
Fixes #

fix local agent restart

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/metadata/annotations.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

Bump to 1.5.0

---

agent/pkg/status/syncers/events/handlers/local_root_policy_handler.go
agent/pkg/status/syncers/policies/handlers/status_event_handler.go

https://issues.redhat.com/browse/ACM-19930
Fixes #

fix redundant log in agent

---

test/script/e2e_run_qe.sh

disable migration cases in e2e

---

agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_from_syncer_test.go
agent/pkg/spec/syncers/migration_to_syncer.go
agent/pkg/spec/syncers/migration_to_syncer_test.go
go.sum
manager/pkg/migration/migration_cleaning.go
manager/pkg/migration/migration_deploying.go
manager/pkg/migration/migration_initializing.go
manager/pkg/migration/migration_registering.go
manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
operator/api/migration/v1alpha1/managedclustermigration_types.go
test/integration/manager/migration/migration_test.go
test/integration/manager/status/managedclusetrmigration_handler_test.go

:seedling: Rename the condition type and phase

---

manager/pkg/migration/migration_cleaning.go
manager/pkg/migration/migration_deploying.go
manager/pkg/migration/migration_initializing.go
manager/pkg/migration/migration_registering.go
test/integration/manager/migration/migration_test.go

Fixes # https://issues.redhat.com/browse/ACM-19935

:seedling: Remove the duplicated kafka message

---

operator/api/migration/v1alpha1/managedclustermigration_types.go
operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml

Fixes # https://issues.redhat.com/browse/ACM-19657

:bug: Show the phase status in migration

---

manager/pkg/migration/migration_validating.go
test/integration/manager/migration/migration_test.go

Fixes # https://issues.redhat.com/browse/ACM-19661

:sparkles: Hub validation for migration resource

---

operator/pkg/config/scheme_config.go
operator/pkg/controllers/manager/manager_reconciler.go
operator/pkg/controllers/meta.go
test/integration/operator/controllers/manager_test.go

Fixes # https://issues.redhat.com/browse/ACM-17949

:bug: Remove the migration when deleting the global hub cr

---

manager/pkg/migration/migration_registering.go

:seedling: Add registering condition in migration cr

---

operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml

kessel team will make the breaking changes this week. so we need to use the fixed commit sha instead.
Fixes #

:seedling:  Use fixed commit sha for kessel

---

agent/pkg/spec/dispatcher.go
agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_from_syncer_test.go
agent/pkg/spec/syncers/migration_to_syncer.go
pkg/transport/assembler_test.go
pkg/transport/consumer/generic_consumer.go
pkg/transport/controller/controller.go
pkg/transport/producer/generic_producer.go
pkg/transport/producer/generic_producer_test.go
test/integration/agent/spec/suite_test.go
test/integration/agent/status/suite_test.go
test/integration/manager/migration/migration_test.go
test/integration/manager/migration/suite_test.go
test/integration/manager/spec/suite_test.go
test/integration/manager/status/suite_test.go

We need to make sure the consumer and producer can be created successfully for migration topic
Fixes #
- tested in a brand new environment

:bug: Resend msg

---

agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_from_syncer_test.go
agent/pkg/spec/syncers/migration_to_syncer.go
agent/pkg/spec/syncers/migration_to_syncer_test.go
manager/pkg/migration/migration_initializing.go
manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
pkg/bundle/migration/managedcluster_migration.go
samples/cloudevent/confluent-receiver/main.go
samples/cloudevent/confluent-sender/main.go
samples/config/confluent_config.go
samples/kafka/confluent_admin/main.go
test/integration/manager/migration/migration_test.go
test/integration/manager/status/managedclusetrmigration_handler_test.go

Fixes # https://issues.redhat.com/browse/ACM-20259

:sparkles:  Initializing migration

---

agent/pkg/status/filter/time_filter.go
agent/pkg/status/filter/time_filter_test.go
test/integration/agent/status/localpolicy_event_test.go

:bug: Fix the integration test

---

test/integration/agent/status/localpolicy_event_test.go

:seedling: fix the policy event integration test

---

.tekton/multicluster-global-hub-agent-globalhub-1-5-push.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-5-push.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-5-push.yaml

should use `push` instead of `pull_request` for push configurations.
Fixes #

:bug: Correct Konflux Configure

---

operator/pkg/controllers/storage/database/2.tables.sql
operator/pkg/controllers/storage/database/4.trigger.sql
pkg/database/models/status.go

Fixes # https://issues.redhat.com/browse/ACM-20072

:seedling: Remove migration db table

---

operator/pkg/controllers/meta.go

Error Message in manager when deleting the mgh cr
```bash
W0430 01:46:37.243765       1 reflector.go:569] pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: failed to list *v1.ManagedCluster: managedclusters.cluster.open-cluster-management.io is forbidden: User "system:serviceaccount:mgh:multicluster-global-hub-manager" cannot list resource "managedclusters" in API group "cluster.open-cluster-management.io" at the cluster scope
E0430 01:46:37.243812       1 reflector.go:166] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.32.3/tools/cache/reflector.go:251: Failed to watch *v1.ManagedCluster: failed to list *v1.ManagedCluster: managedclusters.cluster.open-cluster-management.io is forbidden: User \"system:serviceaccount:mgh:multicluster-global-hub-manager\" cannot list …
```

:bug: Fix the manager rbac error for the migration deletion

---

renovate.json

:bug: Update renovate according the suggestion from konflux experts

---

manager/pkg/status/handlers/managedcluster/managedcluster_handler.go
manager/pkg/status/handlers/managedhub/hub_cluster_info_handler.go
manager/pkg/status/handlers/policy/local_policy_spec_handler.go
manager/pkg/status/handlers/policy/local_policy_spec_handler_test.go
pkg/database/models/common.go

https://issues.redhat.com/browse/ACM-20027
https://issues.redhat.com/browse/ACM-20147
Fixes #

move inventory: policy-spec

---

agent/pkg/spec/spec.go
agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_from_syncer_test.go
agent/pkg/spec/syncers/migration_to_syncer.go
agent/pkg/spec/syncers/migration_to_syncer_test.go
operator/pkg/controllers/transporter/protocol/manifests/global-hub-kafka-user.yaml
operator/pkg/controllers/transporter/protocol/strimzi_kafka_controller.go
operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
pkg/transport/config/confluent_config.go
pkg/transport/config/rest_config.go
pkg/transport/controller/controller.go
pkg/utils/utils.go
samples/config/sarama_config.go

:seedling: Correct the type error

---

.tekton/multicluster-global-hub-agent-globalhub-1-5-pull-request.yaml
.tekton/multicluster-global-hub-agent-globalhub-1-5-push.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-5-pull-request.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-5-push.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-5-pull-request.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-5-push.yaml
agent/Containerfile.agent
manager/Containerfile.manager
operator/Containerfile.operator

:bug: fix EC

---

operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/pkg/config/transport_config.go
test/manifest/kafka/kafka-cluster/kafka-topics.yaml
test/script/kessel_e2e_setup.sh

:sparkles:  Remove migration from API

---

manager/pkg/migration/migration_initializing.go
manager/pkg/migration/migration_validating.go

:bug: Throw the error if no valid migrating clusters are found

---

manager/pkg/status/handlers/managedcluster/managedcluster_handler.go
manager/pkg/status/handlers/managedcluster/managedcluster_handler_test.go
test/integration/manager/status/suite_test.go

move-inventory: cluster

---

operator/pkg/controllers/inventory/manifests/spicedb-operator/6.spicedb-operator.deploy.yaml
test/script/kessel_e2e_setup.sh

We use latest spicedb image, but the spicedb operator changed the deployment, so we should also change it.
https://github.com/project-kessel/spicedb-operator/commit/e06b36ba9e095846828902a986bd10ffa04734e2
https://github.com/project-kessel/spicedb-operator/commit/e0be57858ab98a6bbc46b7d86f7bf9aa700a4fc6
Fixes #

fix spicedb can not start

---

renovate.json

:bug: Disable minor and major for indirect

---

agent/cmd/main.go

https://issues.redhat.com/browse/ACM-20639
Fixes #

fix agent can not start when disable local-cluster

---

manager/pkg/migration/migration_validating.go

Fixes # https://issues.redhat.com/browse/ACM-20708

:bug: Report cluster not found error during validation

---

go.mod
go.sum
manager/pkg/status/handlers/policy/local_complete_handler.go
manager/pkg/status/handlers/policy/local_compliance_handler.go
manager/pkg/status/handlers/policy/local_compliance_handler_test.go
manager/pkg/status/handlers/policy/local_policy_spec_handler.go
manager/pkg/status/handlers/policy/local_policy_spec_handler_test.go
operator/pkg/controllers/manager/manager_reconciler.go
test/e2e/localpolicy_test.go
test/integration/manager/status/local_policy_compliance_handler_test.go
test/integration/operator/controllers/manager_test.go

https://issues.redhat.com/browse/ACM-20148
https://issues.redhat.com/browse/ACM-20027
Fixes #

Move inventory: policy compliance

---

agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_to_syncer.go
manager/pkg/migration/migration_cleaning.go
manager/pkg/migration/migration_initializing.go

Fixes # https://issues.redhat.com/browse/ACM-20709
Related: https://issues.redhat.com/browse/ACM-19540, https://issues.redhat.com/browse/ACM-20741

:bug: Cleaning up the resources if the migration failed

---

agent/cmd/main.go
agent/pkg/configs/agent_config.go
operator/pkg/config/multiclusterglobalhub_config.go
operator/pkg/controllers/agent/local_agent_controller.go
operator/pkg/controllers/agent/local_agent_controller_test.go
operator/pkg/controllers/agent/manifests/deployment.yaml
operator/pkg/controllers/agent/standalone_agent_controller.go
operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
test/integration/operator/controllers/agent/cluster_none_addon_test.go
test/integration/operator/controllers/agent/local_agent_test.go
test/integration/operator/webhook/admission_suite_test.go

Fixes #
https://issues.redhat.com/browse/ACM-20560

fix rename local-cluster issue

---

agent/cmd/main.go
agent/cmd/main_test.go
agent/pkg/controllers/init_controller.go
agent/pkg/status/status.go
agent/pkg/status/syncers/configmap/config_controller.go
manager/pkg/migration/migration_controller.go
operator/pkg/constants/constants.go
operator/pkg/controllers/agent/addon/addon_manager.go
operator/pkg/controllers/agent/addon/default_agent_controller.go
operator/pkg/controllers/agent/addon/default_agent_controller_test.go
operator/pkg/controllers/agent/addon/manifests/templates/agent/multicluster-global-hub-agent-configmap.yaml
operator/pkg/controllers/agent/addon/manifests/templates/agent/multicluster-global-hub-agent-namespace.yaml
operator/pkg/controllers/agent/addon/manifests/templates/hostedagent/multicluster-global-hub-agent-configmap.yaml
operator/pkg/controllers/agent/addon/manifests/templates/hostedagent/multicluster-global-hub-agent-inventory-sever-ca-cert.yaml
operator/pkg/controllers/agent/addon/manifests/templates/hostedagent/multicluster-global-hub-agent-kafka-cluster-ca-cert.yaml
operator/pkg/controllers/agent/addon/manifests/templates/hostedagent/multicluster-global-hub-agent-transport-config-secret.yaml
operator/pkg/controllers/agent/addon/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-deployment.yaml
operator/pkg/controllers/agent/addon/manifests/templates/hostedagent/multicluster-global-hub-hosting-agent-role.yaml
operator/pkg/utils/utils.go
pkg/constants/constants.go
test/integration/operator/controllers/agent/cluster_hosted_addon_test.go
test/integration/operator/controllers/agent/suite_test.go
test/integration/operator/controllers/manager_test.go

https://issues.redhat.com/browse/ACM-20744
Fixes #

:sparkles: Hosted mode

---

operator/pkg/controllers/transporter/protocol/strimzi_transporter.go
pkg/transport/controller/controller.go
pkg/transport/controller/controller_test.go
pkg/transport/kafka_config.go
test/integration/operator/controllers/agent/suite_test.go

https://issues.redhat.com/browse/ACM-19776
Fixes #

remove upgrade logic from 1.3->1.4

---

.github/workflows/go.yml
manager/pkg/migration/migration_controller.go
manager/pkg/migration/migration_controller_test.go
manager/pkg/migration/migration_initializing.go
manager/pkg/migration/migration_validating.go
operator/api/migration/v1alpha1/managedclustermigration_types.go
operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml

https://issues.redhat.com/browse/ACM-19541
Fixes #

handle 1 migration at the same time

---

manager/pkg/migration/migration_controller.go

fix message format

---

operator/pkg/controllers/agent/addon/default_agent_controller.go

skip local cluster in default agent

---

renovate.json

:bug: refine the definition of renovate

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml
operator/pkg/config/multiclusterglobalhub_config.go

:sparkles: Remove dev preview images from bundle

---

agent/Containerfile.agent
manager/Containerfile.manager

fixed the issue `/usr/local/bin/agent: error while loading shared libraries: librdkafka.so.1: cannot open shared object file: No such file or directory`
Fixes #

:bug:  Add LD_LIBRARY_PATH env

---

agent/pkg/spec/syncers/migration_from_syncer.go

:bug: Fix the restConfig is nil for non cache client

---

doc/global_hub_cluster_migration.md
operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

Make the feature gate more easy to use in the OCP operator console

---

manager/pkg/migration/migration_cleaning.go

Fixes #https://issues.redhat.com/browse/ACM-21005

:bug: Add message for failed migration cleanup 

---

agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_from_syncer_test.go
manager/pkg/migration/migration_deploying.go
manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler_test.go
test/integration/manager/migration/migration_test.go

Fixes # https://issues.redhat.com/browse/ACM-21004

:bug: Report the resource not found error in deploying stage

---

operator/pkg/controllers/agent/addon/hosted_agent_controller.go

fix mgh can not delete

---

.github/scripts/auto_review.py
.github/workflows/auto_code_review.yml

Adding a worflow to trigger automatic code review. This requires adding a secret called OPENAI_API_KEY. I can add mine if I am allowed the permission.
Henceforth, whenever a PR is opened, synchronize, reopened this bot will be called in and code review will be run. This can also be run manually anytime under Actions tab.
In addition to this we should also add code review by sourcery by clicking from here - https://github.com/sourcery-ai/sourcery?tab=readme-ov-file#getting-started. (This also uses openai under the covers).
We should check out both and see which works better. And we can make our code reviewer much smarter - if needed - then what it is now.
Fixes #

📝 Auto PR Review

---

operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

https://issues.redhat.com/browse/ACM-21055
Fixes #

update description for installAgentOnLocal

---

manager/pkg/migration/migration_cleaning.go
manager/pkg/migration/migration_cleaning_test.go

Fixes # https://issues.redhat.com/browse/ACM-21114

:bug: cleanup condition show be true before the migration initialization

---

agent/pkg/spec/syncers/migration_to_syncer.go

Fixes # https://issues.redhat.com/browse/ACM-21113

:seedling:  report the deploying exists error during syncing resources

---

manager/pkg/migration/migration_initializing.go

MigrationStarted should not have timeout

---

manager/pkg/migration/migration_cleaning.go

Fixes # https://issues.redhat.com/browse/ACM-21114

:bug: cleanup nil panic

---

operator/pkg/controllers/agent/addon/hosted_agent_controller.go

fix mgh can not delete in hosted mode

---

doc/global_hub_cluster_migration.md

:book: migration doc crrection

---

rpms.in.yaml

ref: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1749779418360049
Fixes #

specify which stage to use

---

operator/pkg/webhook/admission_handler.go

When importing a managed cluster into global hub,  the GH addon should not be installed.
Everything works as expected when the Global Hub has the local cluster enabled.
However, when I try to import a cluster into a Global Hub that hasn't enabled the local cluster, the following error occurs:
```bash
admission webhook "global-hub.open-cluster-management.io" denied the request: the local clusters must be enabled
```
Fixes #
https://issues.redhat.com/browse/ACM-21552

import managed cluster into global hub

---

agent/pkg/status/syncers/managedcluster/managed_cluster_syncer.go

Reverts stolostron/multicluster-global-hub#1752

Revert "do not collect hosted reginal hub info"

---

test/manifest/kafka/kafka-cluster/kafka-cluster.yaml
test/script/e2e_prow.sh
test/script/util.sh

[release-2.13] fix e2e error in 2.13

---

.github/workflows/auto_code_review.yml
rpms.in.yaml

:bug:  Correct configs format

---

agent/pkg/status/syncers/security/stackrox_syncer.go
operator/pkg/controllers/agent/local_agent_controller.go
operator/pkg/controllers/agent/manifests/deployment.yaml
operator/pkg/controllers/agent/standalone_agent_controller.go

ref: https://issues.redhat.com/browse/ACM-21722
Need to pass enable-stackrox-integration into the local agent
Fixes #

:bug: Fix RHACS integration issues

---

.github/workflows/go.yml
.tekton/multicluster-global-hub-agent-globalhub-1-6-pull-request.yaml
.tekton/multicluster-global-hub-agent-globalhub-1-6-push.yaml
agent/Containerfile.agent
manager/Containerfile.manager
operator/Containerfile.operator
operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/metadata/annotations.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml

:sparkles:  Bump to 1.6

---

agent/pkg/status/status.go
pkg/constants/constants.go
pkg/transport/config/confluent_config.go
pkg/transport/producer/generic_producer.go

enlarge the message size to 10MB to resolve the issue the customer met. This is a temporary solution. for the longer term, we need to improve our transport logic to allow delta bundle instead of full bundle.
Fixes # https://issues.redhat.com/browse/ACM-21906

:bug: Enlarge the message size to 10MB

---

agent/pkg/status/status.go
pkg/constants/constants.go
pkg/transport/config/confluent_config.go
pkg/transport/producer/generic_producer.go

ref: #1786
Fixes #
https://issues.redhat.com/browse/ACM-21907

:bug:  Incomplete data in global hub dashboards

---

rpms.lock.yaml

Fixes # https://issues.redhat.com/browse/ACM-21914

Update rpm manually to address EC failure

---

manager/pkg/migration/migration_controller.go

1. align all the migration status 
2. use it to assert whether the migration is started
Fixes #

add started condition for every the migration instance

---

.github/workflows/auto_code_review.yml

:bug: Test AI code review

---

agent/pkg/status/status.go
manager/pkg/status/conflator/element_complete.go
manager/pkg/status/handlers/policy/local_replicated_policy_event_handler.go
manager/pkg/status/handlers/policy/local_root_policy_event_handler.go
pkg/database/common/util.go
pkg/transport/controller/controller.go

ref: https://issues.redhat.com/browse/ACM-21815
Fixes #

Disable app related syncers by default

---

operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml

https://issues.redhat.com/browse/ACM-21869
Fixes #

set InstallAgentOnLocal to true by default

---

agent/pkg/status/emitters/emitter.go
agent/pkg/status/emitters/emitter_test.go
agent/pkg/status/emitters/object_emitter.go
agent/pkg/status/generic/object_controller.go
agent/pkg/status/generic/object_controller_test.go
pkg/bundle/generic/generic_bundle.go
pkg/bundle/version/version.go
pkg/enum/sync_mode.go
pkg/transport/consumer/generic_consumer.go
pkg/transport/producer/generic_producer.go
samples/cloudevent/confluent-receiver/main.go

:sparkles: Define the lightweight bundle and emitter for policies and clusters

---

operator/Makefile
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/manager/manager.yaml

Remove inventory-api image

---

.tekton/multicluster-global-hub-manager-globalhub-1-4-pull-request.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-4-push.yaml

Correct manager's image

---

agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_to_syncer.go
agent/pkg/spec/syncers/migration_to_syncer_test.go
manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler_test.go
pkg/bundle/migration/managedcluster_migration.go
test/integration/agent/migration/migration_from_syncer_test.go
test/integration/agent/migration/migration_to_syncer_test.go
test/integration/agent/migration/suite_test.go
test/manifest/crd/config.open-cluster-management.io_klusterletconfigs.crd.yaml

Fixes # https://issues.redhat.com/browse/ACM-22487

Optimize global hub agent syncer for migration

---

.gitignore
agent/pkg/spec/syncers/migration_from_syncer.go
agent/pkg/spec/syncers/migration_from_syncer_test.go
agent/pkg/spec/syncers/migration_to_syncer.go
agent/pkg/spec/syncers/migration_to_syncer_test.go
doc/global_hub_cluster_migration.md
manager/pkg/migration/migration_cleaning.go
manager/pkg/migration/migration_cleaning_test.go
manager/pkg/migration/migration_controller.go
manager/pkg/migration/migration_controller_test.go
manager/pkg/migration/migration_deploying.go
manager/pkg/migration/migration_deploying_test.go
manager/pkg/migration/migration_initializing.go
manager/pkg/migration/migration_initializing_test.go
manager/pkg/migration/migration_registering.go
manager/pkg/migration/migration_registering_test.go
manager/pkg/migration/migration_rollbacking.go
manager/pkg/migration/migration_rollbacking_test.go
manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler.go
manager/pkg/status/handlers/clustermigartion/managedclustermigration_handler_test.go
operator/api/migration/v1alpha1/managedclustermigration_types.go
operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml
pkg/bundle/migration/managedcluster_migration.go
test/integration/agent/migration/migration_from_syncer_test.go
test/integration/agent/migration/migration_to_syncer_test.go
test/integration/agent/migration/suite_test.go
test/integration/manager/migration/migration_error_scenarios_test.go
test/integration/manager/migration/migration_phase_test.go

Fixes # https://issues.redhat.com/browse/ACM-22602
Reference: https://github.com/stolostron/multicluster-global-hub-operator-bundle/pull/191

:sparkles: Rollback condition and phase

---

manager/pkg/migration/migration_validating.go
manager/pkg/migration/migration_validating_test.go
test/integration/manager/migration/migration_error_scenarios_test.go
test/integration/manager/migration/suite_test.go

cluster status must be ready
Non local cluster -> validate managed hub label
Local cluster -> agent - deployment is enabled
https://issues.redhat.com/browse/ACM-22754
Fixes #

validate migration from/to hub

---

manager/pkg/status/conflator/conflation_unit.go
manager/pkg/status/conflator/element_delta.go
operator/pkg/controllers/backup/backup_reconcile.go

log adjustment for dropping bundle

---

.github/workflows/go.yml
agent/Containerfile.agent
agent/Dockerfile
go.mod
manager/Containerfile.manager
manager/Dockerfile
operator/Containerfile.operator
operator/Dockerfile
test/script/util.sh

Upgrade Go from 1.23.6 to 1.24.4 Assisted-by: Claude Code

---

operator/api/migration/v1alpha1/managedclustermigration_types.go
operator/bundle/manifests/global-hub.open-cluster-management.io_managedclustermigrations.yaml
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/config/crd/bases/global-hub.open-cluster-management.io_managedclustermigrations.yaml
operator/config/manifests/bases/multicluster-global-hub-operator.clusterserviceversion.yaml
test/integration/manager/migration/migration_validation_test.go

Fixes # https://issues.redhat.com/browse/ACM-23319

:sparkles: Update API to add IncludedManagedClustersPlacementRef

---

.tekton/multicluster-global-hub-agent-globalhub-1-6-push.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-6-push.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-6-push.yaml

:sparkles: Add nudge bundle repo

---

manager/cmd/main.go
operator/api/operator/v1alpha4/multiclusterglobalhub_types.go
operator/bundle/manifests/multicluster-global-hub-operator.clusterserviceversion.yaml
operator/bundle/manifests/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
operator/config/crd/bases/operator.open-cluster-management.io_multiclusterglobalhubs.yaml
pkg/transport/controller/controller.go

Fixes # https://issues.redhat.com/browse/ACM-23340

:sparkles: Add customized the consumer group id in the API

---

manager/pkg/migration/migration_controller.go
manager/pkg/migration/migration_validating.go
manager/pkg/migration/migration_validating_test.go

add migration cluster list to configmap

---

agent/pkg/spec/migration/migration_from_syncer.go

remove kubectl apply annotation in migrating bundle

---

ai-doc/migration-sequence-diagram.md

:sparkles:  Add migration sequence diagram

---

manager/pkg/migration/migration_pending.go
test/integration/manager/migration/suite_test.go

https://issues.redhat.com/browse/ACM-23610
Fixes #

should NOT handle migration which is created in other namespace

---

doc/migration/global_hub_cluster_migration.md
doc/migration/migration_performance.md

https://issues.redhat.com/browse/ACM-21857
Fixes #

migration performance test plan

---

agent/pkg/spec/migration/migration_from_syncer.go
agent/pkg/spec/migration/migration_from_syncer_test.go
agent/pkg/spec/migration/migration_to_syncer.go
agent/pkg/spec/migration/migration_to_syncer_test.go
agent/pkg/spec/spec.go
manager/pkg/migration/migration_cleaning.go
manager/pkg/migration/migration_eventstatus.go
manager/pkg/migration/migration_registering.go
manager/pkg/migration/migration_rollbacking.go
manager/pkg/migration/migration_validating.go
manager/pkg/migration/migration_validating_test.go
test/integration/agent/migration/migration_from_syncer_test.go
test/integration/agent/migration/migration_to_syncer_test.go
test/integration/agent/migration/suite_test.go
test/integration/manager/migration/migration_error_scenarios_test.go
test/integration/manager/migration/migration_phase_test.go
test/integration/manager/migration/suite_test.go

https://issues.redhat.com/browse/ACM-23445
Fixes #

move validating logic to agent

---

rpms.in.yaml

ref: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1758857069154989
Fixes #

Remove containerfile and add bare

---

.tekton/multicluster-global-hub-agent-globalhub-1-6-push.yaml
.tekton/multicluster-global-hub-manager-globalhub-1-6-push.yaml
.tekton/multicluster-global-hub-operator-globalhub-1-6-push.yaml

add slack notification
